---
title: "PIEN analysis"
author: "Katie Nigro"
date: "2024-05-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Set up 

##Packages

```{r}
#load required packages
library(terra)
library(ggplot2)
library(ggspatial)
library(tidyterra)
library(dplyr)
library(stringr)
#library(ClimateNAr)
library(ggfortify)
library(RColorBrewer)
library(tidyr)
library(lme4)
library(lmerTest)
library(car)
library(viridis)
library(dplR)
library(ggpubr)
library(ggrepel)
library(ggcorrplot)
library(MuMIn)
library(vegan)
library(cluster)
library(MASS)
library(indicspecies)
library(SPEI)
library(lattice)
```

##Plot locations

```{r}
#read in site and provenance locations
us <- geodata::gadm(country = "USA",  level = 1, resolution = 2,
             path = "C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject")
west_states<- c("Arizona","Colorado","Idaho","Montana","Nevada","New Mexico","South Dakota","North Dakota","Nebraska","Utah","Wyoming","California","Oregon","Washington","Kansas","Oklahoma","Texas")
westernus <- us[match(toupper(west_states),toupper(us$NAME_1)),]

##use coordinates adjusted based on elevation and google maps
adjusted_coords<- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/PIEN_corrected_coords.csv")

adjusted_provs<- vect(adjusted_coords, geom=c("long_corrected","lat_corrected"), crs=crs(us))

ggplot()+
  geom_spatvector(data=westernus)+
  geom_spatvector(data=adjusted_provs, color="maroon")

#make key for provenance names
prov_names<-adjusted_coords %>% dplyr::select(Provenance, no) %>% 
 separate_wider_delim(Provenance, delim=" ", names=c("first","second","third"), too_few = "align_start", cols_remove=FALSE) %>% 
  separate_wider_delim(first, delim= "-", names=c("first","2"), too_few="align_start") %>% 
    separate_wider_delim(second, delim= "-", names=c("second","3"), too_few="align_start") %>% 
  mutate(across(everything(), ~ replace(.x, is.na(.x), ""))) %>% 
  mutate(code=paste(substr(first,0,2),substr(`2`,0,1),substr(second,0,2),substr(`3`,0,1),third, sep="")) %>% 
  dplyr::select(c(Provenance,no,code)) %>% 
  mutate(no=as.integer(no))
```

#Climate

##ClimateNA

```{r}
#read in climate from climateNA

#first download climate normals from ClimateNA then read in to R
mastervarList <- c('mat', 'map','td','mcmt','msp','shm','nffd','bFFP','eFFP','mwmt','dd_0','dd5','emt','cmd','pas','PPT_sp','PPT_sm') #these are all the climate variables I want

# rasterDownload (region='NA',res='4000m',period='Normal_1961_1990',varList="PPT_sm",sDir='C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/PIENproject/ClimateNA')

normal_clim_rasters <- c()
for(i in 1:length(mastervarList)){
  normal_clim_rasters[i]<- paste("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/PIENproject/ClimateNA/NA/4000m/Normal_1961_1990/",mastervarList[i],".tif",sep="")
}

clim_raster_stack <- rast(normal_clim_rasters)

prov_clim_adjusted_bi <- terra::extract(clim_raster_stack, adjusted_provs, method='bilinear') %>% cbind(as.data.frame(adjusted_provs)) %>% cbind(crds(adjusted_provs)) %>% 
  mutate(smrpb = PPT_sm/PPT_sp, monsoonality = msp/map)

prov_clim_adjusted_bi_long<- prov_clim_adjusted_bi %>% 
  mutate(no=ifelse(is.na(no),"Plan",no)) %>% 
  dplyr::select(c(Provenance,MAT:PPT_sm, smrpb, monsoonality)) %>% 
  pivot_longer(MAT:monsoonality) %>% 
  mutate(type="adj bilinear") 


#nffd x map
ggplot()+
  geom_point(data=prov_clim_adjusted_bi, size=3, aes(x=nffd, y=map), col="aquamarine3")+
  geom_text(data=prov_clim_adjusted_bi, aes(x=nffd, y=map, label=Provenance), vjust=0.5, hjust=-.1)+
  theme_bw()+
  theme(legend.position = 'none')

#nffd x TD
ggplot()+
  geom_point(data=prov_clim_adjusted_bi, size=3, aes(x=nffd, y=TD), col="aquamarine3")+
  geom_text(data=prov_clim_adjusted_bi, aes(x=nffd, y=TD, label=Provenance), vjust=1)+
  theme_bw()+
  theme(legend.position = 'none')
```

```{r}
#compare climates of provenances
prov_vars<- prov_clim_adjusted_bi %>% 
  dplyr::select(c(Provenance,MAT:pas,smrpb)) %>% 
  left_join(prov_names) %>% 
  pivot_longer(MAT:smrpb, names_to = "var", values_to = "value")

ggplot(prov_vars, aes(x=factor(Provenance), y=value))+
  geom_point(size=4)+
  facet_wrap(~var, scales="free")+
  scale_color_manual(values=heat.colors(21))+
  theme(axis.text.x = element_text(angle=45,hjust=1), legend.position = 'none')
```

##PRISM

```{r}
#read in files
ppt_comb_plantation<- read.csv("ppt_comb_plantation.csv")
tmax_comb_plantation<- read.csv("tmax_comb_plantation.csv")
tmin_comb_plantation<- read.csv("tmin_comb_plantation.csv")
tmean_comb_plantation<- read.csv("tmean_comb_plantation.csv")
vpdmax_comb_plantation<- read.csv("vpdmax_comb_plantation.csv")
vpdmin_comb_plantation<- read.csv("vpdmin_comb_plantation.csv")

ppt_comb_all<- read.csv("ppt_comb_all.csv")
tmax_comb_all<- read.csv("tmax_comb_all.csv")
tmin_comb_all<- read.csv("tmin_comb_all.csv")
tmean_comb_all<- read.csv("tmean_comb_all.csv")
vpdmax_comb_all<- read.csv("vpdmax_comb_all.csv")
vpdmin_comb_all<- read.csv("vpdmin_comb_all.csv")
```

```{r}
##calculate seasonal PRISM values

##ppt
ppt_summed <- as.data.frame(ppt_comb_plantation) %>% 
  mutate(ppt = as.numeric(ppt), year=as.integer(year)) %>%
  filter(!is.na(ppt)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(ppt = sum(ppt)) 

ggplot(ppt_summed %>% filter(CN=="Plantation"), aes(x=year, y=ppt)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(ppt_summed %>% filter(CN=="Plantation") %>% pull(ppt)), col="red")

##seasonal ppt
ppt_seasonal_plantation <- ppt_comb_plantation %>% 
  filter(month %in% c(6,7,8)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_sm = sum(ppt)) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(5,6,7,8,9)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_gs = sum(ppt))) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(12,1,2)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_wt = sum(ppt))) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(9,10,11)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_fa = sum(ppt))) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(3,4,5)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_sp = sum(ppt))) %>% 
  left_join(ppt_summed) 


##tmin
tmin_summed <- as.data.frame(tmin_comb_plantation) %>% 
  mutate(tmin = as.numeric(tmin), year=as.integer(year)) %>%
  filter(!is.na(tmin)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(tmin = mean(tmin)) 

ggplot(tmin_summed %>% filter(CN=="Plantation"), aes(x=year, y=tmin)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(tmin_summed %>% filter(CN=="Plantation") %>% pull(tmin)), col="red")

##tmax
tmax_summed <- as.data.frame(tmax_comb_plantation) %>% 
  mutate(tmax = as.numeric(tmax), year=as.integer(year)) %>%
  filter(!is.na(tmax)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(tmax = mean(tmax))

ggplot(tmax_summed %>% filter(CN=="Plantation"), aes(x=year, y=tmax)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(tmax_summed %>% filter(CN=="Plantation") %>% pull(tmax)), col="red")

##tmean
tmean_summed <- as.data.frame(tmean_comb_plantation) %>% 
  mutate(tmean = as.numeric(tmean), year=as.integer(year)) %>%
  filter(!is.na(tmean)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(tmean = mean(tmean)) 

ggplot(tmean_summed %>% filter(CN=="Plantation"), aes(x=year, y=tmean)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(tmean_summed %>% filter(CN=="Plantation") %>% pull(tmean)), col="red")

##seasonal temps
all_temps <- bind_rows(tmean_comb_plantation %>% pivot_longer(tmean), tmin_comb_plantation %>% pivot_longer(tmin), tmax_comb_plantation %>% pivot_longer(tmax))

summertemps <- all_temps %>% filter(month %in% c(6,7,8)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_sm =mean(value))
falltemps <- all_temps %>% filter(month %in% c(9,10,11)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_fa =mean(value))
wintertemps <- all_temps %>% filter(month %in% c(12,1,2)) %>% 
  mutate(year = ifelse(month=="12",year+1,year)) %>% 
  filter(!year %in% c(1970,2017)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_wt =mean(value))
springtemps <- all_temps %>% filter(month %in% c(3,4,5)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_sp =mean(value))

plantation_seasonal_temps <- left_join(summertemps,falltemps) %>% 
  left_join(wintertemps) %>% 
  left_join(springtemps)

plantation_seasonal_temps_wide<- plantation_seasonal_temps %>% 
  pivot_wider(values_from = c(value_sm,value_fa,value_wt,value_sp), names_from = name)

##vpdmax

vpdmax_summed <- as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(!is.na(vpdmax)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax = mean(vpdmax))

ggplot(vpdmax_summed %>% filter(CN=="Plantation"), aes(x=year, y=vpdmax)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(vpdmax_summed %>% filter(CN=="Plantation") %>% pull(vpdmax)), col="red")

vpdmax_seasonal <- as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(6,7,8)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_sm = mean(vpdmax)) %>% 
  left_join(as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(9,10,11)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_fa = mean(vpdmax))) %>% 
  left_join(as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(12,1,2)) %>% 
  mutate(year = ifelse(month == "12", year+1, year)) %>% 
  filter(!year %in% c(1970,2017)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_wt = mean(vpdmax))) %>% 
  left_join(as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(3,4,5)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_sp = mean(vpdmax)))


```
##FDSI calculation

```{r}
all_climate <- left_join(ppt_comb_plantation,tmax_comb_plantation) %>% 
  left_join(tmin_comb_plantation) %>% 
  left_join(tmean_comb_plantation) %>% 
  left_join(vpdmax_comb_plantation) %>% 
  left_join(vpdmin_comb_plantation) %>% 
  mutate(vpdmean=(vpdmin+vpdmax)/2)

nrow(all_climate)
nrow(tmin_comb_plantation)

all_climate_long <- all_climate %>% 
 dplyr::select(-X) %>% 
  pivot_longer(c("ppt","tmax","tmin","tmean","vpdmax","vpdmin","vpdmean"), names_to="climvar", values_to = "value") %>% 
  mutate(monthvar = paste(climvar,month,sep=""))

climate_minus1<- all_climate_long %>% 
  mutate(year=year+1) %>% 
  mutate(monthvar = paste("yr1",climvar,month,sep=""))

climate_minus2<- all_climate_long %>% 
  mutate(year=year+2) %>% 
  mutate(monthvar = paste("yr2",climvar,month,sep=""))

climate_allyears <- rbind(all_climate_long, climate_minus1, climate_minus2)


### FDSI CALC

### CALCULATIONS TAKEN FROM WILLIAMS ET AL., 2013 
# DOI: 10.1038/NCLIMATE1693
#https://www.nature.com/articles/nclimate1693
FDSI_C <- climate_allyears %>%
 dplyr::select(-c("date","month","climvar")) %>% 
  pivot_wider(id_cols=c("CN","year"), names_from = monthvar, values_from = value)

head(FDSI_C)

FDSI_raw<- FDSI_C %>% 
  group_by(CN, year) %>% 
  summarise(FDSIvpd=(((vpdmean5+vpdmean6+vpdmean7)/3)+(yr1vpdmean8+yr1vpdmean9+yr1vpdmean10)/3)/2, FDSIppt=log(yr1ppt11+yr1ppt12+ppt1+ppt2+ppt3))

meanVPD <- mean(FDSI_raw$FDSIvpd, na.rm=T)
meanppt <- mean(FDSI_raw$FDSIppt, na.rm=T)
SDVPD <- sd(FDSI_raw$FDSIvpd, na.rm=T)
SDppt <- sd(FDSI_raw$FDSIppt, na.rm=T)
FDSI_raw$zscoreppt <- ((FDSI_raw$FDSIppt-meanppt)/SDppt)
FDSI_raw$zscoreVPD <- ((FDSI_raw$FDSIvpd-meanVPD)/SDVPD)

FDSI_raw$FDSI <- (0.44*(FDSI_raw$zscoreppt)-0.56*(FDSI_raw$zscoreVPD))

ggplot(FDSI_raw, aes(x=year, y=FDSI))+
  geom_line()+
  geom_point()
#I think we need to consider the fact that FDSI was really high right before the drought of the early 2000's so that's why trees may not be showing equivalent growth rates after the drought (cause it was still relatively hot and dry)
```


##CWD calculation

```{r}
source("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/grad school/cwd_function_v3.r")

#get dem
dem_plantation <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/USGS_13_n40w107_20220216.tif")

slpasp <- terrain(dem_plantation, v = c("slope","aspect"))

slpasp_plantation <- terra::extract(slpasp, adjusted_provs %>% filter(Provenance=="Plantation"), method="simple")

plantation_cwd_data <- all_climate %>% left_join(as.data.frame(adjusted_provs) %>% bind_cols(crds(adjusted_provs)) %>% filter(Provenance=="Plantation"), by=c("CN"="Provenance")) %>% 
  mutate(soilawc=116.5, foldedaspect = abs(180-abs(slpasp_plantation$aspect - 225)), slope=slpasp_plantation$slope)

plantation_cwd <- cwd_function(site="plantation",slope=plantation_cwd_data$slope, latitude=plantation_cwd_data$y, foldedaspect = plantation_cwd_data$foldedaspect, ppt = plantation_cwd_data$ppt, tmean = plantation_cwd_data$tmean, month = plantation_cwd_data$month, soilawc = plantation_cwd_data$soilawc, year = plantation_cwd_data$year, type="annual")

head(plantation_cwd)

cwd_year0 <- plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month<9) %>% 
  group_by(site, year) %>% 
  summarise(cwd_1_9 = sum(cwd))

cwd_yearminus1 <-  plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month>8) %>%
  mutate(wateryear=year+1) %>% 
  group_by(site, wateryear) %>% 
  summarise(cwd_prev = sum(cwd))

wateryear_cwd<- cwd_year0 %>% 
  left_join(cwd_yearminus1, by=c("year" = "wateryear","site")) %>% 
  rowwise() %>% 
  mutate(cwd_wy = sum(cwd_1_9, cwd_prev))

sp_cwd<- plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(3,4,5)) %>%
  group_by(site, year) %>% 
  summarise(cwd_sp = sum(cwd))

fa_cwd<- plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(9,10,11)) %>%
  group_by(site, year) %>% 
  mutate(wateryear = year+1) %>% 
  summarise(cwd_fa = sum(cwd))

##water year drought
ggplot(wateryear_cwd, aes(x=year, y=cwd_wy))+
  geom_point()+
  geom_line()+
  geom_point(data= sp_cwd, aes(x=year, y=cwd_sp),col="green4")+
  geom_line(data= sp_cwd, aes(x=year, y=cwd_sp),col="green4")+
  geom_point(data= fa_cwd, aes(x=year, y=cwd_fa),col="orange")+
  geom_line(data= fa_cwd, aes(x=year, y=cwd_fa),col="orange")  ##1970s and 80s droughts were influenced more by fall lack of moisture than 2002 drought. 


wateryear_cwd %>% 
  filter(cwd_wy>quantile(wateryear_cwd$cwd_wy[-1], c(0.75))+ 1.5*IQR(wateryear_cwd$cwd_wy[-1]))

##spring drought
ggplot( plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(3,4,5)) %>%
  group_by(site, year) %>% 
  summarise(cwd_sp = sum(cwd)), aes(x=year, y=cwd_sp))+
  geom_point()+
  geom_line()

##fall drought
ggplot( plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(9,10,11)) %>%
  group_by(site, year) %>% 
  summarise(cwd_fa = sum(cwd)), aes(x=year, y=cwd_fa))+
  geom_point()+
  geom_line()

#summer drought
ggplot(plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% filter(month%in%c(6,7,8)), aes(x=date, y=cwd))+
  geom_point(aes(col=factor(year)))+
  geom_line()

#number of times each month throughout the time series had CWD>0. July and August are most common times when CWD > 0, and it averages ~9mm
plantation_cwd %>% 
  filter(cwd>0) %>% 
  group_by(month) %>% 
  summarise(n=n(), mean=mean(cwd))

##summarise monthly climate on an annual basis
plantation_cwd_annual <- plantation_cwd %>% 
  group_by(site,year, soilawc) %>% 
  summarise(ppt_sum = sum(ppt), tmean_ave=mean(tmean), aet_sum=sum(aet), cwd_sum=sum(cwd))

plantation_cwd_annual_long<- plantation_cwd_annual %>% 
  left_join(FDSI_raw %>% dplyr::select(year,FDSI), by="year") %>% 
  dplyr::select(-CN) %>% 
  pivot_longer(ppt_sum:FDSI)

ggplot(plantation_cwd_annual_long %>% filter(name%in%c("cwd_sum","FDSI")), aes(x=year, y=value, col=name))+
  geom_point()+
  geom_line()+
  facet_wrap(~name, scales = "free")
  
```

##SPEI

```{r}
##calculate SPEI - Standardized Precipitation Evapotranspiration Index
plantation_climatebalance <- plantation_cwd %>% 
  mutate(ppt_pet = ppt - petm)

plantation_spei <- spei(plantation_climatebalance %>% pull(ppt_pet), scale=1)
plantation_spei$fitted
summary(plantation_spei)

plantation_spei_sum <- data.frame(year=plantation_climatebalance$year, month=plantation_climatebalance$month, spei = plantation_spei$fitted, date = as.Date(paste(plantation_climatebalance$month,"01",plantation_climatebalance$year, sep="/"), "%m/%d/%Y"))

ggplot(plantation_spei_sum %>% filter(year > 1987 & year <2012), aes(x=date, y=spei, fill=spei>0))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

plantation_spei_annual<- plantation_spei_sum %>% 
  group_by(year) %>% 
  summarise(spei_mean = mean(spei), spei_sum=sum(spei))

ggplot(plantation_spei_annual %>% filter(year > 1987 & year <2012), aes(x=year, y=spei_sum, fill=spei_sum>0))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))
```

##All climate vars

```{r}
#combine all climate vars

plantation_clim <- ppt_seasonal_plantation %>% 
  left_join(plantation_seasonal_temps_wide) %>% 
  left_join(vpdmax_seasonal) %>% 
  left_join(FDSI_raw) %>% 
  left_join(plantation_cwd_annual) %>% 
  left_join(wateryear_cwd) %>% 
  left_join(plantation_spei_annual)

colnames(plantation_clim)

plantation_clim_long <- plantation_clim %>% 
dplyr::select(c(CN:vpdmax_sp, FDSI, aet_sum, cwd_sum, cwd_wy, spei_sum)) %>% 
  pivot_longer(ppt_sm:spei_sum)
```

##Climate extremes

```{r}
plantation_clim_long_qs<- plantation_clim_long %>% 
  left_join(plantation_clim_long %>% 
  filter(!is.na(value)) %>% 
  group_by(name) %>% 
  summarise(q2.5 = quantile(value, 0.025), q97.5 = quantile(value, 0.975), out.hi = quantile(value, c(0.75))  + IQR(value)*1.5, out.low = quantile(value, c(0.75)) - IQR(value)*1.5))

##look at years where each climate variable exceeded the 97.5th (or 2.5th) percentile - these are years of potentially extreme climate 
ggplot(plantation_clim_long_qs, aes(x=year, y=value, col=name))+
  geom_point()+
  geom_line()+
  facet_wrap(~name, scales="free")+
  geom_line(data=plantation_clim_long_qs, aes(x=year, y=out.low), col="black")+
  geom_line(data=plantation_clim_long_qs, aes(x=year, y=out.hi), col="black")

```


##K Means

```{r}
##group provenances and plantation site into "climate groups"

#first look at correlations in climate variables
env_vars<- prov_clim_adjusted_bi %>% 
  dplyr::select(c(MAT:pas,smrpb))

prov_clim_adjusted_bi %>% 
  filter(!Provenance=="Gila NF") %>% 
  dplyr::select(c(MAT:pas,smrpb,y)) %>% 
  cor()

env_vars %>% 
  cor() %>% 
  abs()>0.9

env_vars_cut <- env_vars %>% 
  dplyr::select(-c(bFFP, eFFP, EMT, pas, dd5, dd_0))

env_vars_cut %>%
  cor() %>% 
  abs()>0.9

#look at linearity of relationships

pairs(env_vars_cut, lower.panel = NULL)

prov_clim_adjusted_bi_wide <- prov_clim_adjusted_bi %>% 
  mutate(no=ifelse(is.na(no),"Plan",no)) %>% 
  dplyr::select(c(Provenance,MAT:PPT_sm, smrpb, monsoonality))

rownames(prov_clim_adjusted_bi_wide)<- prov_clim_adjusted_bi_wide$Provenance

adjbi_prov_clim_eucdist <- vegdist(prov_clim_adjusted_bi_wide %>% dplyr::select(colnames(env_vars_cut)) %>% as.data.frame(), method="euclidean")

pam4<-pam(adjbi_prov_clim_eucdist,k=4)
pam4
pam4$clustering #view cluster membership
pam4$clusinfo
plot(pam4)

pam5<-pam(adjbi_prov_clim_eucdist,k=5)
pam5
pam5$clustering #view cluster membership
pam5$clusinfo
plot(pam5)

pam6<-pam(adjbi_prov_clim_eucdist,k=6)
pam6
pam6$clustering #view cluster membership
pam6$clusinfo
plot(pam6)

pam7<-pam(adjbi_prov_clim_eucdist,k=7)
pam7
pam7$clustering #view cluster membership - I think this is the best
pam7$clusinfo
plot(pam7)

pam8<-pam(adjbi_prov_clim_eucdist,k=8)
pam8
pam8$clustering #view cluster membership
pam8$clusinfo
plot(pam8)

pam7$silinfo$avg.width #7 groups best by this metric
pam6$silinfo$avg.width 
pam5$silinfo$avg.width
pam8$silinfo$avg.width


```


##PCA

```{r, echo = FALSE}
#run the PCA 
set.seed(83)
clim_pca <- prcomp(env_vars_cut,scale.=T) #proceed from correlation matrix, which scales variables--important because our variables have different units

##to get eigenvalues, we do the square of the stdev
eigenvals <- (clim_pca$sdev)^2
eigenvals
sum(eigenvals) #the sum of the eigenvalues = the number of variables (9)
eigenvals/sum(eigenvals)#this is the proportion variance explained
summary(clim_pca)
par(mfrow=c(1,1))
plot(clim_pca,type="l")
```

```{r, echo=FALSE}
as.data.frame(clim_pca$rotation[,1:2]) %>% 
  tibble::rownames_to_column() %>% 
  arrange(desc(abs(PC1)))
as.data.frame(clim_pca$rotation[,1:2]) %>% 
  tibble::rownames_to_column() %>% 
  arrange(desc(abs(PC2)))
as.data.frame(clim_pca$rotation[,1:3]) %>% 
  tibble::rownames_to_column() %>% 
  arrange(desc(abs(PC3)))
```

```{r}
#plot PCA
prov_pcapts<- clim_pca$x %>% 
  cbind(prov_clim_adjusted_bi) %>% 
  left_join(prov_names) %>% 
  left_join(data.frame(cluster=pam7$clustering) %>% mutate(Provenance=rownames(data.frame(cluster=pam7$clustering))))

autoplot(clim_pca,x=1,y=2,colour="aquamarine3",loadings.colour="red", loadings=T, loadings.label=T, loadings.label.colour="black", scale=0, loadings.label.size=6)+
  geom_point(data=prov_pcapts, aes(x=PC1, y=PC2, col=factor(cluster)), size=5)+
  geom_text_repel(data=prov_pcapts, aes(x=PC1, y=PC2, label=code))+
  theme(text=element_text(size=14, color="black"))
  
autoplot(clim_pca,x=1,y=3,colour="aquamarine3",loadings.colour="red", loadings=T, loadings.label=T, loadings.label.colour="black", scale=0, loadings.label.size=6)+
  geom_point(data=prov_pcapts, aes(x=PC1, y=PC3, col=factor(cluster)), size=5)+
  geom_text_repel(data=prov_pcapts, aes(x=PC1, y=PC3, label=code))+
  theme(text=element_text(size=14, color="black"))
  

ggplot()+
  geom_spatvector(data=westernus)+
  geom_spatvector(data=adjusted_provs %>% left_join(prov_names), color="maroon")+
  geom_spatvector_text(data=adjusted_provs %>% left_join(prov_names), aes(label=code), hjust=c(rep(c(-0.2,1),2),-.2,-.2,-.2,0,rep(c(-.2,1),5),1,1,1))

```

```{r}
plantation_pc1<- prov_pcapts %>% 
  filter(Provenance=="Plantation") %>% 
  pull(PC1)

plantation_pc2<- prov_pcapts %>% 
  filter(Provenance=="Plantation") %>% 
  pull(PC2)

pca_dist_df <- prov_pcapts %>% 
  mutate(PC1diff = abs(PC1-plantation_pc1), PC2diff = abs(PC2 - plantation_pc2)) %>% 
  mutate(dist.to.plant = sqrt(PC1diff^2 + PC2diff^2)) %>% 
  arrange(dist.to.plant) %>% 
  filter(!Provenance=="Plantation")
```


##PIEN climate niche

```{r}
pien <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ArcGIS/Projects/SpeciesRanges/pien_range.tif")

us <- geodata::gadm(country = "USA",  level = 1, resolution = 2,
             path = "C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/maps")
states=c("Arizona","Colorado","Idaho","Montana","Nevada","New Mexico","South Dakota","North Dakota","Nebraska","Utah","Wyoming","Kansas")
interiorwest <- us[match(toupper(states),toupper(us$NAME_1)),]


pien2 <- classify(pien, cbind(-Inf, 0, NA), right=TRUE)
plot(pien2)

pien_trim<- trim(pien2)
plot(pien_trim)

pien_IW<- crop(pien_trim %>% project(crs(interiorwest)), interiorwest)
plot(pien_IW)

pien_uniform <- classify(pien_IW, cbind(-Inf,Inf,1))
plot(pien_uniform)

pien_poly <- as.polygons(pien_uniform)
plot(pien_poly)

# engelmann_clim <- terra::extract(clim_raster_stack, pien_poly %>% project(crs(clim_raster_stack)), method="simple", weights=TRUE)
# 
# ##extract PRISM data for summer/spring precip ratio
# ppt_data_pien<-vector()
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/PRISM_ppt_30yr_normal_800mM4_all_bil/PRISM_ppt_30yr_normal_800mM4_',months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast,pien_poly %>% project(crs(clim_raster_stack)), method="simple", weights = TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   ID<- seq(1:nrow(ext.poly))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(ID,ppt,month)
#   ppt_data_pien<-rbind(ppt_data_pien,ppt_CN)}
# 
# pien_ppt_sum<- ppt_data_pien %>%
#   as.data.frame() %>%
#   unique() %>%
#   mutate(ppt=as.numeric(ppt), ID = as.numeric(ID)) %>%
#   pivot_wider(id_cols=ID, names_from=month, values_from = ppt) %>%
#   rowwise() %>%
#   mutate(JA_ppt = sum(`07`,`08`, na.rm=T), smrpb = sum(`07`,`08`,`09`,na.rm=T)/sum(`04`,`05`,`06`, na.rm=T))
# 
# saveRDS(pien_ppt_sum, "pien_ppt_sum.RDS")
# saveRDS(engelmann_clim, "engelmann_clim.RDS")

pien_ppt_sum <- readRDS("pien_ppt_sum.RDS")

#clim_pien <- left_join(engelmann_clim, pien_ppt_sum) ##not sure how to do this with polygons and weights

engelmann_clim <- readRDS("engelmann_clim.RDS")

ggplot(engelmann_clim, aes(x=MAT, y=map))+
  geom_hex(alpha=0.7)+
  scale_fill_gradientn(colors=c("aquamarine","gold","white"))+
  geom_point(data=prov_pcapts, aes(x=MAT, y=map, col=factor(cluster)), size=4)+
  ggrepel::geom_text_repel(data=prov_pcapts, aes(label=code))+
  theme_bw()+
  theme(text = element_text(size=16, color="black"))
```

#Response variables

##DBH

```{r}
##DBH data is in centimeters
dbh <- read.csv("C:/Users/KatherineNigro/Box/Engelmann Spruce Provenance/Analysis/RWI_data/DBH_data.csv")

name_conversion<- data.frame(oldname = dbh %>% arrange(Provenance) %>% pull(Provenance) %>% unique(),
           newname = prov_names %>% filter(!Provenance=="Plantation") %>%  arrange(Provenance) %>% pull(Provenance) %>% unique())

dbh_long<- dbh %>% 
  left_join(name_conversion, by=c("Provenance" = "oldname")) %>% 
  dplyr::select(-Provenance) %>% 
  rename(Provenance = newname) %>% 
  filter(!is.na(DBH91)) %>% 
  pivot_longer(DBH91:DBH14, names_to = 'year', values_to = 'DBH')

provs_arranged_lat<- prov_pcapts %>% 
  arrange(y) %>% 
  pull(Provenance)
provs_arranged_lat

dbh_clim_data <- dbh_long %>% 
  left_join(prov_pcapts) %>% 
  filter(!is.na(DBH))


#arranging provenances by different variables to visually identify patterns in DBH
ggplot(dbh_long, aes(x=factor(Provenance, levels=provs_arranged_lat), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

ggplot(dbh_clim_data, aes(x=factor(nffd), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

ggplot(dbh_clim_data, aes(x=factor(cmd), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

```

###models

```{r}
dbh_numeric <- dbh_clim_data %>% 
  mutate(num.yr = as.numeric(ifelse(year=="DBH91", 1,
                         ifelse(year=="DBH96", 6,
                                ifelse(year=="DBH06", 16,
                                       ifelse(year=="DBH14", 24, year))))))

dbh_aov <- lm(DBH ~ year*Provenance, data = dbh_numeric)
par(mfrow=c(2,2))
plot(dbh_aov)
anova(dbh_aov) #no significant interaction
dbh_aov_noint <- lm(DBH ~ year + Provenance, data = dbh_numeric)
Anova(dbh_aov_noint, type="2") #both year and provenance are significant but do not interact (relatively similar order of provenance DBH in each year measured)

prov_dbh_order<- dbh_numeric %>% 
  filter(year=="DBH14") %>% 
  group_by(Provenance) %>% 
  summarise(med_DBH = median(DBH, na.rm=T)) %>% 
  arrange(med_DBH)

dbh_early<- ggplot(dbh_numeric %>% filter(!year=="DBH14"), aes(x=factor(year, levels=c("DBH91","DBH96","DBH06"), labels=c(1991,1996,2006)), y=DBH, fill=factor(Provenance, levels=prov_dbh_order$Provenance)))+
  geom_boxplot()+
  scale_x_discrete(name="Year")+
  scale_fill_discrete(name="Provenance")
  
dbh_2014<- ggplot(dbh_numeric %>% filter(year=="DBH14"), aes(x=factor(year, levels=c("DBH14"), labels=c(2014)), y=DBH, fill=factor(Provenance, levels=prov_dbh_order$Provenance)))+
  geom_boxplot()+
  scale_x_discrete(name="Year")+
  scale_fill_discrete(name="Provenance")

ggarrange(dbh_early,dbh_2014, nrow=2, common.legend = TRUE)

###model each year separately
dbh_aov91 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH91"))
plot(dbh_aov91)
summary(dbh_aov91)
TukeyHSD(dbh_aov91)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)
 
dbh_aov96 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH96"))
plot(dbh_aov96)
summary(dbh_aov96)
TukeyHSD(dbh_aov96)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)
  
dbh_aov06 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH06"))
plot(dbh_aov06)
summary(dbh_aov06)
TukeyHSD(dbh_aov06)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)
  
dbh_aov14 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH14"))
plot(dbh_aov14)
summary(dbh_aov14)
TukeyHSD(dbh_aov14)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)

##does DBH vary with climate vars?

#just get most recent DBH measurement 
dbh_num14 <- dbh_numeric %>% filter(year=="DBH14")

#cmd
mod_dbh_cmd <- lmer(DBH ~ cmd + (1|Provenance), data=dbh_num14)
par(mfrow=c(1,1))
plot(mod_dbh_cmd)
qqmath(mod_dbh_cmd)
summary(mod_dbh_cmd) 
summary(lmer(DBH ~ cmd + (1|Provenance), data=dbh_num14 %>% filter(!Provenance=="Gila NF")))
##when Gila is taken out, CMD is not significant

ggplot(dbh_num14%>% filter(!Provenance=="Gila NF"), aes(x=cmd, y=DBH))+
  geom_point()+
  geom_smooth(method="lm")

#cluster
mod_dbh_cluster <- aov(DBH ~ cluster, data=dbh_num14)
par(mfrow=c(2,2))
plot(mod_dbh_cluster)
par(mfrow=c(1,1))
summary(mod_dbh_cluster) ##no significant difference between identified "clusters"

ggplot(dbh_num14, aes(x=factor(cluster), y=DBH))+
  geom_boxplot() 

#PC1
mod_dbh_pc1 <- lmer(DBH ~ PC1 + (1|Provenance), data=dbh_num14 %>% filter(!Provenance=="Gila NF"))
plot(mod_dbh_pc1)
qqmath(mod_dbh_pc1)
summary(mod_dbh_pc1) ##when Gila is taken out, PC1 is not significant

ggplot(dbh_num14 %>% filter(!Provenance=="Gila NF"), aes(x=PC1, y=DBH))+
  geom_point()+
  geom_smooth(method="lm")

#PC2
mod_dbh_pc2 <- lmer(DBH ~ PC2 + (1|Provenance), data=dbh_num14)
plot(mod_dbh_pc2)
qqmath(mod_dbh_pc2)
summary(mod_dbh_pc2) 

ggplot(dbh_num14 , aes(x=PC2, y=DBH))+
  geom_point()+
  geom_smooth(method="lm")


ggplot(dbh_numeric %>% 
  filter(year=="DBH14"), aes(x=y, y=DBH))+
  geom_point()+
  geom_smooth(method="lm")

#Latitude
mod_dbh_lat <- lmer(DBH ~ y+ I(y^2) + (1|Provenance), data=dbh_num14)
plot(mod_dbh_lat)
qqmath(mod_dbh_lat)
summary(mod_dbh_lat) #there's a marginally significant quadratic effect of latitude

  #take out Gila
dbh_num14_nogila <- dbh_num14 %>% filter(!Provenance=="Gila NF")

mod_dbh_lat_nogila <- lmer(DBH ~ y+ I(y^2) + (1|Provenance), data=dbh_num14_nogila)
plot(mod_dbh_lat_nogila)
qqmath(mod_dbh_lat_nogila)
summary(mod_dbh_lat_nogila) #when Gila is removed, latitude is highly significant

newdata_lat <- data.frame(
    y = seq(min(dbh_num14_nogila$y), 
                      max(dbh_num14_nogila$y), 
                      length.out = 100
                      )
    )

##take random effect out to make predictions
mod_dbh_lat_nogila_lm <- lm(DBH ~ y+ I(y^2), data=dbh_num14_nogila)

predicted_scores <- predict(
  mod_dbh_lat_nogila_lm, 
  newdata = newdata_lat, interval='confidence') %>% as.data.frame()

newdata_lat_pred <- bind_cols(newdata_lat, predicted_scores)

ggplot()+
  geom_point(data=dbh_num14_nogila, aes(x=y, y=DBH))+
  geom_ribbon(data=newdata_lat_pred, aes(x=y,ymin=lwr,ymax=upr), alpha=0.4, fill="red")+
  geom_line(data=newdata_lat_pred, aes(x=y, y=fit), col="red")+
  geom_vline(xintercept = prov_clim_adjusted_bi %>% filter(Provenance=="Plantation") %>% pull(y))+
  xlab("Latitude")

#Longitude
mod_dbh_lon <- lmer(DBH ~ x+ I(x^2)+(1|Provenance), data=dbh_num14)
plot(mod_dbh_lon)
qqmath(mod_dbh_lon)
summary(mod_dbh_lon) #no significant effects of longitude

  #take out Gila
mod_dbh_lon_nogila <- lmer(DBH ~ x+ I(x^2) + (1|Provenance), data=dbh_num14_nogila)
summary(mod_dbh_lon_nogila) #still not significant


##distance in PCA space from plantation
dbh_num14_pcadist<- dbh_num14 %>% 
  left_join(pca_dist_df %>% dplyr::select(code, dist.to.plant))

mod_dbh_pcadist <- lmer(DBH ~ dist.to.plant + (1|Provenance), data=dbh_num14_pcadist)
plot(mod_dbh_pcadist)
qqmath(mod_dbh_pcadist)
summary(mod_dbh_pcadist) #no significant effects of distance to plantation in PCA space

#TD
mod_dbh_td <- lmer(DBH ~ TD + I(TD^2) + (1|Provenance), data=dbh_num14)
plot(mod_dbh_td)
qqmath(mod_dbh_td)
summary(mod_dbh_td) 
summary(lmer(DBH ~ TD + I(TD^2) + (1|Provenance), data=dbh_num14 %>% filter(!Provenance=="Gila NF")))

#PAS
mod_dbh_pas <- lmer(DBH ~ pas + I(pas^2) + (1|Provenance), data=dbh_num14)
plot(mod_dbh_pas)
qqmath(mod_dbh_pas)
summary(mod_dbh_pas) 
summary(lmer(DBH ~ pas + I(pas^2) + (1|Provenance), data=dbh_num14 %>% filter(!Provenance=="Gila NF")))


dbh_clim_data <- dbh_num14 %>% 
  dplyr::select(c(Series, Provenance, DBH, colnames(env_vars_cut)))

env_vars_cut %>% 
  cor()

dbh_clim_nogila<- dbh_clim_data %>% filter(!Provenance=="Gila NF")

mod_dbh_allclim <- lmer(DBH ~ MAT + I(MAT^2) + map + I(map^2) + TD + I(TD^2) + SHM + I(SHM^2) + nffd  + I(nffd^2) + smrpb + I(smrpb^2) + (1|Provenance), data=dbh_clim_nogila)
plot(mod_dbh_allclim)
qqmath(mod_dbh_allclim)
vif(mod_dbh_allclim)
summary(mod_dbh_allclim)

options(na.action = "na.fail")
mod_dbh_allclim_dredge <- dredge(mod_dbh_allclim)
mod_dbh_allclim_dredge

#smrpb
mod_dbh_smrpb <- lmer(DBH ~ smrpb + I(smrpb^2) + (1|Provenance), data=dbh_num14)
plot(mod_dbh_smrpb)
qqmath(mod_dbh_smrpb)
summary(mod_dbh_smrpb) 
summary(lmer(DBH ~ smrpb + I(smrpb^2) + (1|Provenance), data=dbh_num14 %>% filter(!Provenance=="Gila NF")))

```

###dbh diff
```{r}
#difference between first and last DBH

dbh_diffs<- dbh %>% 
  left_join(name_conversion, by=c("Provenance" = "oldname")) %>% 
  dplyr::select(-Provenance) %>% 
  rename(Provenance = newname) %>% 
  mutate(diff_total = DBH14 - DBH91, 
         diff3 = DBH14 - DBH06,
         diff2 = DBH06 - DBH96,
         diff1 = DBH96 - DBH91)

dbh_diffs_long <- dbh_diffs %>% 
  pivot_longer(c(DBH91:DBH14,diff_total:diff1)) %>% 
  left_join(prov_pcapts, by="Provenance") %>% 
  filter(!is.na(value))
  
ggplot(dbh_diffs_long %>% filter(name %in% c("diff_total","diff1","diff2","diff3")), aes(x=factor(Provenance, levels=provs_arranged_lat), y=value, fill=Provenance))+
  geom_boxplot()+
  facet_wrap(~name, scales="free")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

##models
diff_total_df <- dbh_diffs_long %>% 
  filter(name == "diff_total")

dbhdiff_mod <- lmer(value ~ PC1 * PC2 + (1|Provenance), data=diff_total_df)
plot(dbhdiff_mod)
lattice::qqmath(dbhdiff_mod)
summary(dbhdiff_mod)

ggplot(dbh_diffs_long, aes(x= PC1, y=value))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~name, scales="free")

```

##Height Growth

```{r}
moniger_data <- read.csv("past_moniger_data.csv")
moniger_data_ids <- read.csv("past_moniger_data_ids.csv")

head(moniger_data_ids)
head(moniger_data)

moniger_data_comb <- moniger_data %>% 
  left_join(moniger_data_ids, by=c("LOC" = "ID.Code")) %>% 
  mutate(Provenance = ifelse(Location == "Larimer County 1","Larimer 1",
                                    ifelse(Location == "Larimer County 2","Larimer 2",Location))) %>% 
  left_join(prov_pcapts)

colnames(moniger_data_comb)

ggplot(moniger_data_comb, aes(x=factor(cmd), y=HT14, fill=Provenance))+
  geom_boxplot()+
  theme(legend.position = 'right', axis.text.x = element_text(angle=45, hjust=1))

ht_data <- moniger_data_comb %>% 
  dplyr::select(c(LOC,BLK,REP,Provenance,HT74:HT14,Seedling.Ht..from.Nursery)) %>% 
  pivot_longer(HT74:HT14) %>% 
  mutate(nursery_ht_m = Seedling.Ht..from.Nursery/39.37) %>% 
  mutate(growth.m = (value-nursery_ht_m), rel.growth = (value-nursery_ht_m)/nursery_ht_m) %>% 
  filter(!is.na(value))

ht_data_clim <- ht_data %>% 
  left_join(prov_pcapts)

ht.order <- ht_data %>% 
  filter(name=="HT14") %>% 
  group_by(Provenance) %>% 
  summarise(med_rel_growth=median(rel.growth,na.rm=T), med_growth=median(growth.m, na.rm=T), meanht = mean(value, na.rm=T)) %>% 
  arrange(meanht)

#relative growth
ggplot(ht_data %>% filter(!name=="HT74"), aes(x=factor(Provenance, levels=ht.order$Provenance), y=rel.growth, fill=factor(Provenance, levels=ht.order$Provenance)))+
  geom_boxplot()+
  facet_wrap(~factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), scales="free")+
  scale_fill_discrete(name="Provenance")+
  scale_x_discrete(name="Provenance")+
  theme(axis.text.x = element_blank())

#growth
ggplot(ht_data %>% filter(!name=="HT74"), aes(x=factor(Provenance, levels=ht.order$Provenance), y=growth.m, fill=factor(Provenance, levels=ht.order$Provenance)))+
  geom_boxplot()+
  facet_wrap(~factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), scales="free")+
  scale_fill_discrete(name="Provenance")+
  scale_x_discrete(name="Provenance")+
  theme(axis.text.x = element_blank())


ht_data_aves <- ht_data %>% filter(!name=="HT74") %>% 
  group_by(name, Provenance,nursery_ht_m ) %>% 
  summarise(meangrowth = mean(growth.m), seRG = sd(growth.m)/sqrt(n()), meantotht = mean(value), seTH = sd(value)/sqrt(n()))

ggplot(ht_data %>% filter(!name=="HT74"), aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), y=growth.m, fill=factor(Provenance, levels=ht.order$Provenance)))+
  geom_boxplot()+
  geom_line(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), y=meangrowth, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)))+
  scale_fill_discrete(name="Provenance")+
  scale_x_discrete(name="Provenance")

ggplot()+
  geom_line(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), y=meangrowth, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)))+
  geom_errorbar(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), ymin=meangrowth-seRG, ymax=meangrowth+seRG, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)),width=0.2)+
  geom_point(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), y=meangrowth, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)))+
  scale_color_discrete(name="Provenance")+
  scale_x_discrete(name="Year")+
  ylab("Average relative growth ratio")

##initial height effect on height growth -- looks like there isn't really one
ggplot(data=ht_data_aves, aes(x=nursery_ht_m, y=meangrowth))+
  geom_point()

ggplot(data=ht_data_aves, aes(x=nursery_ht_m, y=meantotht))+
  geom_point()

nurse_ht_mod <- lm(meantotht ~ nursery_ht_m, data=ht_data_aves)
summary(nurse_ht_mod)  ##no effect of nursery height on total height in 2014. 

```

##Total Height

###models

```{r}
##effect of year * provenance

plot(lm(value ~ Provenance*name, data=ht_data))

totht_mod <- lm(log(value) ~ Provenance*name, data=ht_data)
par(mfrow=c(2,2))
plot(totht_mod)
anova(totht_mod) ##there is a significant year by provenance interaction

ggplot()+
  geom_line(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), y=meantotht, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)))+
  geom_errorbar(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), ymin=meantotht-seTH, ymax=meantotht+seTH, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)),width=0.2)+
  geom_point(data=ht_data_aves, aes(x=factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), y=meantotht, col=factor(Provenance, levels=ht.order$Provenance),group=factor(Provenance, levels=ht.order$Provenance)))+
  scale_color_discrete(name="Provenance")+
  scale_x_discrete(name="Year")+
  ylab("Total Height (m)")


#each year separately
totht_mod74 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT74"))
plot(totht_mod74)
summary(totht_mod74)
TukeyHSD(totht_mod74)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

totht_mod79 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT79"))
plot(totht_mod79)
summary(totht_mod79)
TukeyHSD(totht_mod79)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

totht_mod85 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT85"))
plot(totht_mod85)
summary(totht_mod85)
TukeyHSD(totht_mod85)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

totht_mod91 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT74"))
plot(totht_mod74)
summary(totht_mod74)
TukeyHSD(totht_mod74)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

totht_mod96 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT96"))
plot(totht_mod96)
summary(totht_mod96)
TukeyHSD(totht_mod96)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

totht_mod06 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT06"))
plot(totht_mod06)
summary(totht_mod06)
TukeyHSD(totht_mod06)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

totht_mod14 <- aov(value ~ Provenance, data= ht_data %>% filter(name=="HT14"))
plot(totht_mod14)
summary(totht_mod14)
TukeyHSD(totht_mod14)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

```


```{r}
##continuous variable effects on height

ht_data_clim14 <- ht_data_clim %>% filter(name=="HT14")

#cmd
mod_totht_cmd <- lmer(value ~ cmd + (1|Provenance), data=ht_data_clim14)
par(mfrow=c(1,1))
plot(mod_totht_cmd)
qqmath(mod_totht_cmd)
summary(mod_totht_cmd) 
summary(lmer(value ~ cmd + (1|Provenance), data=ht_data_clim14 %>% filter(!Provenance=="Gila NF")))
##when Gila is taken out, CMD is not significant -- same as DBH model

ggplot(ht_data_clim14, aes(x=cmd, y=value, col=Provenance=="Gila NF"))+
  geom_point()+
  geom_smooth(method="lm")

#PC1
mod_totht_PC1 <- lmer(value ~ PC1 + (1|Provenance), data=ht_data_clim14)
par(mfrow=c(1,1))
plot(mod_totht_PC1)
qqmath(mod_totht_PC1)
summary(mod_totht_PC1) 
summary(lmer(value ~ PC1 + (1|Provenance), data=ht_data_clim14 %>% filter(!Provenance=="Gila NF")))
##when Gila is taken out, PC1 is not significant 

ggplot(ht_data_clim14%>% filter(!Provenance=="Gila NF"), aes(x=PC1, y=value))+
  geom_point()+
  geom_smooth(method="lm")

#PC2
mod_totht_PC2 <- lmer(value ~ PC2 + (1|Provenance), data=ht_data_clim14)
par(mfrow=c(1,1))
plot(mod_totht_PC2)
qqmath(mod_totht_PC2)
summary(mod_totht_PC2) 
summary(lmer(value ~ PC2 + (1|Provenance), data=ht_data_clim14 %>% filter(!Provenance=="Gila NF")))
##neither is significant

#Latitude
mod_totht_lat <- lmer(value ~ y+ I(y^2) + (1|Provenance), data=ht_data_clim14)
plot(mod_totht_lat)
qqmath(mod_totht_lat)
summary(mod_totht_lat) ##quadratic effect not significant
mod_totht_lat_simple <- lmer(value ~ y+ (1|Provenance), data=ht_data_clim14)
plot(mod_totht_lat_simple)
qqmath(mod_totht_lat_simple)
summary(mod_totht_lat_simple)

#take out Gila
ht_data_clim14_nogila <- ht_data_clim14 %>% filter(!Provenance=="Gila NF")
summary(lmer(value ~ y+ (1|Provenance), data=ht_data_clim14_nogila)) #latitude only signficant with Gila included

summary(lmer(value ~ y+ I(y^2)+ (1|Provenance), data=ht_data_clim14_nogila)) #BUT latitude quadratic effect is significant when Gila is excluded. Height lowest in middle latitudes. 

ggplot(data=ht_data_clim14, aes(x=y, y=value, col=Provenance))+
  geom_point()+
  geom_smooth(method="lm")

#longitude
mod_totht_lon <- lmer(value ~ x + (1|Provenance), data=ht_data_clim14)
plot(mod_totht_lon)
qqmath(mod_totht_lon)
summary(mod_totht_lon) ##longitude is marginally significant
summary(lmer(value ~ x + (1|Provenance), data=ht_data_clim14_nogila)) 

ggplot(data=ht_data_clim14, aes(x=x, y=value, col=Provenance))+
  geom_point()+
  geom_smooth(method="lm")

#TD
mod_totht_TD <- lmer(value ~ TD*map + (1|Provenance), data=ht_data_clim14)
plot(mod_totht_TD)
qqmath(mod_totht_TD)
summary(mod_totht_TD) 
summary(lmer(value ~ TD + (1|Provenance), data=ht_data_clim14_nogila)) 

summary(lmer(value ~ TD*map + (1|Provenance), data=ht_data_clim14_nogila)) 

ggplot(data=ht_data_clim14_nogila, aes(x=TD, y=value, col=map>700))+
  geom_point()+
  geom_smooth(method="lm") ##seems like there could be an interaction going on here. 

#nffd
mod_totht_nffd <- lmer(value ~ nffd + (1|Provenance), data=ht_data_clim14)
plot(mod_totht_nffd)
qqmath(mod_totht_nffd)
summary(mod_totht_nffd) 
summary(lmer(value ~ nffd*SHM + (1|Provenance), data=ht_data_clim14_nogila)) 


ht_data_clim14_noXT <- ht_data_clim14 %>% 
  filter(TD > 20 & TD < 23)

mod_totht_TD_noXT <- lmer(value ~ TD + I(TD^2) + (1|Provenance), data=ht_data_clim14_noXT)
plot(mod_totht_TD_noXT)
qqmath(mod_totht_TD_noXT)
summary(mod_totht_TD_noXT) 

ggplot(data=ht_data_clim14_noXT, aes(x=TD, y=value, col=Provenance))+
  geom_point()+
  geom_smooth(method="lm")


##Look at just southern Rockies, excluding Gila
ht_SR <- ht_data_clim14_nogila %>% filter(y < 44)
  
htmod_SR <- lmer(value ~ y + (1|Provenance), data=ht_SR)
plot(htmod_SR)
qqmath(htmod_SR)
summary(htmod_SR)

ggplot(data=ht_SR, aes(x=y, y=value, col=Provenance))+
  geom_point()+
  geom_smooth(method="lm")

colnames(ht_SR)

cor(ht_SR %>% dplyr::select(c(MAT:PPT_sm,elev,x,y,smrpb,monsoonality)))

#TD
TD_htmod_SR <- lmer(value ~ TD + (1|Provenance), data=ht_SR)
plot(TD_htmod_SR)
qqmath(TD_htmod_SR)
summary(TD_htmod_SR) ##Temperature differential is the main differntiating feature between latitude in the southern Rockies (excluding Gila)

#nursery height
totht_mod_nursery <- lmer(value ~ Seedling.Ht..from.Nursery + (1|Provenance), data=ht_data_clim14_nogila)
plot(totht_mod_nursery)
qqmath(totht_mod_nursery)
summary(totht_mod_nursery) ##significant effect of nursery height on total height in 2014 when Gila is removed

ggplot(data= ht_data_clim14, aes(x=Seedling.Ht..from.Nursery, y=value, col=Provenance))+
  geom_point()

###big model
totht_mod_allvars <- lmer(value ~  MAT + I(MAT^2) + map + I(map^2) + TD + I(TD^2) + SHM + I(SHM^2) + nffd  + I(nffd^2) + smrpb + I(smrpb^2) + Seedling.Ht..from.Nursery + (1|Provenance), data=ht_data_clim14)
plot(totht_mod_allvars)
qqmath(totht_mod_allvars)
summary(totht_mod_allvars)



```



##Survival

```{r}
##survival
tree.num <- ht_data %>% 
  filter(!is.na(rel.growth)) %>% 
  group_by(name, Provenance) %>% 
  summarise(n=n()) %>% 
  mutate(year = case_when(
    name=="HT74" ~ 1974,
    name=="HT79" ~ 1979,
    name=="HT85" ~ 1985,
    name=="HT91" ~ 1991,
    name=="HT96" ~ 1996,
    name=="HT06" ~ 2006,
    name=="HT14" ~ 2014))

trees.died<- tree.num %>% 
  left_join(tree.num %>% filter(year==1974) %>% ungroup() %>% dplyr::select(Provenance, n) %>% rename(n_74=n)) %>% 
  mutate(prop = n/n_74)

ggplot(tree.num, aes(x=year, y=n, col=Provenance))+
  geom_point()+
  geom_line()

ggplot(trees.died %>% filter(name=="HT14"), aes(x=Provenance, y=prop))+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))


ggplot(ht_data %>% filter(!name=="HT74"), aes(x=factor(Provenance, levels=ht.order$Provenance), y=rel.growth, fill=factor(Provenance, levels=ht.order$Provenance)))+
  geom_boxplot()+
  geom_text(data=tree.num %>% filter(!name=="HT74"), aes(x=Provenance, y=0, label=n))+
  facet_wrap(~factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), scales="free")+
  scale_fill_discrete(name="Provenance")+
  scale_x_discrete(name="Provenance")+
  theme(axis.text.x = element_blank())


```

###models

```{r}
#provenance climate affect on survival linear models

```

##Cones

```{r}
cone_data <- moniger_data_comb %>% 
  dplyr::select(c(SORT,Provenance,Cones85:Cones06)) %>% 
  pivot_longer(Cones85:Cones06) %>% 
  mutate(year=case_when(name == "Cones85" ~ 1985,
                        name == "Cones91" ~ 1991,
                        name == "Cones96" ~ 1996,
                        name == "Cones06" ~ 2006))


cone_sum <- cone_data %>%
  filter(!is.na(value)) %>% 
  group_by(Provenance,year) %>% 
  summarise(value=sum(value), n=n()) %>% 
  mutate(prop.w.cones = value/n)

ave_hts <- moniger_data_comb %>% 
  dplyr::select(c(SORT,Provenance,HT85:HT06)) %>% 
  pivot_longer(HT85:HT06) %>% 
  mutate(year=case_when(name == "HT85" ~ 1985,
                        name == "HT91" ~ 1991,
                        name == "HT96" ~ 1996,
                        name == "HT06" ~ 2006)) %>% 
  filter(!is.na(value)) %>% 
  group_by(Provenance, year) %>% 
  summarise(ave.ht = mean(value), se.ht = sd(value)/sqrt(n())) %>% 
  left_join(cone_sum)

ave_dbh <- moniger_data_comb %>% 
  dplyr::select(c(SORT,Provenance,DBH91:DBH06)) %>% 
  pivot_longer(DBH91:DBH06) %>% 
  mutate(year=case_when(name == "DBH91" ~ 1991,
                        name == "DBH96" ~ 1996,
                        name == "DBH06" ~ 2006)) %>%
  filter(!is.na(value)) %>% 
  group_by(Provenance, year) %>% 
  summarise(ave.dbh = mean(value), se.dbh = sd(value)/sqrt(n())) %>% 
  left_join(cone_sum)

ggplot(ave_hts, aes(x=ave.ht, y=prop.w.cones, col=Provenance))+
  geom_point()+
  geom_errorbar(aes(xmin=ave.ht - se.ht, xmax=ave.ht+se.ht))

ggplot(ave_dbh, aes(x=ave.dbh, y=prop.w.cones, col=Provenance))+
  geom_point()+
  geom_errorbar(aes(xmin=ave.dbh-se.dbh, xmax=ave.dbh+se.dbh))

ggplot(moniger_data_comb, aes(x=HT85, y=Cones85))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=HT91, y=Cones91))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=HT96, y=Cones96))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=HT06, y=Cones06))+
  geom_jitter(height=0.1)

ggplot(moniger_data_comb, aes(x=DBH91, y=Cones91))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=DBH96, y=Cones96))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=DBH06, y=Cones06))+
  geom_jitter(height=0.1)

ggplot(cone_sum, aes(x=year, y=prop.w.cones, col=Provenance))+
  geom_point()+
  geom_line()
```

###models

```{r}
#provenance climate affect on cones linear models

```

##RWI

###Raw

```{r}
prov_all <- read.rwl("C:/Users/KatherineNigro/Box/Engelmann Spruce Provenance/Ring_widths_raw/prov_all.rwl")
```


```{r}
#plot raw data to look at timeseries length
plot.rwl(prov_all)

##compare timing of when trees reached 30cm tall (and thus had a growth ring measured)
dbh_age <- prov_all %>% 
  as.data.frame() %>% 
  mutate(year = rownames(prov_all)) %>% 
  pivot_longer(!year, values_to = "rw", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(dbh %>% mutate(tree=paste("X",Series,sep="")), by="tree")
  
dbh_age_summary <- dbh_age %>%
  filter(!is.na(rw)) %>% 
  group_by(Provenance,tree) %>% 
  summarise(minyr = min(year), maxyr=max(year), n=n()) %>% 
  mutate(years.calc = maxyr-minyr+1)

#compare when time series started (min year)
ggplot(dbh_age_summary, aes(x=factor(Provenance, levels=prov_pcapts %>% arrange(y) %>% pull(Provenance)), y=minyr))+
  geom_boxplot()+
  geom_point(color="maroon")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#compare length of timeseries
ggplot(dbh_age_summary, aes(x=Provenance, y=n))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

dbh_age_summary2 <- dbh_age_summary %>% 
  left_join(dbh %>% mutate(Series=paste("X",Series,sep="")), by=c("tree"="Series","Provenance")) 

ggplot(dbh_age_summary2, aes(x=minyr, y=DBH14, col=Provenance))+
  geom_point() #there isn't a strong correlation between dbh and the length of the timeseries which makes me think that rings were just lost (not that the tree didn't reach DBH height until the min year)
###

##remove NAs from ring width series
prov_all_nona<- prov_all %>% na.omit()
colnames(prov_all_nona)

##raw
ggplot(dbh_age, aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

hist(dbh_age$rw)
hist(dbh_age %>% filter(rw<0.5) %>% pull(rw))


###investigating series with really low ring width values
dbh_rwi_comp <- dbh_age %>% 
  filter(!tree=="X32A1") %>% 
  group_by(Provenance, tree) %>% 
  summarise(sum=sum(rw, na.rm = TRUE)) %>% 
  arrange(tree) %>% 
  bind_cols(dbh %>% arrange(Series) %>% 
  filter(!is.na(DBH14))) %>% 
  mutate(lowsum=ifelse(sum<16,"yes","no"))

dbh_rwi_comp %>% 
  filter(lowsum=="yes")

ggplot(dbh_rwi_comp)+
  geom_point(aes(x=sum, y=DBH14, col=lowsum))

ggplot(dbh_rwi_comp %>% mutate(sum=ifelse(sum<15,sum*10,sum)))+
  geom_point(aes(x=sum, y=DBH14, col=lowsum))+
  geom_abline(slope=1/10,intercept = 0)
###########

#find series that are likely off by an order of magnitude
off_provs<- dbh_age %>% 
  filter(Provenance %in% c("Cache NF","Coconino NF", "Cutting Permit 31", "Dixie NF", "Gunnison NF","Larimer 2", "Okanogan NF","Powers Creek","Wallowa-Whitman NF","Wenatchee NF"))

ggplot(off_provs, aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

off_trees<- dbh_rwi_comp %>% 
  filter(lowsum=="yes") %>% pull(tree) %>% c("X58A4") #this is the weird tree that's half and half

prov_good_nona <- prov_all_nona %>%dplyr::select(-all_of(substr(off_trees, 2,nchar(off_trees))))


###this cuts out sketchy trees and year = 2016
prov_good <- prov_all %>% dplyr::select(-all_of(substr(off_trees,2,nchar(off_trees)))) %>% 
  filter(!row.names(prov_all)=="2016")
```

```{r}
##some plots of the raw data averaged
dbh_age_good <- dbh_age %>% 
  filter(!tree %in% off_trees)


ave_rw_prov<- dbh_age_good %>% 
  na.omit() %>% 
  group_by(Provenance, year) %>% 
  summarise(ave_rw=mean(rw), se=sd(rw)/sqrt(n())) 

ggplot(ave_rw_prov, aes(x=year, y=ave_rw, col=Provenance))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(x=year, ymin=ave_rw-se, ymax=ave_rw+se, col=Provenance))+
  geom_vline(xintercept = 1985)+
  facet_wrap(~Provenance)

ggplot(ave_rw_prov, aes(x=year, y=ave_rw, col=Provenance))+
  geom_point()+
  geom_line()+
  #geom_errorbar(aes(x=year, ymin=ave_rw-se, ymax=ave_rw+se, col=Provenance))+
  geom_vline(xintercept = 1985)


ave_rw_all <- dbh_age_good %>%
  na.omit() %>% 
  group_by(year) %>% 
  summarise(ave_rw=mean(rw), se=sd(rw)/sqrt(n()))

ggplot(ave_rw_all, aes(x=year, y=ave_rw))+
  geom_point()+
  geom_errorbar(aes(x=year, ymin=ave_rw-se, ymax=ave_rw+se), col="red")+
  geom_line()
### it seems like the major deviation in the data is in response to the wet period right before the drought, rather than the 2002 drought. 

```

###Detrending

```{r}
##detrending with Spline method - using stiffness of 35 years
##need to figure out what age to start at based on how long the "young tree growth spurt" usually takes

###plot series to figure out where NAs are
plot(prov_good, plot.type="spag")
rwl.report(prov_good)
prov_good_stats<- summary(prov_good)
summary(prov_good_stats$ar1)

ggplot(prov_good_stats, aes(y=ar1))+
  geom_boxplot()+
  geom_point()


growth.detrended.all = matrix(nrow=nrow(prov_all)-1, ncol=length(colnames(prov_good)))
for(i in 1:length(prov_good_nona)){
obj<- detrend.series(y = prov_good  %>%  pull(colnames(prov_good)[i]), y.name="growth", method="Spline", nyrs = 35)
growth.detrended.all[,i]<- obj
}
colnames(growth.detrended.all) = colnames(prov_good)
rownames(growth.detrended.all) = rownames(prov_good)

rwi.stats(growth.detrended.all, period="max")
chron(growth.detrended.all)
plot(chron(growth.detrended.all), add.spline=TRUE, nyrs=35)


growth.detrended.df.all <- growth.detrended.all %>% 
  as.data.frame() %>% 
  mutate(year = rownames(growth.detrended.all)) %>% 
  pivot_longer(!year, values_to = "rw_spline", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(dbh %>% mutate(tree=paste("X",Series,sep="")), by="tree")

ggplot(growth.detrended.df.all, aes(x=year, y=rw_spline, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance, scales = "free")+
  theme(legend.position = "none")

##remove first 15 years of ring widths since they are missing for many trees and likely represent unusual growth patterns. 
growth.detrended.short = matrix(nrow=nrow(prov_good)-15, ncol=length(colnames(prov_good)))
for(i in 1:length(prov_good_nona)){
obj<- detrend.series(y = prov_good %>% filter(!(row.names(prov_good) < 1985))  %>%  pull(colnames(prov_good)[i]), y.name="growth", method="Spline", nyrs = 35)
growth.detrended.short[,i]<- obj
}
colnames(growth.detrended.short) = colnames(prov_good)
rownames(growth.detrended.short) = rownames(prov_good)[16:nrow(prov_good)]

rwi.stats(growth.detrended.short, period="max")
plot(chron(growth.detrended.short), add.spline=TRUE, nyrs=35)
##########

growth.detrended.df <- growth.detrended.short %>% 
  as.data.frame() %>% 
  mutate(year = rownames(growth.detrended.short)) %>% 
  pivot_longer(!year, values_to = "rw_spline", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(dbh %>% mutate(tree=paste("X",Series,sep="")), by="tree")

ggplot(growth.detrended.df, aes(x=year, y=rw_spline, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance, scales = "free")+
  theme(legend.position = "none")
```


