---
title: "PIEN data exploration"
output: html_document
date: "2023-10-30"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load required packages
library(terra)
library(ggplot2)
library(ggspatial)
library(tidyterra)
library(dplyr)
library(stringr)
#library(ClimateNAr)
library(ggfortify)
library(RColorBrewer)
library(tidyr)
library(lme4)
library(car)
library(viridis)
library(dplR)
library(ggpubr)
library(ggrepel)
library(ggcorrplot)
```

#Climate

```{r}
#read in site and provenance locations
us <- geodata::gadm(country = "USA",  level = 1, resolution = 2,
             path = "C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject")
west_states<- c("Arizona","Colorado","Idaho","Montana","Nevada","New Mexico","South Dakota","North Dakota","Nebraska","Utah","Wyoming","California","Oregon","Washington","Kansas","Oklahoma","Texas")
westernus <- us[match(toupper(west_states),toupper(us$NAME_1)),]

#this includes the plantation lat/long
provenances <- vect("C:/Users/KatherineNigro/Box/Engelmann Spruce Provenance/Maps-GIS/SourceLocsAdj.shp")
as.data.frame(provenances)

ggplot()+
  geom_spatvector(data=westernus)+
  geom_spatvector(data=provenances, color="maroon")

```


```{r}
#read in climate from climateNA

#first download climate normals from ClimateNA then read in to R
mastervarList <- c('mat', 'map','td','mcmt','msp','shm','nffd','bFFP','eFFP','mwmt','dd_0','dd5','emt','cmd','pas','PPT_sp','PPT_sm') #these are all the climate variables I want

# rasterDownload (region='NA',res='4000m',period='Normal_1961_1990',varList="PPT_sm",sDir='C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/PIENproject/ClimateNA')

normal_clim_rasters <- c()
for(i in 1:length(mastervarList)){
  normal_clim_rasters[i]<- paste("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/PIENproject/ClimateNA/NA/4000m/Normal_1961_1990/",mastervarList[i],".tif",sep="")
}

clim_raster_stack <- rast(normal_clim_rasters)

prov_clim <- terra::extract(clim_raster_stack, provenances, method='simple') %>% cbind(as.data.frame(provenances)) %>% cbind(crds(provenances)) %>% 
  mutate(smrpb = PPT_sm/PPT_sp, monsoonality = msp/map)
prov_clim

prov_clim_bilinear <- terra::extract(clim_raster_stack, provenances, method='bilinear') %>% cbind(as.data.frame(provenances)) %>% cbind(crds(provenances)) %>% 
  mutate(smrpb = PPT_sm/PPT_sp, monsoonality = msp/map)

ggplot(prov_clim, aes(x=monsoonality, y=smrpb))+
  geom_point()

#nffd x map
ggplot()+
  geom_point(data=prov_clim, size=3, aes(x=nffd, y=map), col="aquamarine3")+
  geom_text(data=prov_clim, aes(x=nffd, y=map, label=ident), vjust=0.5, hjust=-.1)+
  theme_bw()+
  theme(legend.position = 'none')

ggplot()+
  geom_point(data=prov_clim, size=3, aes(x=nffd, y=TD), col="aquamarine3")+
  geom_text(data=prov_clim, aes(x=nffd, y=TD, label=ident), vjust=1)+
  theme_bw()+
  theme(legend.position = 'none')
```


```{r}
#make key for provenance names
prov_names<- data.frame(ident = prov_clim$ident, number = substr(prov_clim$ident,1,4), Provenance = c("Powers Creek","Kidd Creek","Inlet Creek","Cutting Permit 31","Roosevelt NF","Pike NF","San Juan NF","Gunnison NF","Santa Fe NF","Coconino NF","Payette NF","Cache NF","Dixie NF","Okanogan NF","Wenatchee NF","Wallowa-Whitman NF","Larimer 1","Larimer 2","GM-U NF","Gila NF","Plantation"), code = c("PC","KC","IC","CP31","Roo","Pike","SJ","Gunni","SF","Coco","Pay","Cache","Dixie","Oka","Wen","Wall-Whit","Lar1", "Lar2","GMUG","Gila","Plantation"))
```

```{r}
#all clim vars
colnames(prov_clim)

prov_clim_long<- prov_clim %>% 
  dplyr::select(c(ident,MAT:PPT_sm, Latitude, Longitude, smrpb, monsoonality)) %>% 
  pivot_longer(MAT:monsoonality) %>% 
  mutate(type="simple", number=substr(ident,0,4)) %>% 
  left_join(prov_names)

prov_clim_bilinear_long<- prov_clim_bilinear %>% 
  dplyr::select(c(ident,MAT:PPT_sm, Latitude, Longitude, smrpb, monsoonality)) %>% 
  pivot_longer(MAT:monsoonality) %>% 
  mutate(type="bilinear", number=substr(ident,0,4)) %>% 
  left_join(prov_names)

##try new coordinates
adjusted_coords<- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/PIEN_corrected_coords.csv")

adjusted_provs<- vect(adjusted_coords, geom=c("long_corrected","lat_corrected"))

prov_clim_adjusted_bi <- terra::extract(clim_raster_stack, adjusted_provs, method='bilinear') %>% cbind(as.data.frame(adjusted_provs)) %>% cbind(crds(adjusted_provs)) %>% 
  mutate(smrpb = PPT_sm/PPT_sp, monsoonality = msp/map)

prov_clim_adjusted_bi_long<- prov_clim_adjusted_bi %>% 
  mutate(no=ifelse(is.na(no),"Plan",no)) %>% 
  dplyr::select(c(Provenance,MAT:PPT_sm, smrpb, monsoonality)) %>% 
  pivot_longer(MAT:monsoonality) %>% 
  mutate(type="adj bilinear") 

prov_clim_compare <- bind_rows(prov_clim_bilinear_long, prov_clim_adjusted_bi_long) %>% 
  mutate(Provenance = ifelse(Provenance == "Grand Mesa-Uncompahgre NF", "GM-U NF", Provenance))

ggplot(prov_clim_compare %>% filter(!name%in%c("Latitude","Longitude")), aes(x=name, y=value, col=type))+
  geom_point()+
  facet_wrap(~Provenance, scales="free")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


```

```{r}
##monthly variables
years_old<- as.character(seq(1970,1980,1))
years_new <- as.character(seq(1981,2016,1))
months<- c("01","02","03","04","05","06","07","08","09","10","11","12")

# set location of climate data
climdir <- "C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/PRISM"


# #pull climate for 1970 - 2016 from PRISM
# ppt_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_ppt_stable_4kmM3_198101_202305_bil/PRISM_ppt_stable_4kmM2_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(CN,ppt,year,month)
#   ppt_data_old<-rbind(ppt_data_old,ppt_CN)}
# }
# 
# ppt_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_ppt_stable_4kmM3_198101_202305_bil/PRISM_ppt_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(CN,ppt,year,month)
#   ppt_data_new<-rbind(ppt_data_new,ppt_CN)}
# }
# 
# ppt_comb_plantation <- bind_rows(as.data.frame(ppt_data_old), as.data.frame(ppt_data_new)) %>% filter(CN == "Plantation") %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), ppt=as.numeric(ppt))
# 
# ppt_comb_all <- bind_rows(as.data.frame(ppt_data_old), as.data.frame(ppt_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), ppt=as.numeric(ppt))
# 
# write.csv(ppt_comb_all, "ppt_comb_all.csv")
# 
# 
# ##tmin
# tmin_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmin_stable_4kmM3_198101_202305_bil/PRISM_tmin_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   tmin<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmin_CN<-cbind(CN,tmin,year,month)
#   tmin_data_old<-rbind(tmin_data_old,tmin_CN)}
# }
# 
# tmin_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmin_stable_4kmM3_198101_202305_bil/PRISM_tmin_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   tmin<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmin_CN<-cbind(CN,tmin,year,month)
#   tmin_data_new<-rbind(tmin_data_new,tmin_CN)}
# }
# 
# tmin_comb_plantation <- bind_rows(as.data.frame(tmin_data_old), as.data.frame(tmin_data_new)) %>% filter(CN == "Plantation") %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmin=as.numeric(tmin))
# 
# tmin_comb_all <- bind_rows(as.data.frame(tmin_data_old), as.data.frame(tmin_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmin=as.numeric(tmin))
# 
# write.csv(tmin_comb_all, "tmin_comb_all.csv")
# 
# 
# ##tmax
# tmax_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmax_stable_4kmM3_198101_202305_bil/PRISM_tmax_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   tmax<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmax_CN<-cbind(CN,tmax,year,month)
#   tmax_data_old<-rbind(tmax_data_old,tmax_CN)}
# }
# 
# tmax_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmax_stable_4kmM3_198101_202305_bil/PRISM_tmax_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   tmax<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmax_CN<-cbind(CN,tmax,year,month)
#   tmax_data_new<-rbind(tmax_data_new,tmax_CN)}
# }
# 
# tmax_comb_plantation <- bind_rows(as.data.frame(tmax_data_old), as.data.frame(tmax_data_new)) %>% filter(CN == "Plantation") %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmax=as.numeric(tmax))
# 
# tmax_comb_all <- bind_rows(as.data.frame(tmax_data_old), as.data.frame(tmax_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmax=as.numeric(tmax))
# 
# write.csv(tmax_comb_all, "tmax_comb_all.csv")
# 
# ##tmean
# tmean_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmean_stable_4kmM3_198101_202305_bil/PRISM_tmean_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   tmean<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmean_CN<-cbind(CN,tmean,year,month)
#   tmean_data_old<-rbind(tmean_data_old,tmean_CN)}
# }
# 
# tmean_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmean_stable_4kmM3_198101_202305_bil/PRISM_tmean_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   tmean<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmean_CN<-cbind(CN,tmean,year,month)
#   tmean_data_new<-rbind(tmean_data_new,tmean_CN)}
# }
# 
# tmean_comb_plantation <- bind_rows(as.data.frame(tmean_data_old), as.data.frame(tmean_data_new)) %>% filter(CN == "Plantation") %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmean=as.numeric(tmean))
# 
# tmean_comb_all <- bind_rows(as.data.frame(tmean_data_old), as.data.frame(tmean_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmean=as.numeric(tmean))
# 
# write.csv(tmean_comb_all, "tmean_comb_all.csv")
# 
# 
# ##vpdmax
# vpdmax_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmax_stable_4kmM3_198101_202305_bil/PRISM_vpdmax_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmax<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmax_CN<-cbind(CN,vpdmax,year,month)
#   vpdmax_data_old<-rbind(vpdmax_data_old,vpdmax_CN)}
# }
# 
# vpdmax_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmax_stable_4kmM3_198101_202305_bil/PRISM_vpdmax_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmax<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmax_CN<-cbind(CN,vpdmax,year,month)
#   vpdmax_data_new<-rbind(vpdmax_data_new,vpdmax_CN)}
# }
# 
# vpdmax_comb_plantation <- bind_rows(as.data.frame(vpdmax_data_old), as.data.frame(vpdmax_data_new)) %>% filter(CN == "Plantation") %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), vpdmax=as.numeric(vpdmax))
# 
# vpdmax_comb_all <- bind_rows(as.data.frame(vpdmax_data_old), as.data.frame(vpdmax_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), vpdmax=as.numeric(vpdmax))
# 
# write.csv(vpdmax_comb_all, "vpdmax_comb_all.csv")
# 
# 
# ##vpdmin
# vpdmin_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmin_stable_4kmM3_198101_202305_bil/PRISM_vpdmin_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmin<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmin_CN<-cbind(CN,vpdmin,year,month)
#   vpdmin_data_old<-rbind(vpdmin_data_old,vpdmin_CN)}
# }
# 
# vpdmin_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmin_stable_4kmM3_198101_202305_bil/PRISM_vpdmin_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, provenances, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmin<-ext.poly[,2]
#   CN<-provenances$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmin_CN<-cbind(CN,vpdmin,year,month)
#   vpdmin_data_new<-rbind(vpdmin_data_new,vpdmin_CN)}
# }
# 
# vpdmin_comb_plantation <- bind_rows(as.data.frame(vpdmin_data_old), as.data.frame(vpdmin_data_new)) %>% filter(CN == "Plantation") %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), vpdmin=as.numeric(vpdmin))
# 
# vpdmin_comb_all <- bind_rows(as.data.frame(vpdmin_data_old), as.data.frame(vpdmin_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), vpdmin=as.numeric(vpdmin))
# 
# write.csv(vpdmin_comb_all, "vpdmin_comb_all.csv")

# ##save extracted climate data files
# write.csv(ppt_comb_plantation, "ppt_comb_plantation.csv")
# write.csv(tmax_comb_plantation, "tmax_comb_plantation.csv")
# write.csv(tmin_comb_plantation, "tmin_comb_plantation.csv")
# write.csv(tmean_comb_plantation, "tmean_comb_plantation.csv")
# write.csv(vpdmax_comb_plantation, "vpdmax_comb_plantation.csv")
# write.csv(vpdmin_comb_plantation, "vpdmin_comb_plantation.csv")

```

```{r}
## get PRISM data for adjusted coordinates

# #pull climate for 1970 - 2016 from PRISM
# ppt_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_ppt_stable_4kmM3_198101_202305_bil/PRISM_ppt_stable_4kmM2_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(CN,ppt,year,month)
#   ppt_data_old<-rbind(ppt_data_old,ppt_CN)}
# }
# 
# ppt_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_ppt_stable_4kmM3_198101_202305_bil/PRISM_ppt_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(CN,ppt,year,month)
#   ppt_data_new<-rbind(ppt_data_new,ppt_CN)}
# }
# 
# ppt_comb_all_adj <- bind_rows(as.data.frame(ppt_data_old), as.data.frame(ppt_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), ppt=as.numeric(ppt))
# 
# write.csv(ppt_comb_all_adj, "ppt_comb_all_adj.csv")
# 
# 
# ##tmin
# tmin_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmin_stable_4kmM3_198101_202305_bil/PRISM_tmin_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   tmin<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmin_CN<-cbind(CN,tmin,year,month)
#   tmin_data_old<-rbind(tmin_data_old,tmin_CN)}
# }
# 
# tmin_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmin_stable_4kmM3_198101_202305_bil/PRISM_tmin_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   tmin<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmin_CN<-cbind(CN,tmin,year,month)
#   tmin_data_new<-rbind(tmin_data_new,tmin_CN)}
# }
# 
# tmin_comb_all_adj <- bind_rows(as.data.frame(tmin_data_old), as.data.frame(tmin_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmin=as.numeric(tmin))
# 
# write.csv(tmin_comb_all_adj, "tmin_comb_all_adj.csv")
# 
# 
# ##tmax
# tmax_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmax_stable_4kmM3_198101_202305_bil/PRISM_tmax_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   tmax<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmax_CN<-cbind(CN,tmax,year,month)
#   tmax_data_old<-rbind(tmax_data_old,tmax_CN)}
# }
# 
# tmax_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmax_stable_4kmM3_198101_202305_bil/PRISM_tmax_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   tmax<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmax_CN<-cbind(CN,tmax,year,month)
#   tmax_data_new<-rbind(tmax_data_new,tmax_CN)}
# }
# 
# tmax_comb_all_adj <- bind_rows(as.data.frame(tmax_data_old), as.data.frame(tmax_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmax=as.numeric(tmax))
# 
# write.csv(tmax_comb_all_adj, "tmax_comb_all_adj.csv")
# 
# ##tmean
# tmean_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmean_stable_4kmM3_198101_202305_bil/PRISM_tmean_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   tmean<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmean_CN<-cbind(CN,tmean,year,month)
#   tmean_data_old<-rbind(tmean_data_old,tmean_CN)}
# }
# 
# tmean_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_tmean_stable_4kmM3_198101_202305_bil/PRISM_tmean_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   tmean<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   tmean_CN<-cbind(CN,tmean,year,month)
#   tmean_data_new<-rbind(tmean_data_new,tmean_CN)}
# }
# 
# tmean_comb_all_adj <- bind_rows(as.data.frame(tmean_data_old), as.data.frame(tmean_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), tmean=as.numeric(tmean))
# 
# write.csv(tmean_comb_all_adj, "tmean_comb_all_adj.csv")
# 
# 
# ##vpdmax
# vpdmax_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmax_stable_4kmM3_198101_202305_bil/PRISM_vpdmax_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmax<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmax_CN<-cbind(CN,vpdmax,year,month)
#   vpdmax_data_old<-rbind(vpdmax_data_old,vpdmax_CN)}
# }
# 
# vpdmax_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmax_stable_4kmM3_198101_202305_bil/PRISM_vpdmax_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmax<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmax_CN<-cbind(CN,vpdmax,year,month)
#   vpdmax_data_new<-rbind(vpdmax_data_new,vpdmax_CN)}
# }
# 
# vpdmax_comb_all_adj <- bind_rows(as.data.frame(vpdmax_data_old), as.data.frame(vpdmax_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), vpdmax=as.numeric(vpdmax))
# 
# write.csv(vpdmax_comb_all_adj, "vpdmax_comb_all_adj.csv")
# 
# 
# ##vpdmin
# vpdmin_data_old<-vector()
# for(i in 1:length(years_old)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmin_stable_4kmM3_198101_202305_bil/PRISM_vpdmin_stable_4kmM3_',years_old[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmin<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_old[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmin_CN<-cbind(CN,vpdmin,year,month)
#   vpdmin_data_old<-rbind(vpdmin_data_old,vpdmin_CN)}
# }
# 
# vpdmin_data_new<-vector()
# for(i in 1:length(years_new)){
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/annual/PRISM_vpdmin_stable_4kmM3_198101_202305_bil/PRISM_vpdmin_stable_4kmM3_',years_new[i],months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast, adjusted_provs, fun = mean, na.rm=TRUE, df=TRUE)
#   vpdmin<-ext.poly[,2]
#   CN<-adjusted_provs$ident
#   year <- rep(years_new[i],length(ext.poly[,2]))
#   month <- rep(months[j],length(ext.poly[,2]))
#   vpdmin_CN<-cbind(CN,vpdmin,year,month)
#   vpdmin_data_new<-rbind(vpdmin_data_new,vpdmin_CN)}
# }
# 
# vpdmin_comb_all_adj <- bind_rows(as.data.frame(vpdmin_data_old), as.data.frame(vpdmin_data_new)) %>%
#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), vpdmin=as.numeric(vpdmin))
# 
# write.csv(vpdmin_comb_all_adj, "vpdmin_comb_all_adj.csv")

```

##PRISM plots

```{r}
#read in files
ppt_comb_plantation<- read.csv("ppt_comb_plantation.csv")
tmax_comb_plantation<- read.csv("tmax_comb_plantation.csv")
tmin_comb_plantation<- read.csv("tmin_comb_plantation.csv")
tmean_comb_plantation<- read.csv("tmean_comb_plantation.csv")
vpdmax_comb_plantation<- read.csv("vpdmax_comb_plantation.csv")
vpdmin_comb_plantation<- read.csv("vpdmin_comb_plantation.csv")

ppt_comb_all<- read.csv("ppt_comb_all.csv")
tmax_comb_all<- read.csv("tmax_comb_all.csv")
tmin_comb_all<- read.csv("tmin_comb_all.csv")
tmean_comb_all<- read.csv("tmean_comb_all.csv")
vpdmax_comb_all<- read.csv("vpdmax_comb_all.csv")
vpdmin_comb_all<- read.csv("vpdmin_comb_all.csv")
```


```{r}
#plots

##ppt
ggplot(ppt_comb_plantation, aes(x=as.Date(date), y=ppt))+
  geom_line()+
  geom_hline(yintercept = mean(ppt_comb_plantation$ppt), col="red")

ppt_summed <- as.data.frame(ppt_comb_plantation) %>% 
  mutate(ppt = as.numeric(ppt), year=as.integer(year)) %>%
  filter(!is.na(ppt)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(ppt = sum(ppt)) 

ggplot(ppt_summed %>% filter(CN=="Plantation"), aes(x=year, y=ppt)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(ppt_summed %>% filter(CN=="Plantation") %>% pull(ppt)), col="red")

##seasonal ppt
ppt_seasonal_plantation <- ppt_comb_plantation %>% 
  filter(month %in% c(6,7,8)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_sm = sum(ppt)) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(5,6,7,8,9)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_gs = sum(ppt))) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(12,1,2)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_wt = sum(ppt))) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(9,10,11)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_fa = sum(ppt))) %>% 
  left_join(ppt_comb_plantation %>% 
  filter(month %in% c(3,4,5)) %>% 
  group_by(CN, year) %>% 
  summarise(ppt_sp = sum(ppt))) %>% 
  left_join(ppt_summed) 


##tmin
ggplot(tmin_comb_plantation, aes(x=as.Date(date), y=tmin))+
  geom_line()+
  geom_hline(yintercept = mean(tmin_comb_plantation$tmin), col="red")

tmin_summed <- as.data.frame(tmin_comb_plantation) %>% 
  mutate(tmin = as.numeric(tmin), year=as.integer(year)) %>%
  filter(!is.na(tmin)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(tmin = mean(tmin)) 

ggplot(tmin_summed %>% filter(CN=="Plantation"), aes(x=year, y=tmin)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(tmin_summed %>% filter(CN=="Plantation") %>% pull(tmin)), col="red")

##tmax
ggplot(tmax_comb_plantation, aes(x=as.Date(date), y=tmax))+
  geom_line()+
  geom_hline(yintercept = mean(tmax_comb_plantation$tmax), col="red")

tmax_summed <- as.data.frame(tmax_comb_plantation) %>% 
  mutate(tmax = as.numeric(tmax), year=as.integer(year)) %>%
  filter(!is.na(tmax)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(tmax = mean(tmax))

ggplot(tmax_summed %>% filter(CN=="Plantation"), aes(x=year, y=tmax)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(tmax_summed %>% filter(CN=="Plantation") %>% pull(tmax)), col="red")

##tmean
ggplot(tmean_comb_plantation, aes(x=as.Date(date), y=tmean))+
  geom_line()+
  geom_hline(yintercept = mean(tmean_comb_plantation$tmean), col="red")

tmean_summed <- as.data.frame(tmean_comb_plantation) %>% 
  mutate(tmean = as.numeric(tmean), year=as.integer(year)) %>%
  filter(!is.na(tmean)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(tmean = mean(tmean)) 

ggplot(tmean_summed %>% filter(CN=="Plantation"), aes(x=year, y=tmean)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(tmean_summed %>% filter(CN=="Plantation") %>% pull(tmean)), col="red")

##seasonal temps
all_temps <- bind_rows(tmean_comb_plantation %>% pivot_longer(tmean), tmin_comb_plantation %>% pivot_longer(tmin), tmax_comb_plantation %>% pivot_longer(tmax))

summertemps <- all_temps %>% filter(month %in% c(6,7,8)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_sm =mean(value))
falltemps <- all_temps %>% filter(month %in% c(9,10,11)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_fa =mean(value))
wintertemps <- all_temps %>% filter(month %in% c(12,1,2)) %>% 
  mutate(year = ifelse(month=="12",year+1,year)) %>% 
  filter(!year %in% c(1970,2017)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_wt =mean(value))
springtemps <- all_temps %>% filter(month %in% c(3,4,5)) %>% 
  group_by(CN, year, name) %>% 
  summarise(value_sp =mean(value))

plantation_seasonal_temps <- left_join(summertemps,falltemps) %>% 
  left_join(wintertemps) %>% 
  left_join(springtemps)

plantation_seasonal_temps_wide<- plantation_seasonal_temps %>% 
  pivot_wider(values_from = c(value_sm,value_fa,value_wt,value_sp), names_from = name)

##vpdmax
ggplot(vpdmax_comb_plantation, aes(x=as.Date(date), y=vpdmax))+
  geom_line()+
  geom_hline(yintercept = mean(vpdmax_comb_plantation$vpdmax), col="red")

vpdmax_summed <- as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(!is.na(vpdmax)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax = mean(vpdmax))

ggplot(vpdmax_summed %>% filter(CN=="Plantation"), aes(x=year, y=vpdmax)) +
  geom_point()+
  geom_line()+
  geom_hline(yintercept=mean(vpdmax_summed %>% filter(CN=="Plantation") %>% pull(vpdmax)), col="red")

vpdmax_seasonal <- as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(6,7,8)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_sm = mean(vpdmax)) %>% 
  left_join(as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(9,10,11)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_fa = mean(vpdmax))) %>% 
  left_join(as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(12,1,2)) %>% 
  mutate(year = ifelse(month == "12", year+1, year)) %>% 
  filter(!year %in% c(1970,2017)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_wt = mean(vpdmax))) %>% 
  left_join(as.data.frame(vpdmax_comb_plantation) %>% 
  mutate(vpdmax = as.numeric(vpdmax), year=as.integer(year)) %>%
  filter(month %in% c(3,4,5)) %>% 
  group_by(CN, year) %>% 
 dplyr::summarise(vpdmax_sp = mean(vpdmax)))


```

##FDSI calculation

```{r}
all_climate <- left_join(ppt_comb_plantation,tmax_comb_plantation) %>% 
  left_join(tmin_comb_plantation) %>% 
  left_join(tmean_comb_plantation) %>% 
  left_join(vpdmax_comb_plantation) %>% 
  left_join(vpdmin_comb_plantation) %>% 
  mutate(vpdmean=(vpdmin+vpdmax)/2)

nrow(all_climate)
nrow(tmin_comb_plantation)

all_climate_long <- all_climate %>% 
  select(-X) %>% 
  pivot_longer(c("ppt","tmax","tmin","tmean","vpdmax","vpdmin","vpdmean"), names_to="climvar", values_to = "value") %>% 
  mutate(monthvar = paste(climvar,month,sep=""))

climate_minus1<- all_climate_long %>% 
  mutate(year=year+1) %>% 
  mutate(monthvar = paste("yr1",climvar,month,sep=""))


climate_minus2<- all_climate_long %>% 
  mutate(year=year+2) %>% 
  mutate(monthvar = paste("yr2",climvar,month,sep=""))


climate_allyears <- rbind(all_climate_long, climate_minus1, climate_minus2)


### FDSI CALC

### CALCULATIONS TAKEN FROM WILLIAMS ET AL., 2013 
# DOI: 10.1038/NCLIMATE1693
#https://www.nature.com/articles/nclimate1693
FDSI_C <- climate_allyears %>%
  select(-c("date","month","climvar")) %>% 
  pivot_wider(id_cols=c("CN","year"), names_from = monthvar, values_from = value)

head(FDSI_C)

FDSI_raw<- FDSI_C %>% 
  group_by(CN, year) %>% 
  summarise(FDSIvpd=(((vpdmean5+vpdmean6+vpdmean7)/3)+(yr1vpdmean8+yr1vpdmean9+yr1vpdmean10)/3)/2, FDSIppt=log(yr1ppt11+yr1ppt12+ppt1+ppt2+ppt3))

meanVPD <- mean(FDSI_raw$FDSIvpd, na.rm=T)
meanppt <- mean(FDSI_raw$FDSIppt, na.rm=T)
SDVPD <- sd(FDSI_raw$FDSIvpd, na.rm=T)
SDppt <- sd(FDSI_raw$FDSIppt, na.rm=T)
FDSI_raw$zscoreppt <- ((FDSI_raw$FDSIppt-meanppt)/SDppt)
FDSI_raw$zscoreVPD <- ((FDSI_raw$FDSIvpd-meanVPD)/SDVPD)

FDSI_raw$FDSI <- (0.44*(FDSI_raw$zscoreppt)-0.56*(FDSI_raw$zscoreVPD))

ggplot(FDSI_raw, aes(x=year, y=FDSI))+
  geom_line()+
  geom_point()
#I think we need to consider the fact that FDSI was really high right before the drought of the early 2000's so that's why trees may not be showing equivalent growth rates after the drought (cause it was still relatively hot and dry)
```


##CWD calculation

```{r}
source("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/grad school/cwd_function_v3.r")

#get dem
dem_plantation <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/PIENproject/USGS_13_n40w107_20220216.tif")

slpasp <- terrain(dem_plantation, v = c("slope","aspect"))

slpasp_plantation <- terra::extract(slpasp, provenances %>% filter(ident=="Plantation"), method="simple")

plantation_cwd_data <- all_climate %>% left_join(as.data.frame(provenances) %>% filter(ident=="Plantation"), by=c("CN"="ident")) %>% 
  mutate(soilawc=116.5, foldedaspect = abs(180-abs(slpasp_plantation$aspect - 225)), slope=slpasp_plantation$slope)

plantation_cwd <- cwd_function(site="plantation",slope=plantation_cwd_data$slope, latitude=plantation_cwd_data$Latitude, foldedaspect = plantation_cwd_data$foldedaspect, ppt = plantation_cwd_data$ppt, tmean = plantation_cwd_data$tmean, month = plantation_cwd_data$month, soilawc = plantation_cwd_data$soilawc, year = plantation_cwd_data$year, type="annual")

head(plantation_cwd)

cwd_year0 <- plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month<9) %>% 
  group_by(site, year) %>% 
  summarise(cwd_1_9 = sum(cwd))

cwd_yearminus1 <-  plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month>8) %>%
  mutate(wateryear=year+1) %>% 
  group_by(site, wateryear) %>% 
  summarise(cwd_prev = sum(cwd))

wateryear_cwd<- cwd_year0 %>% 
  left_join(cwd_yearminus1, by=c("year" = "wateryear","site")) %>% 
  rowwise() %>% 
  mutate(cwd_wy = sum(cwd_1_9, cwd_prev))

sp_cwd<- plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(3,4,5)) %>%
  group_by(site, year) %>% 
  summarise(cwd_sp = sum(cwd))

fa_cwd<- plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(9,10,11)) %>%
  group_by(site, year) %>% 
  mutate(wateryear = year+1) %>% 
  summarise(cwd_fa = sum(cwd))

##water year drought
ggplot(wateryear_cwd, aes(x=year, y=cwd_wy))+
  geom_point()+
  geom_line()+
  geom_point(data= sp_cwd, aes(x=year, y=cwd_sp),col="green4")+
  geom_line(data= sp_cwd, aes(x=year, y=cwd_sp),col="green4")+
  geom_point(data= fa_cwd, aes(x=year, y=cwd_fa),col="orange")+
  geom_line(data= fa_cwd, aes(x=year, y=cwd_fa),col="orange")  ##1970s and 80s droughts were influenced more by fall lack of moisture than 2002 drought. 


wateryear_cwd %>% 
  filter(cwd_wy>quantile(wateryear_cwd$cwd_wy[-1], c(0.75))+ 1.5*IQR(wateryear_cwd$cwd_wy[-1]))

##spring drought
ggplot( plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(3,4,5)) %>%
  group_by(site, year) %>% 
  summarise(cwd_sp = sum(cwd)), aes(x=year, y=cwd_sp))+
  geom_point()+
  geom_line()

##fall drought
ggplot( plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% 
  filter(month%in%c(9,10,11)) %>%
  group_by(site, year) %>% 
  summarise(cwd_fa = sum(cwd)), aes(x=year, y=cwd_fa))+
  geom_point()+
  geom_line()

ggplot(plantation_cwd %>% 
  mutate(date= as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y")) %>% filter(month%in%c(6,7,8)), aes(x=date, y=cwd))+
  geom_point(aes(col=factor(year)))+
  geom_line()

plantation_cwd %>% 
  filter(cwd>0) %>% 
  group_by(month) %>% 
  summarise(n=n(), mean=mean(cwd))


plantation_cwd_annual <- plantation_cwd %>% 
  group_by(site,year, soilawc) %>% 
  summarise(ppt_sum = sum(ppt), tmean_ave=mean(tmean), aet_sum=sum(aet), cwd_sum=sum(cwd))

plantation_cwd_annual_long<- plantation_cwd_annual %>% 
  left_join(FDSI_raw %>% dplyr::select(year,FDSI), by="year") %>% 
  dplyr::select(-CN) %>% 
  pivot_longer(ppt_sum:FDSI)

ggplot(plantation_cwd_annual_long %>% filter(name%in%c("cwd_sum","FDSI")), aes(x=year, y=value, col=name))+
  geom_point()+
  geom_line()+
  facet_wrap(~name, scales = "free")
  
```

```{r}
plantation_climatebalance <- plantation_cwd %>% 
  mutate(ppt_pet = ppt - petm)

library(SPEI)

plantation_spei <- spei(plantation_climatebalance %>% pull(ppt_pet), scale=1)
plantation_spei$fitted
summary(plantation_spei)

plantation_spei_sum <- data.frame(year=plantation_climatebalance$year, month=plantation_climatebalance$month, spei = plantation_spei$fitted, date = as.Date(paste(plantation_climatebalance$month,"01",plantation_climatebalance$year, sep="/"), "%m/%d/%Y"))

#   mutate(date=as.Date(paste(month,"01",year,sep="/"), "%m/%d/%Y"), ppt=as.numeric(ppt))


ggplot(plantation_spei_sum %>% filter(year > 1987 & year <2012), aes(x=date, y=spei, fill=spei>0))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

plantation_spei_annual<- plantation_spei_sum %>% 
  group_by(year) %>% 
  summarise(spei_mean = mean(spei), spei_sum=sum(spei))


ggplot(plantation_spei_annual %>% filter(year > 1987 & year <2012), aes(x=year, y=spei_sum, fill=spei_sum>0))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


```

##All climate vars

```{r}
#combine all climate vars

plantation_clim <- ppt_seasonal_plantation %>% 
  left_join(plantation_seasonal_temps_wide) %>% 
  left_join(vpdmax_seasonal) %>% 
  left_join(FDSI_raw) %>% 
  left_join(plantation_cwd_annual) %>% 
  left_join(wateryear_cwd) %>% 
  left_join(plantation_spei_annual)

colnames(plantation_clim)

plantation_clim_long <- plantation_clim %>% 
 select(c(CN:vpdmax_sp, FDSI, aet_sum, cwd_sum, cwd_wy, spei_sum)) %>% 
  pivot_longer(ppt_sm:spei_sum)

plantation_clim_long_qs<- plantation_clim_long %>% 
  left_join(plantation_clim_long %>% 
  filter(!is.na(value)) %>% 
  group_by(name) %>% 
  summarise(q2.5 = quantile(value, 0.025), q97.5 = quantile(value, 0.975), out.hi = quantile(value, c(0.75))  + IQR(value)*1.5, out.low = quantile(value, c(0.75)) - IQR(value)*1.5))


ggplot(plantation_clim_long_qs, aes(x=year, y=value, col=name))+
  geom_point()+
  geom_line()+
  facet_wrap(~name, scales="free")+
  geom_line(data=plantation_clim_long_qs, aes(x=year, y=out.low), col="black")+
  geom_line(data=plantation_clim_long_qs, aes(x=year, y=out.hi), col="black")

#quantile(rw_clim_wide$cwd_sum, c(0.75))  + IQR(rw_clim_wide$cwd_sum)*1.5

```


#PCA

```{r}
#make PCA

#first look at correlations in climate variables
env_vars<- prov_clim %>% 
  dplyr::select(c(MAT:pas,smrpb))

env_vars %>% 
  cor() %>% 
  abs()>0.9
##CMD is only super correlated to temperature variables and not precipitation variables, which makes me think it is overall more driven by temperature than precipitation

env_vars_cut <- env_vars %>% 
  dplyr::select(-c(bFFP, eFFP, EMT, pas, dd5, dd_0))

env_vars_cut %>%
  cor() %>% 
  abs()>0.9
```

```{r,eval=FALSE,echo=FALSE}
#look at linearity of relationships

pairs(env_vars_cut, lower.panel = NULL)

```

```{r, echo = FALSE}
#run the PCA 
set.seed(83)
clim_pca <- prcomp(env_vars_cut,scale.=T) #proceed from correlation matrix, which scales variables--important because our variables have different units

##to get eigenvalues, we do the square of the stdev
eigenvals <- (clim_pca$sdev)^2
eigenvals
sum(eigenvals) #the sum of the eigenvalues = the number of variables (9)
eigenvals/sum(eigenvals)#this is the proportion variance explained
summary(clim_pca)
par(mfrow=c(1,1))
plot(clim_pca,type="l")
```

```{r, echo=FALSE}
as.data.frame(clim_pca$rotation[,1:2]) %>% 
  tibble::rownames_to_column() %>% 
  arrange(desc(abs(PC1)))
as.data.frame(clim_pca$rotation[,1:2]) %>% 
  tibble::rownames_to_column() %>% 
  arrange(desc(abs(PC2)))
as.data.frame(clim_pca$rotation[,1:3]) %>% 
  tibble::rownames_to_column() %>% 
  arrange(desc(abs(PC3)))
```

```{r}

#plot PCA
prov_pcapts<- clim_pca$x %>% 
  cbind(prov_clim) %>% 
  mutate(state = substr(ident,6,7), number = substr(ident, 1,4)) %>% 
  left_join(prov_names)

state.colors <- c(brewer.pal(n=9, name="Set1")[-6],"darkolivegreen")

autoplot(clim_pca,x=1,y=2,colour="aquamarine3",loadings.colour="red", loadings=T, loadings.label=T, loadings.label.colour="black", scale=0, loadings.label.size=6)+
  geom_point(data=prov_pcapts, aes(x=PC1, y=PC2, col=state), size=5)+
  geom_text_repel(data=prov_pcapts, aes(x=PC1, y=PC2, label=code))+
  scale_color_manual(values=state.colors)+
  theme(text=element_text(size=14, color="black"))
  
ggplot()+
  geom_spatvector(data=westernus)+
  geom_spatvector(data=provenances, color="maroon")+
  geom_spatvector_text(data=provenances, aes(label=substr(ident,1,4)), hjust=c(rep(c(-0.2,1),2),-.2,-.2,-.2,0,rep(c(-.2,1),5),1,1,1))

ggplot()+
  geom_spatvector(data=westernus)+
  geom_spatvector(data=provenances, color="maroon")+
  geom_spatvector_text(data=provenances %>% 
  left_join(prov_names), aes(label=code, hjust=c(rep(c(-0.2,1),2),-.2,-.2,-.2,0,rep(c(-.2,1),5),1,1,1)))


```

```{r}
plantation_pc1<- prov_pcapts %>% 
  filter(Provenance=="Plantation") %>% 
  pull(PC1)

plantation_pc2<- prov_pcapts %>% 
  filter(Provenance=="Plantation") %>% 
  pull(PC2)

pca_dist_df <- prov_pcapts %>% 
  mutate(PC1diff = abs(PC1-plantation_pc1), PC2diff = abs(PC2 - plantation_pc2)) %>% 
  mutate(dist.to.plant = sqrt(PC1diff^2 + PC2diff^2)) %>% 
  arrange(dist.to.plant) %>% 
  filter(!Provenance=="Plantation")
```

##Engelmann spruce

```{r}
pien <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ArcGIS/Projects/SpeciesRanges/pien_range.tif")

us <- geodata::gadm(country = "USA",  level = 1, resolution = 2,
             path = "C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/maps")
states=c("Arizona","Colorado","Idaho","Montana","Nevada","New Mexico","South Dakota","North Dakota","Nebraska","Utah","Wyoming","Kansas")
interiorwest <- us[match(toupper(states),toupper(us$NAME_1)),]


pien2 <- classify(pien, cbind(-Inf, 0, NA), right=TRUE)
plot(pien2)

pien_trim<- trim(pien2)
plot(pien_trim)

pien_IW<- crop(pien_trim %>% project(crs(interiorwest)), interiorwest)
plot(pien_IW)

pien_uniform <- classify(pien_IW, cbind(-Inf,Inf,1))
plot(pien_uniform)

pien_poly <- as.polygons(pien_uniform)
plot(pien_poly)

# engelmann_clim <- terra::extract(clim_raster_stack, pien_poly %>% project(crs(clim_raster_stack)), method="simple", weights=TRUE)
# 
# ##extract PRISM data for summer/spring precip ratio
# ppt_data_pien<-vector()
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/PRISM_ppt_30yr_normal_800mM4_all_bil/PRISM_ppt_30yr_normal_800mM4_',months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast,pien_poly %>% project(crs(clim_raster_stack)), method="simple", weights = TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   ID<- seq(1:nrow(ext.poly))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(ID,ppt,month)
#   ppt_data_pien<-rbind(ppt_data_pien,ppt_CN)}
# 
# pien_ppt_sum<- ppt_data_pien %>%
#   as.data.frame() %>%
#   unique() %>%
#   mutate(ppt=as.numeric(ppt), ID = as.numeric(ID)) %>%
#   pivot_wider(id_cols=ID, names_from=month, values_from = ppt) %>%
#   rowwise() %>%
#   mutate(JA_ppt = sum(`07`,`08`, na.rm=T), smrpb = sum(`07`,`08`,`09`,na.rm=T)/sum(`04`,`05`,`06`, na.rm=T))
# 
# saveRDS(pien_ppt_sum, "pien_ppt_sum.RDS")
# saveRDS(engelmann_clim, "engelmann_clim.RDS")

pien_ppt_sum <- readRDS("pien_ppt_sum.RDS")

#clim_pien <- left_join(engelmann_clim, pien_ppt_sum) ##not sure how to do this with polygons and weights

engelmann_clim <- readRDS("engelmann_clim.RDS")


prov_clim_states <- prov_clim %>% 
    mutate(state = substr(ident,6,7), number = substr(ident, 1,4)) %>% 
  left_join(prov_names) 
  

ggplot(engelmann_clim, aes(x=MAT, y=map))+
  geom_hex(alpha=0.7)+
  scale_fill_gradientn(colors=c("aquamarine","gold","white"))+
  geom_point(data=prov_clim_states, aes(x=MAT, y=map, col=state), size=4)+
  scale_color_manual(values = state.colors)+
  theme_bw()+
  theme(text = element_text(size=16, color="black"))

ggplot(engelmann_clim, aes(x=MAT, y=map))+
  geom_hex(alpha=0.7)+
  scale_fill_gradientn(colors=c("aquamarine","gold","white"))+
  geom_point(data=prov_clim_states, aes(x=MAT, y=map, col=state), size=4)+
  ggrepel::geom_text_repel(data=prov_clim_states, aes(label=code))+
  scale_color_manual(values = state.colors)+
  theme_bw()+
  theme(text = element_text(size=16, color="black"))

```

```{r}
############### OLD WAY WITH POINTS #####################
# pien <- rast("C:/Users/KatherineNigro/OneDrive - USDA/Documents/ArcGIS/Projects/SpeciesRanges/pien_range.tif")
# 
# pien2 <- clamp(pien, lower=1, value=FALSE)
# pien3 <- trim(pien2)
# 
# engelmann_points <- spatSample(pien3, size=100000000, method="regular", replace=FALSE, na.rm=TRUE, as.points=TRUE, values=TRUE, xy=TRUE)
# 
# engelmann_clim <- terra::extract(clim_raster_stack, engelmann_points %>% project(crs(clim_raster_stack)), method="simple")
# 
# ##extract PRISM data for summer/spring precip ratio
# ppt_data_pien<-vector()
# for(j in 1:length(months)){
#   raster<-paste(climdir,'/PRISM_ppt_30yr_normal_800mM4_all_bil/PRISM_ppt_30yr_normal_800mM4_',months[j],'_bil.bil',sep="")
#   rast <- rast(raster)
#   ext.poly <- terra::extract(rast,engelmann_points %>% project(crs(clim_raster_stack)), method="simple", na.rm=TRUE, df=TRUE)
#   ppt<-ext.poly[,2]
#   ID<- seq(1:nrow(engelmann_points))
#   month <- rep(months[j],length(ext.poly[,2]))
#   ppt_CN<-cbind(ID,ppt,month)
#   ppt_data_pien<-rbind(ppt_data_pien,ppt_CN)}
# 
# pien_ppt_sum<- ppt_data_pien %>% 
#   as.data.frame() %>% 
#   unique() %>% 
#   mutate(ppt=as.numeric(ppt), ID = as.numeric(ID)) %>% 
#   pivot_wider(id_cols=ID, names_from=month, values_from = ppt) %>% 
#   rowwise() %>% 
#   mutate(JA_ppt = sum(`07`,`08`, na.rm=T), smrpb = sum(`07`,`08`,`09`,na.rm=T)/sum(`04`,`05`,`06`, na.rm=T)) 
# 
# clim_pien <- left_join(engelmann_clim, pien_ppt_sum) 
# 
# saveRDS(clim_pien, "clim_pien.RDS")
# 
# clim_pien <- readRDS("clim_pien.RDS")
```

#DBH

```{r}
##DBH data is in centimeters
dbh <- read.csv("C:/Users/KatherineNigro/Box/Engelmann Spruce Provenance/Analysis/RWI_data/DBH_data.csv")

head(dbh)

dbh_long<- dbh %>% 
    mutate(Provenance = ifelse(Provenance == "Grand Mesa - Uncompahgre", "GM-U", Provenance)) %>% 
  filter(!is.na(DBH91)) %>% 
  pivot_longer(DBH91:DBH14, names_to = 'year', values_to = 'DBH')

provs_arranged_lat<- prov_pcapts %>% 
  mutate(Provenance = gsub(" NF","", prov_pcapts$Provenance)) %>% 
  arrange(Latitude) %>% 
  pull(Provenance)
unique(dbh_long$Provenance)
provs_arranged_lat

dbh_clim_data <- dbh_long %>% 
  mutate(Provenance = ifelse(Provenance == "Grand Mesa - Uncompahgre", "GM-U", Provenance)) %>% 
  left_join(prov_pcapts %>% 
  mutate(Provenance = gsub(" NF","", prov_pcapts$Provenance)), by="Provenance")

ggplot(dbh_long, aes(x=factor(Provenance, levels=provs_arranged_lat), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

ggplot(dbh_clim_data, aes(x=factor(nffd), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

ggplot(dbh_clim_data, aes(x=factor(cmd), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

ggplot(dbh_clim_data, aes(x=factor(smrpb), y=DBH, col=Provenance))+
  geom_boxplot()+
  facet_wrap(~factor(year,levels=c("DBH91","DBH96","DBH06","DBH14")), nrow=1)+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

#model for dbh
dbh_cmd_data<- dbh_clim_data %>% filter(year=="DBH14") %>% 
  mutate(DBH=as.numeric(DBH), cmd=as.numeric(cmd)) %>% 
  group_by(Provenance,cmd) %>% 
  summarise(ave_dbh14 = mean(DBH, na.rm=T), n=n())

mod_dbh_cmd <- lm(ave_dbh14 ~ cmd, data=dbh_cmd_data)
summary(mod_dbh_cmd)
```

##model

```{r}
dbh_numeric <- dbh_clim_data %>% 
  mutate(num.yr = as.numeric(ifelse(year=="DBH91", 1,
                         ifelse(year=="DBH96", 6,
                                ifelse(year=="DBH06", 16,
                                       ifelse(year=="DBH14", 24, year))))))

dbh_aov <- aov(DBH ~ year*Provenance, data = dbh_numeric)
summary(dbh_aov)
dbh_lm <- lm(DBH ~ year*Provenance, data=dbh_numeric)
summary(dbh_lm)
car::Anova(dbh_lm, type=3)
dbh_tukey <- TukeyHSD(dbh_aov)
dbh_tukey$year
dbh_tukey$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)

dbh_tukey_sig<- dbh_tukey$`year:Provenance` %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05) %>% 
  mutate(comparison = rownames(dbh_tukey$`year:Provenance` %>%
  as.data.frame() %>% filter(`p adj` < 0.05)))

dbh_tukey_sig %>% dplyr::select(comparison) %>% arrange(comparison) %>% View()

dbh_sig_comps<- bind_rows(
as.data.frame(stringr::str_split_fixed(dbh_tukey_sig$comparison, "\\W+", n=6)) %>%
  mutate(id = seq(1,n())) %>% 
  dplyr::filter(str_detect(V3, "DBH"))%>% 
  dplyr::select(id,V1,V3) %>% 
  dplyr::rename(first = V1, second = V3),
as.data.frame(stringr::str_split_fixed(dbh_tukey_sig$comparison, "\\W+", n=6)) %>% 
  mutate(id = seq(1,n())) %>% 
  dplyr::filter(str_detect(V4, "DBH"))%>% 
  dplyr::select(id,V1,V4)%>% 
  dplyr::rename(first = V1, second = V4),
as.data.frame(stringr::str_split_fixed(dbh_tukey_sig$comparison, "\\W+", n=6)) %>% 
  mutate(id = seq(1,n())) %>% 
  dplyr::filter(str_detect(V5, "DBH"))%>% 
  dplyr::select(id, V1,V5)%>% 
  dplyr::rename(first = V1, second = V5)
) %>% arrange(id) 

dbh_sig_comps %>% 
  mutate(same = dbh_sig_comps$first == dbh_sig_comps$second) %>% 
  filter(same == "TRUE")
  
dbh_tukey_sig[c(16,275,279,309,318),]

prov_dbh_order<- dbh_numeric %>% 
  filter(year=="DBH14") %>% 
  group_by(Provenance) %>% 
  summarise(med_DBH = median(DBH, na.rm=T)) %>% 
  arrange(med_DBH)

dbh_early<- ggplot(dbh_numeric %>% filter(!year=="DBH14"), aes(x=factor(year, levels=c("DBH91","DBH96","DBH06"), labels=c(1991,1996,2006)), y=DBH, fill=factor(Provenance, levels=prov_dbh_order$Provenance)))+
  geom_boxplot()+
  scale_x_discrete(name="Year")+
  scale_fill_discrete(name="Provenance")
  
dbh_2014<- ggplot(dbh_numeric %>% filter(year=="DBH14"), aes(x=factor(year, levels=c("DBH14"), labels=c(2014)), y=DBH, fill=factor(Provenance, levels=prov_dbh_order$Provenance)))+
  geom_boxplot()+
  scale_x_discrete(name="Year")+
  scale_fill_discrete(name="Provenance")

ggarrange(dbh_early,dbh_2014, nrow=2, common.legend = TRUE)
  

###model each year separately
dbh_aov91 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH91"))
summary(dbh_aov91)
TukeyHSD(dbh_aov91)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)
 
dbh_aov96 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH96"))
summary(dbh_aov96)
TukeyHSD(dbh_aov96)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)
  
dbh_aov06 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH06"))
summary(dbh_aov06)
TukeyHSD(dbh_aov06)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)
  
dbh_aov14 <- aov(DBH ~ Provenance, data = dbh_numeric %>% filter(year=="DBH14"))
summary(dbh_aov14)
TukeyHSD(dbh_aov14)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj` < 0.05)

prov_clim_states %>% 
  filter(Provenance %in% c("Gila NF","Cache NF","Cutting Permit 31"))


ggplot(prov_clim_long, aes(x=Provenance, y=value, col=Provenance %in% c("Gila NF","Cache NF","Cutting Permit 31")))+
  geom_point()+
  facet_wrap(~name, scales="free")+
  theme(legend.position = "none", axis.text.x = element_text(angle=45,hjust=1))

##does DBH vary with climate vars?

dbh14_long <- dbh_numeric %>% 
  filter(year=="DBH14") %>% 
  pivot_longer(cols=c(PC1,PC2,PC3))

ggplot(dbh14_long, aes(x=value, y=DBH))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~name, scales="free") ##doesn't look like there's much there.

ggplot(dbh_numeric %>% 
  filter(year=="DBH14"), aes(x=Latitude, y=DBH))+
  geom_point()+
  geom_smooth(method="lm")

dbh_num14 <- dbh_numeric %>% filter(year=="DBH14")

mod_dbh_lat <- lm(DBH ~ Latitude+ I(Latitude^2), data=dbh_num14)
summary(mod_dbh_lat)

mod_dbh_nffd <- lm(DBH ~ nffd, data=dbh_num14)
summary(mod_dbh_nffd)

predicted_scores <- predict(
  mod_dbh_lat, 
  newdata = data.frame(
    Latitude = seq(min(dbh_num14$Latitude), 
                      max(dbh_num14$Latitude), 
                      length.out = 100
                      )
    )
  )

plot(dbh_num14$Latitude, dbh_num14$DBH)
lines( seq(min(dbh_num14$Latitude), 
                      max(dbh_num14$Latitude), 
                      length.out = 100
                      ), predicted_scores, col="red")

ggplot(dbh_num14, aes(x=nffd, y=DBH))+
  geom_point()
```

#Height

```{r}
moniger_data <- read.csv("past_moniger_data.csv")
moniger_data_ids <- read.csv("past_moniger_data_ids.csv")

head(moniger_data_ids)
head(moniger_data)

moniger_data_comb <- moniger_data %>% 
  left_join(moniger_data_ids, by=c("LOC" = "ID.Code")) %>% 
  mutate(Provenance = ifelse(Location == "Grand Mesa-Uncompahgre NF", "GM-U NF", 
                             ifelse(Location == "Larimer County 1","Larimer 1",
                                    ifelse(Location == "Larimer County 2","Larimer 2",Location)))) %>% 
  left_join(prov_pcapts)

colnames(moniger_data_comb)

ggplot(moniger_data_comb, aes(x=factor(cmd), y=HT14, fill=Provenance))+
  geom_boxplot()+
  theme(legend.position = 'none', axis.text.x = element_text(angle=45, hjust=1))

ht_data <- moniger_data_comb %>% 
  dplyr::select(c(Provenance,HT74:HT14,Seedling.Ht..from.Nursery)) %>% 
  pivot_longer(HT74:HT14) %>% 
  mutate(nursery_ht_m = Seedling.Ht..from.Nursery/39.37) %>% 
  mutate(rel.ht.m = (value-nursery_ht_m), rel.growth = (value-nursery_ht_m)/nursery_ht_m)

ht_data_clim <- ht_data %>% 
  left_join(prov_pcapts)

ht.order <- ht_data %>% 
  filter(name=="HT14") %>% 
  group_by(Provenance) %>% 
  summarise(med_rel_growth=median(rel.growth,na.rm=T)) %>% 
  arrange(med_rel_growth)

ggplot(ht_data %>% filter(!name=="HT74"), aes(x=factor(Provenance, levels=ht.order$Provenance), y=rel.growth, fill=factor(Provenance, levels=ht.order$Provenance)))+
  geom_boxplot()+
  facet_wrap(~factor(name, levels=c("HT79","HT85","HT91","HT96","HT06","HT14")), scales="free")+
  scale_fill_discrete(name="Provenance")+
  scale_x_discrete(name="Provenance")+
  theme(axis.text.x = element_blank())

###model each year separately

ht_aov_74 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT74"))
summary(ht_aov_74)
TukeyHSD(ht_aov_74)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ht_aov_79 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT79"))
summary(ht_aov_79)
TukeyHSD(ht_aov_79)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ht_aov_85 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT85"))
summary(ht_aov_85)
TukeyHSD(ht_aov_85)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ht_aov_91 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT91"))
summary(ht_aov_91)
TukeyHSD(ht_aov_91)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ht_aov_96 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT96"))
summary(ht_aov_96)
TukeyHSD(ht_aov_96)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ht_aov_06 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT06"))
summary(ht_aov_06)
TukeyHSD(ht_aov_06)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ht_aov_14 <- aov(rel.growth ~ Provenance, data=ht_data %>% filter(name=="HT14"))
summary(ht_aov_14)
TukeyHSD(ht_aov_14)$Provenance %>% 
  as.data.frame() %>% 
  filter(`p adj`<0.05)

ggplot(ht_data_clim %>% filter(name=="HT14"), aes(x=Latitude, y=rel.growth, col=Provenance))+
  geom_point()
ggplot(ht_data_clim %>% filter(name=="HT14"), aes(x=SHM, y=rel.growth, col=Provenance))+
  geom_point()

##survival
tree.num <- ht_data %>% 
  filter(!is.na(rel.growth)) %>% 
  group_by(name, Provenance) %>% 
  summarise(n=n()) %>% 
  mutate(year = case_when(
    name=="HT74" ~ 1974,
    name=="HT79" ~ 1979,
    name=="HT85" ~ 1985,
    name=="HT91" ~ 1991,
    name=="HT96" ~ 1996,
    name=="HT06" ~ 2006,
    name=="HT14" ~ 2014))

trees.died<- tree.num %>% 
  left_join(tree.num %>% filter(year==1974) %>% ungroup() %>%  select(Provenance, n) %>% rename(n_74=n)) %>% 
  mutate(prop = n/n_74)

ggplot(tree.num, aes(x=year, y=n, col=Provenance))+
  geom_point()+
  geom_line()

ggplot(trees.died %>% filter(name=="HT14"), aes(x=Provenance, y=prop))+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

```


```{r}
#compare climates of provenances
prov_vars<- prov_clim %>% 
  dplyr::select(c(ident,MAT:pas,smrpb)) %>% 
  dplyr::select(-c(bFFP, eFFP, EMT, pas, dd5, dd_0)) %>% 
  mutate(number=substr(ident,1,4)) %>% 
  left_join(prov_names) %>% 
  pivot_longer(MAT:smrpb, names_to = "var", values_to = "value")

ggplot(prov_vars, aes(x=factor(Provenance,levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance)), y=value, color=factor(Provenance,levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance))))+
  geom_point(size=4)+
  facet_wrap(~var, scales="free")+
  scale_color_manual(values=heat.colors(21))+
  theme(axis.text.x = element_text(angle=45,hjust=1), legend.position = 'none')

ggplot(prov_vars %>% filter(!Provenance=="Gila NF"), aes(x=factor(Provenance,levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance)), y=value, color=factor(Provenance,levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance))))+
  geom_point(size=4)+
  facet_wrap(~var, scales="free")+
  scale_color_manual(values=heat.colors(21))+
  theme(axis.text.x = element_text(angle=45,hjust=1), legend.position = 'none')
```

```{r}
#difference between first and last DBH

dbh_diffs<- dbh %>% 
  mutate(diff_total = DBH14 - DBH91, 
         diff3 = DBH14 - DBH06,
         diff2 = DBH06 - DBH96,
         diff1 = DBH96 - DBH91)

dbh_diffs_long <- dbh_diffs %>% 
  mutate(Provenance = gsub(" NF","", Provenance)) %>% 
  mutate(Provenance = ifelse(Provenance == "Grand Mesa - Uncompahgre", "GM-U", Provenance)) %>% 
  pivot_longer(c(DBH91:DBH14,diff_total:diff1)) %>% 
  left_join(prov_pcapts %>% 
  mutate(Provenance = gsub(" NF","", prov_pcapts$Provenance)), by="Provenance") %>% 
  filter(!is.na(value))
  
ggplot(dbh_diffs_long %>% filter(name %in% c("diff_total","diff1","diff2","diff3")), aes(x=factor(Provenance, levels=provs_arranged_lat), y=value, fill=Provenance))+
  geom_boxplot()+
  facet_wrap(~name, scales="free")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


dbh_diffs_long$Provenance %>% unique()

##models
diff_total_df <- dbh_diffs_long %>% 
  filter(name == "diff_total")

dbhdiff_mod <- lmer(value ~ PC1 * PC2 + (1|Provenance), data=diff_total_df)
plot(dbhdiff_mod)
lattice::qqmath(dbhdiff_mod)
summary(dbhdiff_mod)
Anova(dbhdiff_mod, type="3")

ggplot(dbh_diffs_long, aes(x= PC1, y=value))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~name, scales="free")

dbh_diffs_prov_ave <- dbh_diffs_long %>% 
  group_by(Provenance, name, PC1, PC2) %>% 
  summarise(meanvalue = mean(value))

ggplot(dbh_diffs_prov_ave %>% filter(!Provenance=="Gila"), aes(x= PC1, y=meanvalue))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~name, scales="free")
ggplot(dbh_diffs_prov_ave %>% filter(!Provenance=="Gila"), aes(x= PC2, y=meanvalue))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~name, scales="free")


```

#Cones

```{r}
cone_data <- moniger_data_comb %>% 
  dplyr::select(c(SORT,Provenance,Cones85:Cones06)) %>% 
  pivot_longer(Cones85:Cones06) %>% 
  mutate(year=case_when(name == "Cones85" ~ 1985,
                        name == "Cones91" ~ 1991,
                        name == "Cones96" ~ 1996,
                        name == "Cones06" ~ 2006))


cone_sum <- cone_data %>%
  filter(!is.na(value)) %>% 
  group_by(Provenance,year) %>% 
  summarise(value=sum(value), n=n()) %>% 
  mutate(prop.w.cones = value/n)

ave_hts <- moniger_data_comb %>% 
  dplyr::select(c(SORT,Provenance,HT85:HT06)) %>% 
  pivot_longer(HT85:HT06) %>% 
  mutate(year=case_when(name == "HT85" ~ 1985,
                        name == "HT91" ~ 1991,
                        name == "HT96" ~ 1996,
                        name == "HT06" ~ 2006)) %>% 
  filter(!is.na(value)) %>% 
  group_by(Provenance, year) %>% 
  summarise(ave.ht = mean(value), se.ht = sd(value)/sqrt(n())) %>% 
  left_join(cone_sum)

ave_dbh <- moniger_data_comb %>% 
  dplyr::select(c(SORT,Provenance,DBH91:DBH06)) %>% 
  pivot_longer(DBH91:DBH06) %>% 
  mutate(year=case_when(name == "DBH91" ~ 1991,
                        name == "DBH96" ~ 1996,
                        name == "DBH06" ~ 2006)) %>%
  filter(!is.na(value)) %>% 
  group_by(Provenance, year) %>% 
  summarise(ave.dbh = mean(value), se.dbh = sd(value)/sqrt(n())) %>% 
  left_join(cone_sum)

ggplot(ave_hts, aes(x=ave.ht, y=prop.w.cones, col=Provenance))+
  geom_point()+
  geom_errorbar(aes(xmin=ave.ht - se.ht, xmax=ave.ht+se.ht))

ggplot(ave_dbh, aes(x=ave.dbh, y=prop.w.cones, col=Provenance))+
  geom_point()+
  geom_errorbar(aes(xmin=ave.dbh-se.dbh, xmax=ave.dbh+se.dbh))

ggplot(moniger_data_comb, aes(x=HT85, y=Cones85))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=HT91, y=Cones91))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=HT96, y=Cones96))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=HT06, y=Cones06))+
  geom_jitter(height=0.1)

ggplot(moniger_data_comb, aes(x=DBH91, y=Cones91))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=DBH96, y=Cones96))+
  geom_jitter(height=0.1)
ggplot(moniger_data_comb, aes(x=DBH06, y=Cones06))+
  geom_jitter(height=0.1)

ggplot(cone_sum, aes(x=year, y=prop.w.cones, col=Provenance))+
  geom_point()+
  geom_line()
```

#RWI

##Raw

```{r}
prov_all <- read.rwl("C:/Users/KatherineNigro/Box/Engelmann Spruce Provenance/Ring_widths_raw/prov_all.rwl")
```

##Standardized

```{r}
rwi<- read.csv("C:/Users/KatherineNigro/Box/Engelmann Spruce Provenance/Analysis/RWI_data/Prov_resid_long.csv") %>% 
  mutate(Provenance = case_when(
    Provenance == "Roosevelt" ~ "Roosevelt NF",
    Provenance == "Pike" ~ "Pike NF",
    Provenance == "San Juan" ~ "San Juan NF",
    Provenance == "Gunnison" ~ "Gunnison NF",
    Provenance == "Santa Fe" ~ "Santa Fe NF",
    Provenance == "Coconino" ~ "Coconino NF",
    Provenance == "Payette" ~ "Payette NF",
    Provenance == "Cache" ~ "Cache NF",
    Provenance == "Dixie" ~ "Dixie NF",
    Provenance == "Okanogan" ~ "Okanogan NF",
    Provenance == "Wenatchee" ~ "Wenatchee NF",
    Provenance == "Wallowa Whitman" ~ "Wallowa-Whitman NF",
    Provenance == "Grand Mesa - Uncompahgre" ~ "GM-U NF",
    Provenance == "Gila" ~ "Gila NF",
    .default = Provenance
  ))

ggplot(rwi, aes(x=Year, y=RWI, col=Tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance, scales="free")+
  theme(legend.position = 'none')

summary(rwi$Year)

head(rwi)


##correlate rwi with ppt
ppt_plantation <- ppt_summed %>% 
  filter(CN =="Plantation")

rwi_ppt<- left_join(rwi,ppt_plantation, by=c("Year"="year")) %>% 
  filter(!is.na(RWI)) %>% 
  group_by(Provenance,Tree) %>% 
  summarise(cor=cor(RWI,ppt))

mean_cor<- rwi_ppt %>% 
  group_by(Provenance) %>% 
  summarise(mean=mean(cor), sd=sd(cor), se=sd(cor)/sqrt(n()))

ggplot(rwi_ppt,aes(x=factor(Provenance, levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance)), y=cor))+
  geom_boxplot()+
  geom_hline(yintercept = 0, color="black")+
  xlab("Provenance")+
  ylab("RWI by precip correlation")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#rwixppt cor vs. PC1 and 2
rwi_ppt_pcapts<- rwi_ppt %>% 
  left_join(prov_pcapts, by="Provenance") 

ggplot(rwi_ppt_pcapts,aes(x=factor(PC1), y=cor))+
  geom_boxplot()+
  geom_hline(yintercept = 0, color="black")+
  xlab("PC1")+
  ylab("RWI by precip correlation")+
  theme(axis.text.x = element_text(angle=45, hjust=1)) #no real pattern with PC1 and correlation between RWI and ppt


#look at site variability in ppt

ppt_cv<- ppt_comb_all %>% 
  filter(!is.na(ppt)) %>% 
  group_by(CN, year) %>% 
  summarise(total.ppt = sum(ppt, na.rm=T)) %>% 
  group_by(CN) %>% 
  summarise(min=min(year), max = max(year), cv=sd(total.ppt)/mean(total.ppt)) %>% 
  mutate(number=substr(CN,0,4)) %>% 
  left_join(prov_names) %>% 
  arrange(cv)

ggplot(mean_cor,aes(x=factor(Provenance, levels=ppt_cv$name), y=mean))+
  geom_point()+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se))+
  geom_hline(yintercept = 0, color="gray")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

rwi_by_cv <- rwi_ppt %>% 
  left_join(ppt_cv, by="Provenance")

mod_cv <- lm(cor~ cv , data=rwi_by_cv)
anova(mod_cv)


#rwi by fdsi

rwi_fdsi<- left_join(rwi,FDSI_raw, by=c("Year"="year")) %>% 
  filter(!is.na(RWI)) %>% 
  filter(!is.na(FDSI))

rwi_fdsi_cor <- rwi_fdsi %>% 
  group_by(Provenance,Tree) %>% 
  summarise(cor = cor(RWI,FDSI))

ggplot(rwi_fdsi_cor, aes(x=factor(Provenance, levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance)), y=cor))+
  geom_boxplot()+
  geom_hline(yintercept = 0, color="gray")+
  xlab("Provenance")+
  ylab("Correlation RWI x FDSI")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

rwi_fdsi_pcapts <- rwi_fdsi_cor %>% 
  left_join(pca_dist_df, by="Provenance")

ggplot(rwi_fdsi_pcapts,aes(x=factor(PC1), y=cor))+
  geom_boxplot()+
  geom_hline(yintercept = 0, color="black")+
  xlab("PC1")+
  ylab("RWI by FDSI correlation")+
  theme(axis.text.x = element_text(angle=45, hjust=1)) #no real pattern with PC1 and correlation between RWI and ppt

ggplot(rwi_fdsi_pcapts,aes(x=factor(dist.to.plant), y=cor))+
  geom_boxplot()+
  geom_hline(yintercept = 0, color="black")+
  xlab("PC1")+
  ylab("RWI by FDSI correlation")+
  theme(axis.text.x = element_text(angle=45, hjust=1)) #no real pattern with PC1 and correlation between RWI and ppt

# RWI and CWD
rwi_cwd<- left_join(rwi,plantation_cwd_annual, by=c("Year"="year")) %>% 
  filter(!is.na(RWI)) %>% 
  filter(!is.na(cwd_sum))

rwi_cwd_cor <- rwi_cwd %>% 
  group_by(Provenance,Tree) %>% 
  summarise(cor = cor(RWI,cwd_sum))

summary(rwi_fdsi_cor)
summary(rwi_ppt)
summary(rwi_cwd_cor)

rwi_ave <- rwi %>% 
  group_by(Year) %>% 
  filter(!is.na(RWI)) %>% 
  summarise(mean_rwi = mean(RWI), sd = sd(RWI), se= sd(RWI)/sqrt(n())) %>% 
  left_join(plantation_cwd_annual, by=c("Year"="year")) %>% 
  mutate(cwd_scaled = cwd_sum/100) %>% 
  pivot_longer(c(mean_rwi, cwd_scaled)) 

ggplot(rwi_ave, aes(x=Year, y=value, col=name))+
  geom_line()+
  geom_point()+
  geom_hline(yintercept = mean(rwi_ave %>% filter(name=="mean_rwi" & Year>1981) %>% pull(value)), col="blue")+
  geom_hline(yintercept = mean(rwi_ave %>% filter(name=="cwd_scaled") %>% pull(value)), col="red")

# CV of RWI alone
cv_rwi<- rwi %>% 
  filter(!is.na(RWI)) %>% 
  group_by(Tree, Provenance, Lat, Elevation, Source_temp, Source_ppt) %>%
  summarise(cv_rwi = sd(RWI) / mean(RWI) * 100) 
  
ggplot(cv_rwi, aes(x=factor(Provenance, levels=prov_pcapts %>% arrange(monsoonality) %>% pull(Provenance)), y=cv_rwi))+
  geom_boxplot()+
  geom_jitter(col="lightblue")+
  theme(axis.text.x = element_text(angle = 45, hjust=1))

```

##GLK

```{r}
rwi_simple<- rwi %>% 
  filter(!is.na(RWI)) %>% 
  select(Year, Tree, RWI) %>% 
  pivot_wider(id_cols=Year, names_from=Tree,values_from = RWI ) %>% 
  filter(Year > 1987 & Year < 2011) %>% 
  select(-Year) %>% as.rwl()
rownames(rwi_simple) <- seq(1988,2010)

glk(rwi_simple,
  overlap = 50, prob = TRUE)
```

##BAI

```{r}
bai_in <- bai.in(prov_all)
bai_out <- bai.out(prov_all)

bai_in_long<- as.data.frame(bai_in) %>%
  mutate(year = rownames(bai_in)) %>% 
  pivot_longer(!year, names_to = "tree", values_to = "bai") %>% 
  filter(!is.na(bai)) %>% 
  mutate(tree=paste("X",tree,sep = ""), year=as.integer(year)) %>% 
  left_join(rwi %>% dplyr::select(c(Tree, Provenance)) %>% unique(), by=c("tree" = "Tree"))

summary(bai_in_long)

ggplot(bai_in_long, aes(x=year, y=bai, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance, scales = "free")+
  theme(legend.position = "none")

bai_in_long %>% 
  filter(bai<10 & year > 2000) %>% View()

####### try using diameter #########
##### Ott et al., 2021 data (trees ~140 years old [30-40cm DBH]):
### average bark thickness = 3.9 +- 0.2 mm
### average phloem thickness = 5.7 +-0.2 mm
### total = 9.6mm

##### Pellegrini et al., 2017 data (trees ~10cm in diameter):
### average bark thickness = 3.99 mm

est_BT_cm = mean(c(9.6,4))/10

dbh %>% 
  select(Series,Provenance,DBH14) %>% 
  pull(DBH14) %>% 
  mean(na.rm=T)  #mean DBH is 14.7cm for our trees



diam14 <- dbh %>% 
  select(Series,Provenance,DBH14) %>% 
  mutate(inner_diam_mm = (DBH14-2*est_BT_cm)*10) %>% 
  select(Series, Provenance, inner_diam_mm)

diam14$Series == colnames(prov_all)

#calculate BAI with diameter
diam14_byseries<- prov_all %>% 
  pivot_longer(`32I2`:`47C2`) %>% 
  select(name) %>% 
  unique() %>% 
  left_join(diam14, by=c("name" = "Series")) %>% 
  select(-Provenance) %>% 
  rename(series = name, diam=inner_diam_mm)

c(diam14_byseries$series == colnames(prov_all)) %>% summary()

#bai_wdiam14 = bai.out(prov_all[-c(1:16,46,47),], diam= diam14_byseries)

sum(prov_all$`30B3`,na.rm=T)
diam14_byseries %>% filter(series=="30B3")
# 
# diam_data14 <- prov_good %>% 
#   mutate(year=rownames(prov_good)) %>% 
#   pivot_longer(`32I2`:`47C2`) %>% 
#   na.omit() %>% 
#   filter(year <2014) %>% 
#   group_by(name) %>% 
#   summarise(minyr = min(year), maxyr = max(year), n_yrs=n(), sum_rw=sum(value), diam_rw=sum(value)*2) %>% 
#   left_join(diam14, by=c("name" = "Series")) %>% 
#   mutate(innerdbh_minus_rw = (inner_diam_mm - diam_rw)/2) %>% 
#   left_join(dbh, by=c("name"="Series", "Provenance")) %>% 
#   mutate(dbh14_mm=DBH14*10) %>% 
#   mutate(outerdbh_minus_rw = (dbh14_mm - diam_rw)/2) %>% 
#   arrange(n_yrs)
# 
# ggplot()+
#   geom_point(data=diam_data14, aes(x=factor(name, levels=diam_data14$name), y=innerdbh_minus_rw, col=innerdbh_minus_rw>0))+
#   geom_hline(yintercept = 0)
# 
# ggplot()+
#   geom_point(data=diam_data14, aes(x=factor(name, levels=diam_data14$name), y=outerdbh_minus_rw, col=outerdbh_minus_rw>0))+
#   geom_hline(yintercept = 0)
#   
# ggplot()+
#   geom_point(data=diam_data14, aes(x=dbh14_mm, y=diam_rw))+
#   geom_abline(slope=1, intercept=0)
# 
# ggplot()+
#   geom_point(data=diam_data14, aes(x=inner_diam_mm, y=diam_rw))+
#   geom_abline(slope=1, intercept=0)
# 
# 
# ggplot(diam_data14, aes(x=n_yrs, y=outerdbh_minus_rw))+
#   geom_point()
# 
# ggplot(diam_data14, aes(x=sum_rw, y=dbh14_mm/2, col=n_yrs))+
#   geom_point()+
#   geom_abline(slope=1, intercept=0)
# 
# 
# diam_data14 %>% 
#   filter(outerdbh_minus_rw<0) %>% 
#   nrow()
# 
# diam_data14 %>% 
#   filter(outerdbh_minus_rw>0) %>% 
#   nrow()
# 
# diam_data14 %>% 
#   filter(n_yrs < 40) %>% 
#   filter(outerdbh_minus_rw<0) %>% 
#   nrow()
```

##Detrending

```{r}

#plot raw data to look at timeseries length
plot.rwl(prov_all)

##compare timing of when trees reached 30cm tall (and thus had a growth ring measured)
dbh_age <- prov_all %>% 
  as.data.frame() %>% 
  mutate(year = rownames(prov_all)) %>% 
  pivot_longer(!year, values_to = "rw", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(rwi %>% dplyr::select(Provenance, Tree) %>% unique(), by=c("tree"="Tree"))
  
dbh_age_summary <- dbh_age %>%
  filter(!is.na(rw)) %>% 
  group_by(Provenance,tree) %>% 
  summarise(minyr = min(year), maxyr=max(year), n=n()) %>% 
  mutate(years.calc = maxyr-minyr+1)

ggplot(dbh_age_summary, aes(x=factor(Provenance, levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance)), y=minyr))+
  geom_boxplot()+
  geom_point(color="maroon")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ggplot(dbh_age_summary, aes(x=Provenance, y=n))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

dbh_age_summary %>% 
  group_by(Provenance) %>% 
  summarise(n=n())

dbh_age_summary2 <- dbh_age_summary %>% 
  left_join(dbh %>% mutate(Series=paste("X",Series,sep="")), by=c("tree"="Series")) 

ggplot(dbh_age_summary2, aes(x=minyr, y=DBH14, col=Provenance.y))+
  geom_point()


###

prov_all_nona<- prov_all %>% na.omit()
colnames(prov_all_nona)


##raw
ggplot(dbh_age, aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

hist(dbh_age$rw)
View(dbh_age)
hist(dbh_age %>% filter(rw<0.5) %>% pull(rw))


dbh_age %>% group_by(Provenance) %>% 
  summarise(n=length(unique(tree))) 
dbh %>% arrange(Series) %>% 
  filter(!is.na(DBH14)) %>% group_by(Provenance) %>% 
  summarise(n=length(unique(Series))) 

dbh_rwi_comp <- dbh_age %>% 
  filter(!tree=="X32A1") %>% 
  group_by(Provenance, tree) %>% 
  summarise(sum=sum(rw, na.rm = TRUE)) %>% 
  arrange(tree) %>% 
  bind_cols(dbh %>% arrange(Series) %>% 
  filter(!is.na(DBH14))) %>% 
  mutate(lowsum=ifelse(sum<16,"yes","no"))


dbh_rwi_comp %>% 
  filter(lowsum=="yes")

ggplot(dbh_rwi_comp)+
  geom_point(aes(x=sum, y=DBH14, col=lowsum))

ggplot(dbh_rwi_comp %>% mutate(sum=ifelse(sum<15,sum*10,sum)))+
  geom_point(aes(x=sum, y=DBH14, col=lowsum))+
  geom_abline(slope=1/10,intercept = 0)

#find series that are likely off by an order of magnitude
off_provs<- dbh_age %>% 
  filter(Provenance %in% c("Cache NF","Coconino NF", "Cutting Permit 31", "Dixie NF", "Gunnison NF","Larimer 2", "Okanogan NF","Powers Creek","Wallowa-Whitman NF","Wenatchee NF"))

ggplot(off_provs, aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

off_trees<- dbh_rwi_comp %>% 
  filter(lowsum=="yes") %>% pull(tree) %>% c("X58A4") #this is the weird tree that's half and half

prov_good_nona <- prov_all_nona %>% select(-all_of(substr(off_trees, 2,nchar(off_trees))))

growth.detrended = matrix(nrow=nrow(prov_good_nona), ncol=length(colnames(prov_good_nona)))
for(i in 1:length(prov_good_nona)){
obj<- detrend.series(y = prov_all_nona %>% pull(colnames(prov_good_nona)[i]), y.name="growth", method="Spline")
growth.detrended[,i]<- obj
}
colnames(growth.detrended) = colnames(prov_good_nona)
growth.detrended.df <- growth.detrended %>% 
  as.data.frame() %>% 
  mutate(year = rownames(prov_good_nona)) %>% 
  pivot_longer(!year, values_to = "rw_spline", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(rwi %>% dplyr::select(Provenance, Tree) %>% unique(), by=c("tree"="Tree"))

ggplot(growth.detrended.df, aes(x=year, y=rw_spline, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance, scales = "free")+
  theme(legend.position = "none")

dbh_age_corrected <- dbh_age %>% 
  mutate(rw = ifelse(tree %in% off_trees, rw*10, rw))

ggplot(dbh_age_corrected, aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

ggplot(dbh_age %>% filter(tree=="X49D2"), aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

prov_good <- prov_all %>% as.data.frame() %>% 
  select(-all_of(off_trees %>% substr(2, nchar(off_trees))))

dbh_age_good <- prov_good %>% 
  as.data.frame() %>% 
  mutate(year = rownames(prov_all)) %>% 
  pivot_longer(!year, values_to = "rw", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(rwi %>% dplyr::select(Provenance, Tree) %>% unique(), by=c("tree"="Tree"))
  
ggplot(dbh_age_good, aes(x=year, y=rw, col=tree))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

ggplot(dbh_age_good, aes(x=year, y=rw, col=tree %in% c(dbh_age_summary %>% filter(maxyr<2016) %>% pull(tree))))+
  geom_line()+
  geom_point()+
  facet_wrap(~Provenance)+
  theme(legend.position = "bottom")

dbh_age_good %>% filter(tree %in% c(dbh_age_summary %>% filter(maxyr<2016) %>% pull(tree))) %>% 
  pull(tree) %>% 
  unique() %>% 
  length()

dbh_age_good %>% filter(!tree %in% c(dbh_age_summary %>% filter(maxyr<2016) %>% pull(tree))) %>% 
  pull(tree) %>% 
  unique() %>% 
  length()

meanrw<- dbh_age_good %>% 
  na.omit() %>% 
  group_by(year) %>% 
  summarise(meanrw=mean(rw), n=n()) 

ggplot(meanrw, aes(x=year, y=meanrw))+
  geom_point()

dbh_age_good %>%
  filter(tree %in% c(dbh_age_summary2 %>% filter(maxyr<2015) %>% pull(tree))) %>% 
  ggplot(aes(x=year,y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance)


dbh_age_good %>%
  filter(!tree %in% c(dbh_age_summary2 %>% filter(maxyr<2015) %>% pull(tree))) %>% 
  ggplot(aes(x=year,y=rw, col=tree))+
  geom_point()+
  geom_line()+
  xlim(c(1970,2015))+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

##########
##look at dbh vs. rw sum
full_join( dbh_age_good %>% select(tree) %>% unique(),
           dbh %>% 
             filter(!Series=="") %>% 
              mutate(tree=paste("X",Series,sep="")) %>% 
              filter(!tree %in% off_trees) %>% 
             select(tree) %>% unique()) == dbh_age_good %>% select(tree) %>% unique() 


dbh_rw <- dbh_age_good %>% 
  left_join(dbh %>% 
              mutate(tree=paste("X",Series,sep="")) %>% 
              filter(!tree %in% off_trees), by=c("tree","Provenance"))

dbh_rw %>% 
  filter(year==2006)
##########

##data from Kelsey et al. 2018

kelsey <- read.csv("EngelmannSpruce.csv")

kelsey$Site %>% unique()

ggplot(kelsey %>% filter(Site=="AL1"), aes(x=Year, y=RawGrowth_mm, col=Core_ID))+
  geom_point()+
  geom_line()

kelseyrwl<- kelsey %>% 
  pivot_wider(id_cols = c(Year), names_from = Core_ID, values_from = RawGrowth_mm) %>% 
  arrange(Year) %>% 
  tibble::column_to_rownames(var="Year")

row.names(kelseyrwl) = seq(1899,2012,1)

kelseyrwl*1000

#write.rwl(kelseyrwl*1000, "kelsey.rwl")

kelseyrwl2 <- read.rwl("kelsey.rwl")

bai_kelsey<- bai.out(kelseyrwl2)

bai_kelsey$al1es0

bai35A1 <- data.frame(bai = bai_out$`35A1`, year=seq(1970,2016,1), tree="35A1")

bai_comb <- data.frame(bai=bai_kelsey$al1es0, year=seq(1899,2012,1), tree="al1es05") %>% 
  bind_rows(bai35A1)

ggplot(bai_comb, aes(x=year, y=bai, col=tree))+
  geom_point()+
  geom_line()

ggplot(dbh_age_good %>% filter(Provenance=="Cutting Permit 31"), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()

ave_rw_prov<- dbh_age_good %>% 
  na.omit() %>% 
  group_by(Provenance, year) %>% 
  summarise(ave_rw=mean(rw), se=sd(rw)/sqrt(n())) 

ggplot(ave_rw_prov, aes(x=year, y=ave_rw, col=Provenance))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(x=year, ymin=ave_rw-se, ymax=ave_rw+se, col=Provenance))+
  facet_wrap(~Provenance)

ave_rw_all <- dbh_age_good %>%
  na.omit() %>% 
  group_by(year) %>% 
  summarise(ave_rw=mean(rw), se=sd(rw)/sqrt(n()))

ggplot(ave_rw_all, aes(x=year, y=ave_rw))+
  geom_point()+
  geom_errorbar(aes(x=year, ymin=ave_rw-se, ymax=ave_rw+se), col="red")+
  geom_line()


##data from https://doi.org/10.25921/zp2z-av44 - Engelmann spruce in Montana
mt105 <- read.rwl("mt105.rwl")


mt105_long <- mt105 %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column(var="year") %>%
  mutate(year=as.numeric(year)) %>% 
  pivot_longer(cols=`720011`:`720112`,names_to="tree", values_to="rw")

ggplot(mt105_long %>% filter(tree %in% seq(72011,720052,1)), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~tree)

```

```{r}
rw_clim_wide <- left_join(dbh_age_good, plantation_clim)
colnames(rw_clim_wide)

rw_clim_wide_formodel<- rw_clim_wide %>% select(colnames(rw_clim_wide)[c(2:4,6:27,32,37,38)])

tree_clim_cors <- rw_clim_wide%>% 
  left_join(bai_in_long) %>% 
  filter(!is.na(rw)) %>% 
  filter(!year>2015) %>% 
  pivot_longer(c(ppt_sm:vpdmax_sp,FDSI,aet_sum,cwd_sum)) %>% 
  group_by(tree,Provenance,name) %>% 
  summarise(cor_rw=cor(rw,value), cor_bai=cor(bai, value))

ggplot(tree_clim_cors, aes(x=Provenance, y=cor_rw))+
  geom_boxplot()+
  facet_wrap(~name, scales="free")+
  theme(axis.text.x = element_text(angle=45,hjust=1))

tree_clim_cors %>% 
  group_by(name) %>% 
  summarise(meancor_rw=mean(cor_rw,na.rm=TRUE), sd_rw=sd(cor_rw, na.rm=TRUE), meancor_bai=mean(cor_bai,na.rm=TRUE), sd_bai=sd(cor_bai, na.rm=TRUE)) %>% 
  dplyr::arrange(abs(meancor_bai)) %>% 
  print(n=25) ##summer VPD max has strongest correlation with ring width & summer AET has strongest correlation with BAI

tree_clim_cors %>% 
  filter(name == "vpdmax_sm") %>% 
  group_by(Provenance) %>% 
  summarise(meancor=mean(cor_rw,na.rm=TRUE), sd=sd(cor_rw, na.rm=TRUE)) %>% 
  dplyr::arrange(meancor) %>% 
  print(n=25) ##shows provenances with highest correlations between ring width and summer vpd max

ggplot(rw_clim_wide, aes(x=year, y=vpdmax_sm))+
  geom_point()
ggplot(rw_clim_wide, aes(x=year, y=cwd_sum))+
  geom_point()+
  geom_hline(yintercept=quantile(rw_clim_wide$cwd_sum, c(0.75))  + IQR(rw_clim_wide$cwd_sum)*1.5, col="red")

rw_clim_wide %>% summary()

quantile(rw_clim_wide$cwd_sum, c(0.025,0.5,0.975))
quantile(rw_clim_wide$cwd_sum, c(0.75))  + IQR(rw_clim_wide$cwd_sum)*1.5

rw_clim_wide %>% 
  dplyr::select(c("year","cwd_sum")) %>% 
  unique() %>% 
  filter(cwd_sum > quantile(rw_clim_wide$cwd_sum, c(0.75))  + IQR(rw_clim_wide$cwd_sum)*1.5)

rw_clim_wide %>% 
  filter(!is.na(rw)) %>% 
  group_by(year) %>% 
  summarise(n=n()) %>% print(n=50)
```

##SEA
```{r}
dbh_age_good #this is raw ring widths for only trees that don't have weird values.
prov_good #this is it in wide format

tree_ids <- colnames(prov_good)

rw.detrended = matrix(nrow=nrow(prov_good %>% slice(1:(n()-2))), ncol=length(tree_ids))
for(i in 1:length(tree_ids)){
obj<- detrend.series(y = prov_good %>% slice(1:(n()-2)) %>% pull(tree_ids[i]), y.name="rw_detrended", method="Spline")
rw.detrended[,i]<- obj
}
colnames(rw.detrended) = tree_ids

rw.detrend.df <- as.data.frame(rw.detrended) %>% 
  mutate(year = seq(1970,2014,1)) 

dtrw_clim_long <- rw.detrend.df %>% 
  mutate(fdsi = FDSI_raw %>% slice(1:(n()-4)) %>% pull(FDSI)) %>% 
  pivot_longer(`32I2`:`47C2`)

ggplot(dtrw_clim_long, aes(x=fdsi, y=value, col=name))+
  geom_point()+
  geom_smooth(method="lm")+
  theme(legend.position = "none")

ggplot(FDSI_raw, aes(x=year, y=FDSI))+
  geom_point()+
  geom_hline(yintercept=0)

mean(FDSI_raw$FDSI,na.rm=T) - 2*sd(FDSI_raw$FDSI,na.rm=T)

FDSI_raw %>% 
  filter(FDSI < mean(FDSI_raw$FDSI,na.rm=T) - 2*sd(FDSI_raw$FDSI,na.rm=T))

rw.detrend.df.filter <- rw.detrend.df %>%
  filter(year > 1990 & year <2011) %>% 
  tibble::column_to_rownames('year')

all.sea <- sea(rw.detrend.df.filter, key=c(2002), lag=5, resample=1000)
foo <- all.sea$se.unscaled
names(foo) <- all.sea$lag
barplot(foo, col = ifelse(all.sea$p < 0.05, "grey30", "grey75"), 
        ylab = "RWI", xlab = "Superposed Epoch")

fdsi.cor.df <- data.frame()
for(i in 1:ncol(rw.detrend.df.filter)){
correlation <- cor(FDSI_raw %>% filter(year > 1990 & year < 2011) %>% pull(FDSI), rw.detrend.df.filter[,i])
  fdsi.cor.df[i,1]<- correlation
}

fdsi.cor.df.pops <- fdsi.cor.df %>% 
  mutate(tree = colnames(rw.detrend.df.filter)) %>% 
  rename(corr = V1) %>% 
  left_join(dbh, by=c("tree"="Series"))
  
ggplot(fdsi.cor.df.pops, aes(x=Provenance,y=corr)) + 
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

corraov <- aov(corr ~ Provenance, data=fdsi.cor.df.pops)
summary(corraov)

provs <- unique(fdsi.cor.df.pops$Provenance)

sea.list<- list()
for(i in 1:length(provs)){
  provn <- rw.detrend.df %>% 
    select(c(year,fdsi.cor.df.pops %>% filter(Provenance == provs[i]) %>% pull(tree))) %>% 
    na.omit()
  
rownames(provn) = provn$year

provn_noyr = provn %>% select(-year)

temp.sea <- sea(provn_noyr, key=c(2002), lag=4, resample=1000)
  
sea.list[[i]]<- temp.sea
}

par(mfrow=c(5,4))
for(i in 1:length(sea.list)){
  plotdata<- sea.list[[i]]$se.unscaled
  names(plotdata) <- sea.list[[i]]$lag
  barplot(plotdata, col = ifelse(sea.list[[i]]$p < 0.05, "grey30", "grey75"), 
        ylab = "RWI", xlab = "Superposed Epoch", main=paste(provs[i]))
}

```


#Distance

```{r}
dbh_diffs_pcapts<- dbh_diffs %>% 
  mutate(Provenance = gsub(" NF","", Provenance)) %>% 
  mutate(Provenance = ifelse(Provenance == "Grand Mesa - Uncompahgre", "GM-U", Provenance)) %>% 
  pivot_longer(c(DBH91:DBH14,diff_total:diff1)) %>% 
  left_join(pca_dist_df %>% mutate(Provenance = gsub(" NF","", Provenance)) %>% 
  mutate(Provenance = ifelse(Provenance == "Grand Mesa - Uncompahgre", "GM-U", Provenance)), by=c("Provenance"))

ggplot(dbh_diffs_pcapts, aes(x=dist.to.plant, y=value))+
  geom_point()+
  facet_wrap(~name, scales="free")
```

#Resistance & Resilience

```{r}
rwi_RR <- rwi %>%
  mutate(Period=ifelse(Period=="","none",Period)) %>% 
  group_by(Tree, Provenance, Period, Lat, Elevation) %>% 
  summarise(mean_rwi=mean(RWI, na.rm=T)) 

  # pivot_wider(values_from=mean_rwi, names_from = Period) %>% 
  # mutate(resistance = During/Before, resilience = After/Before) %>% 
  # filter(!is.na(resistance))

ggplot(rwi_RR %>% filter(!Period=="none"), aes(x=factor(Provenance, levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance)), y=mean_rwi, fill=factor(Provenance, levels=prov_pcapts %>% arrange(Latitude) %>% pull(Provenance))))+
  geom_boxplot()+
  scale_fill_manual(values=viridis(20), name="Provenance (by Lat)")+
  facet_wrap(~factor(Period, levels=c("Before","During","After")))+
  theme(axis.text.x = element_text(angle=45, hjust=1))

n_trees <- rwi %>% 
  group_by(Provenance) %>% 
  summarise(n=length(unique(Tree)))
  
rwi_tree_edit<- rwi %>% 
  group_by(Provenance, Tree) %>% 
  summarise(n_years = n()) %>% 
  left_join(n_trees)

tree_colors<- c(rep(viridis(8),2),viridis(8)[1:7],rep(viridis(8),2),viridis(8)[1:6],viridis(8),rep(viridis(8)[1:7],2), rep(viridis(8),5), viridis(8)[1:7], rep(viridis(8),4), viridis(8)[1:6])

tree_colors<- c(rep(brewer.pal(8,"Dark2"),2),brewer.pal(8,"Dark2")[1:7],rep(brewer.pal(8,"Dark2"),2),brewer.pal(8,"Dark2")[1:6],brewer.pal(8,"Dark2"),rep(brewer.pal(8,"Dark2")[1:7],2), rep(brewer.pal(8,"Dark2"),5), brewer.pal(8,"Dark2")[1:7], rep(brewer.pal(8,"Dark2"),4), brewer.pal(8,"Dark2")[1:6])

ggplot(rwi, aes(x=Year, y=RWI, col=Tree))+
    geom_rect(aes(xmin=2005,xmax=2009,ymin=-Inf, ymax=Inf), fill="darkgrey", color="black", alpha=0.2)+
    geom_rect(aes(xmin=2000,xmax=2004,ymin=-Inf, ymax=Inf), fill="lightgrey", color="black", alpha=0.2)+
    geom_rect(aes(xmin=1995,xmax=1999,ymin=-Inf, ymax=Inf), fill="white", color="black", alpha=0.2)+
  geom_point()+
  geom_line()+
  scale_color_manual(values=tree_colors)+
  facet_wrap(~Provenance, scales="free")+
  theme(legend.position = "none")
  

as.data.frame(provenances) %>% 
  filter(ident %in% c(tmax_comb_all %>% 
  filter(is.na(tmax)) %>% pull(CN) %>% unique()))
  
##compare average RWI in different time periods
rwi_periods<- rwi %>% 
  mutate(Period = ifelse(Year < 1995, "Baseline", Period)) %>% 
  group_by(Period, Provenance) %>% 
  filter(!Period=="")
  
ggplot(rwi_periods, aes(x=factor(Period, levels=c("Baseline","Before","During","After","")), y=RWI))+
  geom_boxplot()+
  facet_wrap(~Provenance, scales="free")

period_model <- lm(RWI ~ Provenance*factor(Period, levels=c("Baseline","Before","During","After","")), data=rwi_periods)
anova(period_model)
summary(period_model) #only significant differences between average RWI are between baseline and before period for Inlet creek (increase in before period) & Gila (decrease in before peiod)
```


#Raw vs. Detrended

```{r}
#do same analysis as Prolic but look at difference between detrending methods.


##raw ring widths
ggplot(data=dbh_age_good %>% filter(year>1994 & year<2010), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

#average by provenance
ggplot(data=dbh_age_good %>% group_by(Provenance,year) %>% summarise(rw=mean(rw,na.rm=T)), aes(x=year, y=rw, col=Provenance))+
  geom_point()+
  geom_line()+
  theme(legend.position = "none")

ggplot(data=rwi %>% group_by(Provenance,Year) %>% summarise(rwi=mean(RWI,na.rm=T)), aes(x=Year, y=rwi, col=Provenance))+
  geom_point()+
  geom_line()+
  theme(legend.position = "none")
##

drought_rw<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1999 & year < 2005) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1994 & year < 2000) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 2004 & year < 2010) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs <- left_join(drought_rw,predrought_rw) %>% left_join(postdrought_rw) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

raw_aov_resist <- aov(resistance ~ Provenance, data=raw_calcs)
summary(raw_aov_resist)
raw_aov_resil <- aov(resilience ~ Provenance, data=raw_calcs)
summary(raw_aov_resil)
TukeyHSD(raw_aov_resil)
TukeyHSD(raw_aov_resil)$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)


ggplot(raw_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("raw")
ggplot(raw_calcs, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("raw")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


####


##linear ring widths
ggplot(data=rwi %>% filter(! Tree %in% off_trees) %>% filter(!Tree%in% c("X30L4","X58A4")), aes(x=Year, y=RWI, col=Tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance, scales="free")+
  theme(legend.position = "none")


drought_rw_linear<- rwi %>% 
  filter(! Tree %in% off_trees) %>% 
    filter(!Tree=="X30L4") %>% ##excluding Gila tree that has a super high growth ring in 2009
  filter(Year > 1999 & Year < 2005) %>% 
  group_by(Tree) %>% 
  summarise(drought_ave_rw_linear = mean(RWI))

predrought_rw_linear<-  rwi %>% 
    filter(! Tree %in% off_trees) %>% 
    filter(!Tree=="X30L4") %>% 
  filter(Year > 1994 & Year < 2000) %>% 
  group_by(Tree) %>% 
  summarise(predrought_ave_rw_linear = mean(RWI))

postdrought_rw_linear<-  rwi %>% 
    filter(! Tree %in% off_trees) %>% 
  filter(!Tree=="X30L4") %>% 
  filter(Year > 2004 & Year < 2010) %>% 
  group_by(Tree) %>% 
  summarise(postdrought_ave_rw_linear = mean(RWI))

linear_calcs <- left_join(drought_rw_linear,predrought_rw_linear) %>% left_join(postdrought_rw_linear) %>% 
  mutate(resistance = drought_ave_rw_linear/predrought_ave_rw_linear, resilience = postdrought_ave_rw_linear/predrought_ave_rw_linear) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("Tree" = "tree"))

linear_aov_resist <- aov(resistance ~ Provenance, data=linear_calcs)
summary(linear_aov_resist)
TukeyHSD(linear_aov_resist)
TukeyHSD(linear_aov_resist)$Provenance %>% as.data.frame() %>%  filter(`p adj` <0.05)
linear_aov_resil <- aov(resilience ~ Provenance, data=linear_calcs)
summary(linear_aov_resil)
TukeyHSD(linear_aov_resil)$Provenance %>% as.data.frame() %>%  filter(`p adj` <0.05)

ggplot(linear_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("linear")+
  theme(axis.text.x = element_text(angle=45, hjust=1))
ggplot(linear_calcs, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("linear")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

###negative exponential detrending with dplr
prov_good_nona <- prov_all_nona %>% select(-all_of(substr(off_trees, 2,nchar(off_trees))))

growth.detrended.ne = matrix(nrow=nrow(prov_good_nona), ncol=length(colnames(prov_good_nona)))
for(i in 1:length(prov_good_nona)){
obj<- detrend.series(y = prov_good_nona %>% pull(colnames(prov_good_nona)[i]), y.name="growth", method="ModNegExp")
growth.detrended.ne[,i]<- obj
}
colnames(growth.detrended.ne) = colnames(prov_good_nona)
growth.detrended.ne.df <- growth.detrended.ne %>% 
  as.data.frame() %>% 
  mutate(year = rownames(prov_good_nona)) %>% 
  pivot_longer(!year, values_to = "rw_spline", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(rwi %>% dplyr::select(Provenance, Tree) %>% unique(), by=c("tree"="Tree"))

ggplot(data=growth.detrended.ne.df %>% filter(year>1994 & year < 2010) %>% filter(! tree %in% off_trees), aes(x=year, y=rw_spline, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

drought_rw_ne<- growth.detrended.ne.df %>% 
  filter(! tree %in% off_trees) %>% 
  filter(year > 1999 & year < 2005) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw_ne = mean(rw_spline))

predrought_rw_ne<-  growth.detrended.ne.df %>% 
    filter(! tree %in% off_trees) %>% 
  filter(year > 1994 & year < 2000) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw_ne = mean(rw_spline))

postdrought_rw_ne<-  growth.detrended.ne.df %>% 
    filter(! tree %in% off_trees) %>% 
  filter(year > 2004 & year < 2010) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw_ne = mean(rw_spline))

ne_calcs <- left_join(drought_rw_ne,predrought_rw_ne) %>% left_join(postdrought_rw_ne) %>% 
  mutate(resistance = drought_ave_rw_ne/predrought_ave_rw_ne, resilience = postdrought_ave_rw_ne/predrought_ave_rw_ne) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("tree" = "tree"))

ne_aov_resist <- aov(resistance ~ Provenance, data=ne_calcs)
summary(ne_aov_resist)

ne_aov_resil <- aov(resilience ~ Provenance, data=ne_calcs)
summary(ne_aov_resil)
TukeyHSD(ne_aov_resil)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)

ggplot(ne_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("ne")+
  theme(axis.text.x = element_text(angle=45, hjust=1))
ggplot(ne_calcs, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("ne")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


###age dependent spline detrending with dplr

growth.detrended.ads = matrix(nrow=nrow(prov_good_nona), ncol=length(colnames(prov_good_nona)))
for(i in 1:length(prov_good_nona)){
obj<- detrend.series(y = prov_good_nona %>% pull(colnames(prov_good_nona)[i]), y.name="growth", method="AgeDepSpline", nyrs=100)
growth.detrended.ads[,i]<- obj
}

colnames(growth.detrended.ads) = colnames(prov_good_nona)
growth.detrended.ads.df <- growth.detrended.ads %>% 
  as.data.frame() %>% 
  mutate(year = rownames(prov_good_nona)) %>% 
  pivot_longer(!year, values_to = "rw_spline", names_to="tree") %>% 
  mutate(tree=paste("X",tree,sep=""), year=as.integer(year)) %>% 
  left_join(rwi %>% dplyr::select(Provenance, Tree) %>% unique(), by=c("tree"="Tree"))

ggplot(data=growth.detrended.ads.df %>% filter(year>1994 & year < 2010) %>% filter(! tree %in% off_trees), aes(x=year, y=rw_spline, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")

drought_rw_ads<- growth.detrended.ads.df %>% 
  filter(! tree %in% off_trees) %>% 
  filter(year > 1999 & year < 2005) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw_ads = mean(rw_spline))

predrought_rw_ads<-  growth.detrended.ads.df %>% 
    filter(! tree %in% off_trees) %>% 
  filter(year > 1994 & year < 2000) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw_ads = mean(rw_spline))

postdrought_rw_ads<-  growth.detrended.ads.df %>% 
    filter(! tree %in% off_trees) %>% 
  filter(year > 2004 & year < 2010) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw_ads = mean(rw_spline))

ads_calcs <- left_join(drought_rw_ads,predrought_rw_ads) %>% left_join(postdrought_rw_ads) %>% 
  mutate(resistance = drought_ave_rw_ads/predrought_ave_rw_ads, resilience = postdrought_ave_rw_ads/predrought_ave_rw_ads) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("tree" = "tree"))

ads_aov_resist <- aov(resistance ~ Provenance, data=ads_calcs)
summary(ads_aov_resist)

ads_aov_resil <- aov(resilience ~ Provenance, data=ads_calcs)
summary(ads_aov_resil)
TukeyHSD(ads_aov_resil)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)

ggplot(ads_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("ads")+
  theme(axis.text.x = element_text(angle=45, hjust=1))
ggplot(ads_calcs, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("ads")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


####

### spline 
ggplot(data=growth.detrended.df %>% filter(year>1994 & year < 2010) %>% filter(! tree %in% off_trees), aes(x=year, y=rw_spline, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance)+
  theme(legend.position = "none")


drought_rw_spline<- growth.detrended.df %>% 
  filter(! tree %in% off_trees) %>% 
  filter(year > 1999 & year < 2005) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw_spline = mean(rw_spline))

predrought_rw_spline<-  growth.detrended.df %>% 
    filter(! tree %in% off_trees) %>% 
  filter(year > 1994 & year < 2000) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw_spline = mean(rw_spline))

postdrought_rw_spline<-  growth.detrended.df %>% 
    filter(! tree %in% off_trees) %>% 
  filter(year > 2004 & year < 2010) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw_spline = mean(rw_spline))

spline_calcs <- left_join(drought_rw_spline,predrought_rw_spline) %>% left_join(postdrought_rw_spline) %>% 
  mutate(resistance = drought_ave_rw_spline/predrought_ave_rw_spline, resilience = postdrought_ave_rw_spline/predrought_ave_rw_spline) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("tree" = "tree"))

spline_aov_resist <- aov(resistance ~ Provenance, data=spline_calcs)
summary(spline_aov_resist)

spline_aov_resil <- aov(resilience ~ Provenance, data=spline_calcs)
summary(spline_aov_resil)
TukeyHSD(spline_aov_resil)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)
##now Gila is not an outlier in terms of resilience. Inlet Creek is less than Gila and Cache.

ggplot(spline_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("spline")+
  theme(axis.text.x = element_text(angle=45, hjust=1))
ggplot(spline_calcs, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("spline")+
  theme(axis.text.x = element_text(angle=45, hjust=1))


##need to test different time periods for pre, post, and drought periods. 
```

##Different times

```{r}
###############
## identify drought year
###############
unique(plantation_clim_long_qs$name)

plantation_clim_xtremes<- plantation_clim_long_qs %>% 
  mutate(extreme = ifelse(name %in% c("ppt_sm","ppt_gs","ppt_wt","ppt_fa","ppt_sp","ppt","FDSI","aet") & value < out.low, "yes",
                          ifelse(name %in% c("value_sm_tmax","value_sm_tmean","value_sm_tmin","value_fa_tmax","value_fa_tmean","value_fa_tmin","value_wt_tmax","value_wt_tmean","value_wt_tmin","value_sp_tmax","value_sp_tmean","value_sp_tmin","vpdmax_sm","vpdmax_fa","vpdmax_wt","vpdmax_sp","cwd_sum","cwd_wy","spei_sum") & value > out.hi, "yes", "no" 
  ))) %>% 
  filter(extreme=="yes")

View(plantation_clim_xtremes)

plantation_clim_xtremes %>% 
  group_by(year) %>% 
  summarise(n=n()) ##2002 has the highest # of climate vars outside the extreme.


#######
# calculate different time periods
#######
droughtyear = 2002
buffertime = seq(0,3,1)
raw_calcs_list<- list()
for(i in 1:length(buffertime)){
drought_rw<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_list[[i]] <- left_join(drought_rw,predrought_rw) %>% left_join(postdrought_rw) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))
}

rawmodlist_resistance<- list()
for(i in 1:length(raw_calcs_list)){
rawmodlist_resistance[[i]] <- aov(resistance ~ Provenance, data=raw_calcs_list[[i]])
}
summary(rawmodlist_resistance[[1]])
summary(rawmodlist_resistance[[2]]) #significant
summary(rawmodlist_resistance[[3]])
summary(rawmodlist_resistance[[4]]) 

rawmodlist_resilience<- list()
for(i in 1:length(raw_calcs_list)){
rawmodlist_resilience[[i]] <- aov(resilience ~ Provenance, data=raw_calcs_list[[i]])
}
summary(rawmodlist_resilience[[1]])
summary(rawmodlist_resilience[[2]]) ##3 year periods marginally significant
TukeyHSD(rawmodlist_resilience[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
summary(rawmodlist_resilience[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(rawmodlist_resilience[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
RR_5yrs_0004 <- raw_calcs_list[[3]] %>% as.data.frame()
ggplot(RR_5yrs_0004, aes(x=Provenance, y=resilience))+
  geom_boxplot()
summary(rawmodlist_resilience[[4]]) 

####
## even time periods
####
#01-02 - 2 years, marginally significant for resistance

drought_rw_0102<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2001 & year <= 2002) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_0102<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1999 & year <= 2000) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw_0102<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2003 & year <= 2004) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0102 <- left_join(drought_rw_0102,predrought_rw_0102) %>% left_join(postdrought_rw_0102) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance_0102 <- aov(resistance ~ Provenance, data=raw_calcs_0102)

summary(rawmodlist_resistance_0102)
TukeyHSD(rawmodlist_resistance_0102)$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)

rawmodlist_resilience_0102 <- aov(resilience ~ Provenance, data=raw_calcs_0102)

summary(rawmodlist_resilience_0102)

#02-03 - 2 years, not significant

drought_rw_0203<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2002 & year <= 2003) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_0203<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2000 & year <= 2001) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw_0203<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2004 & year <= 2005) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0203 <- left_join(drought_rw_0203,predrought_rw_0203) %>% left_join(postdrought_rw_0203) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance_0203 <- aov(resistance ~ Provenance, data=raw_calcs_0203)

summary(rawmodlist_resistance_0203)

rawmodlist_resilience_0203 <- aov(resilience ~ Provenance, data=raw_calcs_0203)

summary(rawmodlist_resilience_0203)

#01-04 - 4 years, significant resilience only

drought_rw_0104<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2001 & year <= 2004) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_0104<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1997 & year <= 2000) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw_0104<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2005 & year <= 2008) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0104 <- left_join(drought_rw_0104,predrought_rw_0104) %>% left_join(postdrought_rw_0104) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance_0104 <- aov(resistance ~ Provenance, data=raw_calcs_0104)

summary(rawmodlist_resistance_0104)

rawmodlist_resilience_0104 <- aov(resilience ~ Provenance, data=raw_calcs_0104)

summary(rawmodlist_resilience_0104)
TukeyHSD(rawmodlist_resilience_0104)$Provenance %>% as.data.frame() %>% filter(`p adj`<0.05)
RR_4yrs_0104 <- raw_calcs_0104 %>% as.data.frame()
ggplot(RR_4yrs_0104, aes(x=Provenance, y=resilience))+
  geom_boxplot()

#00-03 - 4 years, significant reslience only 

drought_rw_0003<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2000 & year <= 2003) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_0003<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1996 & year <= 1999) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw_0003<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2004 & year <= 2007) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0003 <- left_join(drought_rw_0003,predrought_rw_0003) %>% left_join(postdrought_rw_0003) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

rawmodlist_resistance_0003 <- aov(resistance ~ Provenance, data=raw_calcs_0003)

summary(rawmodlist_resistance_0003)

rawmodlist_resilience_0003 <- aov(resilience ~ Provenance, data=raw_calcs_0003)

summary(rawmodlist_resilience_0003)
TukeyHSD(rawmodlist_resilience_0003)$Provenance %>% as.data.frame() %>% filter(`p adj`<0.05)
RR_4yrs_0003 <- raw_calcs_0003 %>% as.data.frame()
ggplot(RR_4yrs_0003, aes(x=Provenance, y=resilience))+
  geom_boxplot()


#00-05 - 6 years not significant for either resistance or resilience

drought_rw_0005<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2000 & year <= 2005) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_0005<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1994 & year <= 1999) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw_0005<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2006 & year <= 2011) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0005 <- left_join(drought_rw_0005,predrought_rw_0005) %>% left_join(postdrought_rw_0005) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance_0005 <- aov(resistance ~ Provenance, data=raw_calcs_0005)

summary(rawmodlist_resistance_0005)

rawmodlist_resilience_0005 <- aov(resilience ~ Provenance, data=raw_calcs_0005)

summary(rawmodlist_resilience_0005)

#99-04 - 6 years not significant for either resistance or resilience

drought_rw_9904<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1999 & year <= 2004) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_9904<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1993 & year <= 1998) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw_9904<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2005 & year <= 2010) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_9904 <- left_join(drought_rw_9904,predrought_rw_9904) %>% left_join(postdrought_rw_9904) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance_9904 <- aov(resistance ~ Provenance, data=raw_calcs_9904)

summary(rawmodlist_resistance_9904)

rawmodlist_resilience_9904 <- aov(resilience ~ Provenance, data=raw_calcs_9904)

summary(rawmodlist_resilience_9904)

################################
################################

# calculate different time periods for other detrending methods
#######
#ne
droughtyear = 2002
buffertime = seq(0,3,1)
ne_calcs_list<- list()
for(i in 1:length(buffertime)){
drought_rw<- growth.detrended.ne.df %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw = mean(rw_spline))

predrought_rw<- growth.detrended.ne.df %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw = mean(rw_spline))

postdrought_rw<- growth.detrended.ne.df %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw = mean(rw_spline))

ne_calcs_list[[i]] <- left_join(drought_rw,predrought_rw) %>% left_join(postdrought_rw) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")
}

nemodlist_resistance<- list()
for(i in 1:length(ne_calcs_list)){
nemodlist_resistance[[i]] <- aov(resistance ~ Provenance, data=ne_calcs_list[[i]])
}
summary(nemodlist_resistance[[1]])
summary(nemodlist_resistance[[2]]) #significant
TukeyHSD(nemodlist_resistance[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)
summary(nemodlist_resistance[[3]])
summary(nemodlist_resistance[[4]]) 

nemodlist_resilience<- list()
for(i in 1:length(ne_calcs_list)){
nemodlist_resilience[[i]] <- aov(resilience ~ Provenance, data=ne_calcs_list[[i]])
}
summary(nemodlist_resilience[[1]])
summary(nemodlist_resilience[[2]]) #significant
TukeyHSD(nemodlist_resilience[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
summary(nemodlist_resilience[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(nemodlist_resilience[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
ggplot(as.data.frame(ne_calcs_list[[3]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))
summary(nemodlist_resilience[[4]]) #significant
TukeyHSD(nemodlist_resilience[[4]])

#ads
droughtyear = 2002
buffertime = seq(0,3,1)
ads_calcs_list<- list()
for(i in 1:length(buffertime)){
drought_rw<- growth.detrended.ads.df %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw = mean(rw_spline))

predrought_rw<- growth.detrended.ads.df %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw = mean(rw_spline))

postdrought_rw<- growth.detrended.ads.df %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw = mean(rw_spline))

ads_calcs_list[[i]] <- left_join(drought_rw,predrought_rw) %>% left_join(postdrought_rw) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")
}

adsmodlist_resistance<- list()
for(i in 1:length(ads_calcs_list)){
adsmodlist_resistance[[i]] <- aov(resistance ~ Provenance, data=ads_calcs_list[[i]])
}
summary(adsmodlist_resistance[[1]])
summary(adsmodlist_resistance[[2]]) #significant
summary(adsmodlist_resistance[[3]])
summary(adsmodlist_resistance[[4]]) 

adsmodlist_resilience<- list()
for(i in 1:length(ads_calcs_list)){
adsmodlist_resilience[[i]] <- aov(resilience ~ Provenance, data=ads_calcs_list[[i]])
}
summary(adsmodlist_resilience[[1]])
summary(adsmodlist_resilience[[2]]) #significant
TukeyHSD(adsmodlist_resilience[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
summary(adsmodlist_resilience[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(adsmodlist_resilience[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
ggplot(as.data.frame(ads_calcs_list[[3]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))
summary(adsmodlist_resilience[[4]]) #significant
TukeyHSD(adsmodlist_resilience[[4]])$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)
ggplot(as.data.frame(ads_calcs_list[[4]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))


#spline
droughtyear = 2002
buffertime = seq(0,3,1)
spline_calcs_list<- list()
for(i in 1:length(buffertime)){
drought_rw<- growth.detrended.df %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw = mean(rw_spline))

predrought_rw<- growth.detrended.df %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw = mean(rw_spline))

postdrought_rw<- growth.detrended.df %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw = mean(rw_spline))

spline_calcs_list[[i]] <- left_join(drought_rw,predrought_rw) %>% left_join(postdrought_rw) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")
}

splinemodlist_resistance<- list()
for(i in 1:length(spline_calcs_list)){
splinemodlist_resistance[[i]] <- aov(resistance ~ Provenance, data=spline_calcs_list[[i]])
}
summary(splinemodlist_resistance[[1]])
summary(splinemodlist_resistance[[2]]) #significant
summary(splinemodlist_resistance[[3]])
summary(splinemodlist_resistance[[4]]) 

splinemodlist_resilience<- list()
for(i in 1:length(spline_calcs_list)){
splinemodlist_resilience[[i]] <- aov(resilience ~ Provenance, data=spline_calcs_list[[i]])
}
summary(splinemodlist_resilience[[1]])
summary(splinemodlist_resilience[[2]]) 
summary(splinemodlist_resilience[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(splinemodlist_resilience[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
ggplot(as.data.frame(spline_calcs_list[[3]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))
summary(splinemodlist_resilience[[4]]) 

```

##2003

```{r}
#######
# calculate different time periods
#######
droughtyear = 2003
buffertime = seq(0,3,1)
raw_calcs_list03<- list()
for(i in 1:length(buffertime)){
drought_rw03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_list03[[i]] <- left_join(drought_rw03,predrought_rw03) %>% left_join(postdrought_rw03) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))
}

rawmodlist_resistance03<- list()
for(i in 1:length(raw_calcs_list03)){
rawmodlist_resistance03[[i]] <- aov(resistance ~ Provenance, data=raw_calcs_list03[[i]])
}
summary(rawmodlist_resistance03[[1]])
summary(rawmodlist_resistance03[[2]]) 
summary(rawmodlist_resistance03[[3]])
summary(rawmodlist_resistance03[[4]]) 

rawmodlist_resilience03<- list()
for(i in 1:length(raw_calcs_list03)){
rawmodlist_resilience03[[i]] <- aov(resilience ~ Provenance, data=raw_calcs_list03[[i]])
}
summary(rawmodlist_resilience03[[1]])
summary(rawmodlist_resilience03[[2]]) ##3 year periods  significant
TukeyHSD(rawmodlist_resilience03[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
summary(rawmodlist_resilience03[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(rawmodlist_resilience03[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
RR_5yrs_0105 <- raw_calcs_list03[[3]] %>% as.data.frame()
ggplot(RR_5yrs_0105, aes(x=Provenance, y=resilience))+
  geom_boxplot()
summary(rawmodlist_resilience03[[4]]) 

####
## even time periods
####
#02-03 - 2 years, not significant

drought_rw_0203<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2002 & year <= 2003) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03_0203<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2000 & year <= 2001) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03_0203<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2004 & year <= 2005) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0203 <- left_join(drought_rw_0203,predrought_rw03_0203) %>% left_join(postdrought_rw03_0203) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance03_0203 <- aov(resistance ~ Provenance, data=raw_calcs_0203)

summary(rawmodlist_resistance03_0203)

rawmodlist_resilience03_0203 <- aov(resilience ~ Provenance, data=raw_calcs_0203)

summary(rawmodlist_resilience03_0203)

#03-04 - 2 years, marginally significant resilience

drought_rw_0304<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2003 & year <= 2004) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03_0304<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2001 & year <= 2002) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03_0304<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2005 & year <= 2006) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0304 <- left_join(drought_rw_0304,predrought_rw03_0304) %>% left_join(postdrought_rw03_0304) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance03_0304 <- aov(resistance ~ Provenance, data=raw_calcs_0304)

summary(rawmodlist_resistance03_0304)

rawmodlist_resilience03_0304 <- aov(resilience ~ Provenance, data=raw_calcs_0304)

summary(rawmodlist_resilience03_0304)
TukeyHSD(rawmodlist_resilience03_0304)$Provenance %>% as.data.frame %>% filter(`p adj` < 0.05)

#02-05 - 4 years, significant resilience & resistance 

drought_rw_0205<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2002 & year <= 2005) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03_0205<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1998 & year <= 2001) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03_0205<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2006 & year <= 2009) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0205 <- left_join(drought_rw_0205,predrought_rw03_0205) %>% left_join(postdrought_rw03_0205) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance03_0205 <- aov(resistance ~ Provenance, data=raw_calcs_0205)

summary(rawmodlist_resistance03_0205) #significant
TukeyHSD(rawmodlist_resistance03_0205)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)

rawmodlist_resilience03_0205 <- aov(resilience ~ Provenance, data=raw_calcs_0205)

summary(rawmodlist_resilience03_0205)
TukeyHSD(rawmodlist_resilience03_0205)$Provenance %>% as.data.frame() %>% filter(`p adj`<0.05)
RR_4yrs_0205 <- raw_calcs_0205 %>% as.data.frame()
ggplot(RR_4yrs_0205, aes(x=Provenance, y=resilience))+
  geom_boxplot()

#01-04 - 4 years, significant resilience only 

drought_rw_0104<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2001 & year <= 2004) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03_0104<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1997 & year <= 2000) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03_0104<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2005 & year <= 2008) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0104 <- left_join(drought_rw_0104,predrought_rw03_0104) %>% left_join(postdrought_rw03_0104) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

rawmodlist_resistance03_0104 <- aov(resistance ~ Provenance, data=raw_calcs_0104)

summary(rawmodlist_resistance03_0104)

rawmodlist_resilience03_0104 <- aov(resilience ~ Provenance, data=raw_calcs_0104)

summary(rawmodlist_resilience03_0104)
TukeyHSD(rawmodlist_resilience03_0104)$Provenance %>% as.data.frame() %>% filter(`p adj`<0.05)
RR_4yrs_0104 <- raw_calcs_0104 %>% as.data.frame()
ggplot(RR_4yrs_0104, aes(x=Provenance, y=resilience))+
  geom_boxplot()


#00-05 - 6 years not significant for either resistance or resilience

drought_rw_0005<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2000 & year <= 2005) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03_0005<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1994 & year <= 1999) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03_0005<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2006 & year <= 2011) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0005 <- left_join(drought_rw_0005,predrought_rw03_0005) %>% left_join(postdrought_rw03_0005) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance03_0005 <- aov(resistance ~ Provenance, data=raw_calcs_0005)

summary(rawmodlist_resistance03_0005)

rawmodlist_resilience03_0005 <- aov(resilience ~ Provenance, data=raw_calcs_0005)

summary(rawmodlist_resilience03_0005)

#01-06 - 6 years 

drought_rw_0106<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2001 & year <= 2006) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw03_0106<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 1995 & year <= 2000) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought_rw03_0106<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year >= 2007 & year <= 2012) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_0106 <- left_join(drought_rw_0106,predrought_rw03_0106) %>% left_join(postdrought_rw03_0106) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


rawmodlist_resistance03_0106 <- aov(resistance ~ Provenance, data=raw_calcs_0106)

summary(rawmodlist_resistance03_0106)

rawmodlist_resilience03_0106 <- aov(resilience ~ Provenance, data=raw_calcs_0106)

summary(rawmodlist_resilience03_0106)

################################
################################

# calculate different time periods for other detrending methods
#######
#ne
droughtyear = 2003
buffertime = seq(0,3,1)
ne_calcs_list03<- list()
for(i in 1:length(buffertime)){
drought_rw03<- growth.detrended.ne.df %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw = mean(rw_spline))

predrought_rw03<- growth.detrended.ne.df %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw = mean(rw_spline))

postdrought_rw03<- growth.detrended.ne.df %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw = mean(rw_spline))

ne_calcs_list03[[i]] <- left_join(drought_rw03,predrought_rw03) %>% left_join(postdrought_rw03) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")
}

nemodlist_resistance03<- list()
for(i in 1:length(ne_calcs_list03)){
nemodlist_resistance03[[i]] <- aov(resistance ~ Provenance, data=ne_calcs_list03[[i]])
}
summary(nemodlist_resistance03[[1]])
summary(nemodlist_resistance03[[2]]) 
summary(nemodlist_resistance03[[3]]) #significant
TukeyHSD(nemodlist_resistance03[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)
summary(nemodlist_resistance03[[4]]) 

nemodlist_resilience03<- list()
for(i in 1:length(ne_calcs_list03)){
nemodlist_resilience03[[i]] <- aov(resilience ~ Provenance, data=ne_calcs_list03[[i]])
}
summary(nemodlist_resilience03[[1]])
summary(nemodlist_resilience03[[2]]) #significant
TukeyHSD(nemodlist_resilience03[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
summary(nemodlist_resilience03[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(nemodlist_resilience03[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
ggplot(as.data.frame(ne_calcs_list03[[3]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))
summary(nemodlist_resilience03[[4]]) #significant
TukeyHSD(nemodlist_resilience03[[4]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)

#ads
droughtyear = 2003
buffertime = seq(0,3,1)
ads_calcs_list03<- list()
for(i in 1:length(buffertime)){
drought_rw03<- growth.detrended.ads.df %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw = mean(rw_spline))

predrought_rw03<- growth.detrended.ads.df %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw = mean(rw_spline))

postdrought_rw03<- growth.detrended.ads.df %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw = mean(rw_spline))

ads_calcs_list03[[i]] <- left_join(drought_rw03,predrought_rw03) %>% left_join(postdrought_rw03) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")
}

adsmodlist_resistance03<- list()
for(i in 1:length(ads_calcs_list03)){
adsmodlist_resistance03[[i]] <- aov(resistance ~ Provenance, data=ads_calcs_list03[[i]])
}
summary(adsmodlist_resistance03[[1]])
summary(adsmodlist_resistance03[[2]]) 
summary(adsmodlist_resistance03[[3]]) #significant
summary(adsmodlist_resistance03[[4]]) 

adsmodlist_resilience03<- list()
for(i in 1:length(ads_calcs_list03)){
adsmodlist_resilience03[[i]] <- aov(resilience ~ Provenance, data=ads_calcs_list03[[i]])
}
summary(adsmodlist_resilience03[[1]])
summary(adsmodlist_resilience03[[2]]) #significant
TukeyHSD(adsmodlist_resilience03[[2]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
summary(adsmodlist_resilience03[[3]]) ##5 year periods is significant (p < 0.05)
TukeyHSD(adsmodlist_resilience03[[3]])$Provenance %>% as.data.frame() %>% filter(`p adj` <0.05)
ggplot(as.data.frame(ads_calcs_list03[[3]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))
summary(adsmodlist_resilience03[[4]]) #significant
TukeyHSD(adsmodlist_resilience03[[4]])$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)
ggplot(as.data.frame(ads_calcs_list03[[4]]), aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))


#spline
droughtyear = 2003
buffertime = seq(0,3,1)
spline_calcs_list03<- list()
for(i in 1:length(buffertime)){
drought_rw03<- growth.detrended.df %>% 
  filter(year >= droughtyear - buffertime[i] & year <= droughtyear + buffertime[i]) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_rw = mean(rw_spline))

predrought_rw03<- growth.detrended.df %>% 
  filter(year >= droughtyear - buffertime[i] - 1 - buffertime[i]*2 & year <= droughtyear - buffertime[i] - 1) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_rw = mean(rw_spline))

postdrought_rw03<- growth.detrended.df %>% 
  filter(year >= droughtyear + buffertime[i] + 1  & year <= droughtyear + buffertime[i] + 1 + buffertime[i]*2) %>% 
  group_by(tree) %>% 
  summarise(postdrought_ave_rw = mean(rw_spline))

spline_calcs_list03[[i]] <- left_join(drought_rw03,predrought_rw03) %>% left_join(postdrought_rw03) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")
}

splinemodlist_resistance03<- list()
for(i in 1:length(spline_calcs_list03)){
splinemodlist_resistance03[[i]] <- aov(resistance ~ Provenance, data=spline_calcs_list03[[i]])
}
summary(splinemodlist_resistance03[[1]])
summary(splinemodlist_resistance03[[2]]) 
summary(splinemodlist_resistance03[[3]]) #significant
summary(splinemodlist_resistance03[[4]]) 

splinemodlist_resilience03<- list()
for(i in 1:length(spline_calcs_list03)){
splinemodlist_resilience03[[i]] <- aov(resilience ~ Provenance, data=spline_calcs_list03[[i]])
}
summary(splinemodlist_resilience03[[1]])
summary(splinemodlist_resilience03[[2]]) 
summary(splinemodlist_resilience03[[3]]) 
summary(splinemodlist_resilience03[[4]]) 
```


```{r}
missingyrs <- prov_good %>% 
  mutate(year=rownames(prov_good)) %>% 
  pivot_longer(`32I2`:`47C2`) %>% 
  filter(!is.na(value)) %>% 
  group_by(name) %>% 
  summarise(minyr=min(year), maxyr=max(year)) %>% 
  mutate(missingyrs=as.numeric(minyr) - 1970) 

hist(missingyrs$missingyrs)

```

#Multiple Drought years

```{r}
### 1988 drought, 5 year periods
plantation_clim_xtremes %>% 
  group_by(year) %>% 
  summarise(n=n()) %>% 
  filter(n>3)

prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(!is.na(value)) %>% 
  group_by(year) %>% 
  summarise(n=n()) %>% 
  print(n=50)

drought88_rw_5yr<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1985 & year < 1991) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought88_rw_5yr<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1980 & year < 1986) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought88_rw_5yr<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1990 & year < 1996) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_88_5yr <- left_join(drought88_rw_5yr,predrought88_rw_5yr) %>% left_join(postdrought88_rw_5yr) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

raw_88_5yr_aov_resist <- aov(resistance ~ Provenance, data=raw_calcs_88_5yr)
summary(raw_88_5yr_aov_resist)
raw_88_5yr_aov_resil <- aov(resilience ~ Provenance, data=raw_calcs_88_5yr)
summary(raw_88_5yr_aov_resil)

ggplot(raw_calcs_88_5yr, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("raw")
ggplot(raw_calcs_88_5yr, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("raw")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

### 1988 drought, 3 year periods

drought88_rw_3yr<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1986 & year < 1990) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought88_rw_3yr<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1983 & year < 1987) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value))

postdrought88_rw_3yr<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1989 & year < 1993) %>% 
  group_by(name) %>% 
  summarise(postdrought_ave_rw = mean(value))

raw_calcs_88_3yr <- left_join(drought88_rw_3yr,predrought88_rw_3yr) %>% left_join(postdrought88_rw_3yr) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw, resilience = postdrought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

raw_88_3yr_aov_resist <- aov(resistance ~ Provenance, data=raw_calcs_88_3yr)
summary(raw_88_3yr_aov_resist)
raw_88_3yr_aov_resil <- aov(resilience ~ Provenance, data=raw_calcs_88_3yr)
summary(raw_88_3yr_aov_resil)

ggplot(raw_calcs_88_3yr, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  ggtitle("raw")
ggplot(raw_calcs_88_3yr, aes(x=Provenance, y=resilience))+
  geom_boxplot()+
  geom_point()+
  ggtitle("raw")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

calcs_2droughts <- raw_calcs_88_3yr %>% 
  bind_rows(raw_calcs_list03[[3]]) %>% 
  group_by(name,Provenance) %>% 
  summarise(mean_resistance = mean(resistance), mean_resilience = mean(resilience)) 

twomod_resistance <- aov(mean_resistance~ Provenance, data=calcs_2droughts)
summary(twomod_resistance)

twomod_resilience <- aov(mean_resilience ~ Provenance, data=calcs_2droughts)
summary(twomod_resilience)
TukeyHSD(twomod_resilience)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)

ggplot(calcs_2droughts, aes(x=Provenance, y=mean_resilience))+
  geom_boxplot()+
  geom_point()+
  geom_hline(yintercept=1, col="red")+
  ggtitle("2 droughts raw")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

```

#Other Metrics

```{r}

drought_rw_new<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year == 2002) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_new<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1985 & year <2002) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value, na.rm=T))

#resistance
new_calcs <- left_join(drought_rw_new,predrought_rw_new) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

new_aov_resist <- aov(resistance ~ Provenance, data=new_calcs)
summary(new_aov_resist) #no difference in resistance when compared to average growth 1985-2002

ggplot(new_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  geom_hline(yintercept=1, col="red")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#recovery time (only 46 trees recovered out of 99, 37 didn't reduce growth in 2002)

no_reduction<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year == 2002) %>%
  left_join(predrought_rw_new) %>% 
  mutate(diff = predrought_ave_rw - value) %>% 
  filter(diff<0) ##37 trees didn't reduce growth in 2002

recover_time<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>%
  filter(!name %in% no_reduction$name) %>% 
  filter(year > 2001) %>%
  left_join(predrought_rw_new) %>% 
  mutate(diff = value - predrought_ave_rw) %>% 
  filter(diff>0) %>% 
  group_by(name) %>% 
  summarise(minyr = min(year)) %>% 
  mutate(recoverytime = as.numeric(minyr) - 2002) %>% 
  mutate(name = paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


aov.recover <- aov(recoverytime ~ Provenance, data=recover_time)
summary(aov.recover)  #no difference in recovery time

ggplot(recover_time, aes(x=Provenance, y=recoverytime))+
  geom_boxplot()+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

not_recovered<- dbh_age_good %>% 
  filter(! tree %in% paste("X",no_reduction$name,sep="")) %>% 
  filter(! tree %in% recover_time$name)

prop.recovered <- dbh_age_good %>% 
  filter(year>1984 & !tree %in% paste("X",no_reduction$name,sep="")) %>% 
  group_by(Provenance) %>% 
  summarise(ntree = length(unique(tree))) %>% 
  left_join(not_recovered %>% 
              group_by(Provenance) %>% 
              summarise(ntree_NR = length(unique(tree)))) %>% 
  mutate(ntree_NR = ifelse(is.na(ntree_NR),0,ntree_NR)) %>% 
  pivot_longer(ntree:ntree_NR)

ggplot(prop.recovered, aes(x=Provenance, y=value, fill=name))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ggplot(not_recovered %>% filter(year>1984), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance, scales="free")

#total growth reduction
growth_red_df<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(!name %in% no_reduction$name) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  filter(!name %in% unique(not_recovered$tree)) %>% 
  filter(year>2001) %>% 
  left_join(predrought_rw_new %>% mutate(name=paste("X",name,sep=""))) %>% 
  mutate(growth_red = predrought_ave_rw-value) %>% 
  filter(growth_red>0) %>% 
  group_by(name) %>% 
  summarise(total.growth.red = max(growth_red)) %>% 
  left_join(recover_time) %>% 
  mutate(ave.growth.red = total.growth.red/recoverytime)

aov.tgr <- aov(total.growth.red ~ Provenance, data=growth_red_df)
summary(aov.tgr)  
TukeyHSD(aov.tgr)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.05)

ggplot(growth_red_df, aes(x=Provenance, y=total.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

aov.agr <- aov(ave.growth.red ~ Provenance, data=growth_red_df)
summary(aov.agr) #no difference in average growth reduction rate

ggplot(growth_red_df, aes(x=Provenance, y=ave.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#average recovery rate
recover.rate.df <- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(!name %in% no_reduction$name) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  filter(!name %in% unique(not_recovered$tree)) %>% 
  filter(year>2001) %>% 
  left_join(predrought_rw_new %>% mutate(name=paste("X",name,sep=""))) %>% 
  mutate(growth_red = predrought_ave_rw-value) %>% 
  filter(year==2002) %>% 
  left_join(recover_time) %>% 
  mutate(recover.rate = (growth_red/recoverytime)/growth_red*100)

aov.arr <- aov(recover.rate ~ Provenance, data=recover.rate.df)
summary(aov.arr) #no difference in average growth reduction rate

ggplot(recover.rate.df, aes(x=Provenance, y=recover.rate))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

####


```

##detrended

```{r}


drought_ne_new<- growth.detrended.ne.df %>% 
  filter(year == 2002) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_ne = mean(rw_spline))

predrought_ne_new<- growth.detrended.ne.df %>% 
  filter(year > 1985 & year <2002) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_ne = mean(rw_spline, na.rm=T))

#resistance
ne_new_calcs <- left_join(drought_ne_new,predrought_ne_new) %>% 
  mutate(resistance = drought_ave_ne/predrought_ave_ne) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")

ne_new_aov_resist <- aov(resistance ~ Provenance, data=ne_new_calcs)
summary(ne_new_aov_resist) #no difference in resistance when compared to average growth 1985-2002

ggplot(ne_new_calcs, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  geom_hline(yintercept=1, col="red")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#recovery time 

ne_no_reduction<- growth.detrended.ne.df %>% 
  filter(year == 2002) %>%
  left_join(predrought_ne_new) %>% 
  mutate(diff = predrought_ave_ne - rw_spline) %>% 
  filter(diff<0) ##55 trees didn't reduce growth in 2002

ne_recover_time<- growth.detrended.ne.df %>%
  filter(!tree %in% ne_no_reduction$tree) %>% 
  filter(year > 2001) %>%
  left_join(predrought_ne_new) %>% 
  mutate(diff = rw_spline - predrought_ave_ne) %>% 
  filter(diff>0) %>% 
  group_by(tree) %>% 
  summarise(minyr = min(year)) %>% 
  mutate(recoverytime = as.numeric(minyr) - 2002) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")


aov.recover.ne <- aov(recoverytime ~ Provenance, data=ne_recover_time)
summary(aov.recover.ne)  #no difference in recovery time

ggplot(ne_recover_time, aes(x=Provenance, y=recoverytime))+
  geom_boxplot()+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ne_not_recovered<- dbh_age_good %>% 
  filter(! tree %in% ne_no_reduction$tree) %>% 
  filter(! tree %in% ne_recover_time$tree)

ne.prop.recovered <- dbh_age_good %>% 
  filter(year>1984 & !tree %in% ne_no_reduction$tree) %>% 
  group_by(Provenance) %>% 
  summarise(ntree = length(unique(tree))) %>% 
  left_join(ne_not_recovered %>% 
              group_by(Provenance) %>% 
              summarise(ntree_NR = length(unique(tree)))) %>% 
  mutate(ntree_NR = ifelse(is.na(ntree_NR),0,ntree_NR)) %>% 
  pivot_longer(ntree:ntree_NR)

ggplot(ne.prop.recovered, aes(x=Provenance, y=value, fill=name))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ggplot(ne_not_recovered %>% filter(year>1984), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance, scales="free")

#total growth reduction
growth_red_ne_df<- growth.detrended.ne.df %>% 
  filter(!tree %in% ne_no_reduction$tree) %>% 
  filter(!tree %in% unique(ne_not_recovered$tree)) %>% 
  filter(year>2001) %>% 
  left_join(predrought_ne_new) %>% 
  mutate(growth_red = predrought_ave_ne-rw_spline) %>% 
  filter(growth_red>0) %>% 
  group_by(tree) %>% 
  summarise(total.growth.red = max(growth_red)) %>% 
  left_join(ne_recover_time) %>% 
  mutate(ave.growth.red = total.growth.red/recoverytime)

aov.tgr.ne <- aov(total.growth.red ~ Provenance, data=growth_red_ne_df)
summary(aov.tgr.ne)  

ggplot(growth_red_ne_df, aes(x=Provenance, y=total.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

aov.agr.ne <- aov(ave.growth.red ~ Provenance, data=growth_red_ne_df)
summary(aov.agr.ne) #no difference in average growth reduction rate

ggplot(growth_red_ne_df, aes(x=Provenance, y=ave.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#average recovery rate
recover.rate.ne.df <- growth.detrended.ne.df %>% 
  filter(!tree %in% ne_no_reduction$tree) %>% 
  filter(!tree %in% unique(ne_not_recovered$tree)) %>% 
  filter(year>2001) %>% 
  left_join(predrought_ne_new) %>% 
  mutate(growth_red = predrought_ave_ne-rw_spline) %>% 
  filter(year==2002) %>% 
  left_join(ne_recover_time) %>% 
  mutate(recover.rate = (growth_red/recoverytime)/growth_red*100)

aov.ne.arr <- aov(recover.rate ~ Provenance, data=recover.rate.ne.df)
summary(aov.ne.arr) #no difference in average growth reduction rate

ggplot(recover.rate.ne.df, aes(x=Provenance, y=recover.rate))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#### next try drought year = 2003


```

#Other Metrics 2003

```{r}
drought_rw_new03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year == 2003) %>% 
  group_by(name) %>% 
  summarise(drought_ave_rw = mean(value))

predrought_rw_new03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year > 1985 & year <2003) %>% 
  group_by(name) %>% 
  summarise(predrought_ave_rw = mean(value, na.rm=T))

#resistance
new_calcs03 <- left_join(drought_rw_new03,predrought_rw_new03) %>% 
  mutate(resistance = drought_ave_rw/predrought_ave_rw) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))

new_aov_resist03 <- aov(resistance ~ Provenance, data=new_calcs03)
summary(new_aov_resist03) #significant difference in 2003 when compared to average growth 1985-2002
TukeyHSD(new_aov_resist03)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.5) #no strong pairwise differences

ggplot(new_calcs03, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  geom_hline(yintercept=1, col="red")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#recovery time (only 58 trees recovered out of 114, 22 didn't reduce growth in 2002)

no_reduction03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(year == 2003) %>%
  left_join(predrought_rw_new03) %>% 
  mutate(diff = predrought_ave_rw - value) %>% 
  filter(diff<0) ##22 trees didn't reduce growth in 2002

recover_time03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>%
  filter(!name %in% no_reduction03$name) %>% 
  filter(year > 2002) %>%
  left_join(predrought_rw_new03) %>% 
  mutate(diff = value - predrought_ave_rw) %>% 
  filter(diff>0) %>% 
  group_by(name) %>% 
  summarise(minyr = min(year)) %>% 
  mutate(recoverytime = as.numeric(minyr) - 2003) %>% 
  mutate(name = paste("X",name,sep="")) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by=c("name" = "tree"))


aov.recover03 <- aov(recoverytime ~ Provenance, data=recover_time03)
summary(aov.recover03)  #marginal difference in recovery time

ggplot(recover_time03, aes(x=Provenance, y=recoverytime))+
  geom_boxplot()+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

not_recovered03<- dbh_age_good %>% 
  filter(! tree %in% paste("X",no_reduction03$name,sep="")) %>% 
  filter(! tree %in% recover_time03$name)

prop.recovered03 <- dbh_age_good %>% 
  filter(year>1984 & !tree %in% paste("X",no_reduction03$name,sep="")) %>% 
  group_by(Provenance) %>% 
  summarise(ntree = length(unique(tree))) %>% 
  left_join(not_recovered03 %>% 
              group_by(Provenance) %>% 
              summarise(ntree_NR = length(unique(tree)))) %>% 
  mutate(ntree_NR = ifelse(is.na(ntree_NR),0,ntree_NR)) %>% 
  pivot_longer(ntree:ntree_NR)

ggplot(prop.recovered03, aes(x=Provenance, y=value, fill=name))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ggplot(not_recovered03 %>% filter(year>1984), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance, scales="free")

#total growth reduction
growth_red_df03<- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(!name %in% no_reduction03$name) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  filter(!name %in% unique(not_recovered03$tree)) %>% 
  filter(year>2002) %>% 
  left_join(predrought_rw_new03 %>% mutate(name=paste("X",name,sep=""))) %>% 
  mutate(growth_red = predrought_ave_rw-value) %>% 
  filter(growth_red>0) %>% 
  group_by(name) %>% 
  summarise(total.growth.red = max(growth_red)) %>% 
  left_join(recover_time03) %>% 
  mutate(ave.growth.red = total.growth.red/recoverytime)

aov.tgr03 <- aov(total.growth.red ~ Provenance, data=growth_red_df03)
summary(aov.tgr03)  #significant differences
TukeyHSD(aov.tgr03)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.1)

ggplot(growth_red_df03, aes(x=Provenance, y=total.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

aov.agr03 <- aov(ave.growth.red ~ Provenance, data=growth_red_df03)
summary(aov.agr03) #significant differences in average growth reduction rate
TukeyHSD(aov.agr03)$Provenance %>% as.data.frame() %>% filter(`p adj` < 0.1)


ggplot(growth_red_df03, aes(x=Provenance, y=ave.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#average recovery rate
recover.rate.df03 <- prov_good %>% 
  mutate(year = rownames(prov_good)) %>% 
  pivot_longer(-year) %>% 
  filter(!name %in% no_reduction03$name) %>% 
  mutate(name=paste("X",name,sep="")) %>% 
  filter(!name %in% unique(not_recovered03$tree)) %>% 
  filter(year>2002) %>% 
  left_join(predrought_rw_new03 %>% mutate(name=paste("X",name,sep=""))) %>% 
  mutate(growth_red = predrought_ave_rw-value) %>% 
  filter(year==2003) %>% 
  left_join(recover_time03) %>% 
  mutate(recover.rate = (growth_red/recoverytime)/growth_red*100)

aov.arr03 <- aov(recover.rate ~ Provenance, data=recover.rate.df03)
summary(aov.arr03) #no difference in average growth reduction rate

ggplot(recover.rate.df03, aes(x=Provenance, y=recover.rate))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

####


```

##detrended

```{r}


drought_ne_new03<- growth.detrended.ne.df %>% 
  filter(year == 2003) %>% 
  group_by(tree) %>% 
  summarise(drought_ave_ne = mean(rw_spline))

predrought_ne_new03<- growth.detrended.ne.df %>% 
  filter(year > 1985 & year <2003) %>% 
  group_by(tree) %>% 
  summarise(predrought_ave_ne = mean(rw_spline, na.rm=T))

#resistance
ne_new_calcs03 <- left_join(drought_ne_new03,predrought_ne_new03) %>% 
  mutate(resistance = drought_ave_ne/predrought_ave_ne) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")

ne_new_aov_resist03 <- aov(resistance ~ Provenance, data=ne_new_calcs03)
summary(ne_new_aov_resist03) #no difference in resistance when compared to average growth 1985-2002

ggplot(ne_new_calcs03, aes(x=Provenance, y=resistance))+
  geom_boxplot()+
  geom_point()+
  geom_hline(yintercept=1, col="red")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#recovery time 

ne_no_reduction03<- growth.detrended.ne.df %>% 
  filter(year == 2003) %>%
  left_join(predrought_ne_new03) %>% 
  mutate(diff = predrought_ave_ne - rw_spline) %>% 
  filter(diff<0) ##31 trees didn't reduce growth in 2002

ne_recover_time03<- growth.detrended.ne.df %>%
  filter(!tree %in% ne_no_reduction03$tree) %>% 
  filter(year > 2002) %>%
  left_join(predrought_ne_new03) %>% 
  mutate(diff = rw_spline - predrought_ave_ne) %>% 
  filter(diff>0) %>% 
  group_by(tree) %>% 
  summarise(minyr = min(year)) %>% 
  mutate(recoverytime = as.numeric(minyr) - 2003) %>% 
  left_join(dbh_age %>% select(tree,Provenance) %>% unique(), by="tree")


aov.recover03.ne <- aov(recoverytime ~ Provenance, data=ne_recover_time03)
summary(aov.recover03.ne)  #no difference in recovery time

ggplot(ne_recover_time03, aes(x=Provenance, y=recoverytime))+
  geom_boxplot()+
  geom_point()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ne_not_recovered03<- dbh_age_good %>% 
  filter(! tree %in% ne_no_reduction03$tree) %>% 
  filter(! tree %in% ne_recover_time03$tree)

ne.prop.recovered03 <- dbh_age_good %>% 
  filter(year>1984 & !tree %in% ne_no_reduction03$tree) %>% 
  group_by(Provenance) %>% 
  summarise(ntree = length(unique(tree))) %>% 
  left_join(ne_not_recovered03 %>% 
              group_by(Provenance) %>% 
              summarise(ntree_NR = length(unique(tree)))) %>% 
  mutate(ntree_NR = ifelse(is.na(ntree_NR),0,ntree_NR)) %>% 
  left_join(ne_no_reduction03 %>% group_by(Provenance) %>% summarise(n_nored = n())) %>% 
  mutate(n_nored = ifelse(is.na(n_nored),0,n_nored)) %>% 
  mutate(n_recovered = ntree-ntree_NR) %>% 
  mutate(prop.recovered = n_recovered/ntree, prop.nored = n_nored/(n_nored+ntree)) %>% 
  pivot_longer(ntree_NR:n_recovered)

prop.recovered.order<- unique(ne.prop.recovered03 %>% select(Provenance,prop.recovered, prop.nored)) %>% arrange(prop.recovered)

prop.nored.order<- unique(ne.prop.recovered03 %>% select(Provenance,prop.recovered, prop.nored)) %>% arrange(prop.nored)


dbh_age_good %>% 
  group_by(Provenance) %>% 
  summarise(ntree = length(unique(tree))) 

ggplot(ne.prop.recovered03, aes(x=factor(Provenance, levels = prop.nored.order$Provenance), y=value, fill=name))+
  geom_bar(stat="identity")+
  scale_fill_manual(values=c("darkgreen","lightblue","black"))+
  ylab("number of trees")+
  theme(axis.text.x = element_text(angle=45, hjust=1))

ggplot(ne_not_recovered03 %>% filter(year>1984), aes(x=year, y=rw, col=tree))+
  geom_point()+
  geom_line()+
  facet_wrap(~Provenance, scales="free")

#total growth reduction
growth_red_ne_df03<- growth.detrended.ne.df %>% 
  filter(!tree %in% ne_no_reduction03$tree) %>% 
  filter(!tree %in% unique(ne_not_recovered03$tree)) %>% 
  filter(year>2002) %>% 
  left_join(predrought_ne_new03) %>% 
  mutate(growth_red = predrought_ave_ne-rw_spline) %>% 
  filter(growth_red>0) %>% 
  group_by(tree) %>% 
  summarise(total.growth.red = sum(growth_red)) %>% 
  left_join(ne_recover_time03) %>% 
  mutate(ave.growth.red = total.growth.red/recoverytime)

aov.tgr03.ne <- aov(total.growth.red ~ Provenance, data=growth_red_ne_df03)
summary(aov.tgr03.ne)  

ggplot(growth_red_ne_df03, aes(x=Provenance, y=total.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

aov.agr03.ne <- aov(ave.growth.red ~ Provenance, data=growth_red_ne_df03)
summary(aov.agr03.ne) #no difference in average growth reduction rate

ggplot(growth_red_ne_df03, aes(x=Provenance, y=ave.growth.red))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

#average recovery rate
recover.rate.ne.df03 <- growth.detrended.ne.df %>% 
  filter(!tree %in% ne_no_reduction03$tree) %>% 
  filter(!tree %in% unique(ne_not_recovered03$tree)) %>% 
  filter(year>2002) %>% 
  left_join(predrought_ne_new03) %>% 
  mutate(growth_red = predrought_ave_ne-rw_spline) %>% 
  filter(year==2003) %>% 
  left_join(ne_recover_time03) %>% 
  mutate(recover.rate = (growth_red/recoverytime)/growth_red*100)

aov.ne.arr03 <- aov(recover.rate ~ Provenance, data=recover.rate.ne.df03)
summary(aov.ne.arr03) #no difference in average growth reduction rate

ggplot(recover.rate.ne.df03, aes(x=Provenance, y=recover.rate))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))

```

#Model growth-climate relationship

```{r}
##maybe try a moving window analysis here or just use climate vars that have been shown to effect PIEN growth in past studies


plantation_clim_minus1<- plantation_clim %>% mutate(year = year+1) %>% 
  select(c(CN:year,ppt_gs:ppt_sp, vpdmax_sm:vpdmax_sp, FDSI, aet_sum, cwd_wy, spei_sum))

colnames(plantation_clim_minus1)<- paste("prior_",colnames(plantation_clim_minus1),sep="")

growth.detrended.ne.df %>% 
  left_join(plantation_clim) %>% 
  left_join(plantation_clim_minus1, by=c("year" = "prior_year", "CN" = "prior_CN")) %>% View()

plantation_clim_cor<- plantation_clim %>% 
  select(c(CN:year,ppt_gs:ppt_sp, vpdmax_sm:vpdmax_sp, FDSI, aet_sum, cwd_wy, spei_sum)) %>% 
  left_join(plantation_clim_minus1, by=c("year" = "prior_year", "CN" = "prior_CN")) %>% 
  filter(! year %in% c(1971)) %>% 
  ungroup() %>% 
  filter(year>1970) %>% 
  select(-c(CN,year)) %>% 
  cor()

plantation_clim_cor>0.7

ggcorrplot(plantation_clim_cor, type="lower", insig = "blank", lab=TRUE)

plantation_clim_cor_yrof<- plantation_clim %>% 
  select(c(CN:year,ppt_gs:ppt_sp, vpdmax_sm:vpdmax_sp, FDSI, aet_sum, cwd_wy, spei_sum)) %>% 
  filter(! year %in% c(1970)) %>% 
  ungroup() %>% 
  filter(year>1970) %>% 
  select(-c(CN,year)) %>% 
  cor()

ggcorrplot(plantation_clim_cor_yrof, type="lower", insig = "blank", lab=TRUE)


growth_climate_df_ne <- growth.detrended.ne.df %>% 
  left_join(plantation_clim) %>% 
  select(c(CN:year,ppt_gs:ppt_sp, vpdmax_sm:vpdmax_sp, FDSI, aet_sum, cwd_wy, spei_sum)) %>% 
  left_join(plantation_clim_minus1, by=c("year" = "prior_year", "CN" = "prior_CN")) %>% 
  ungroup() %>% 
  filter(year>1970)

growth_climate_df_ne$rw_spline

climvars <- colnames(growth_climate_df_ne %>% dplyr::select(-c(CN:year)))
tree_ids_ne <- unique(growth_climate_df_ne$tree)


gc_cor_df_ne<-data.frame()
for(i in 1:length(climvars)){
  for(j in 1:length(tree_ids_ne)){
  clim <- growth_climate_df_ne %>% dplyr::filter(tree == tree_ids_ne[j]) %>% dplyr::select(climvars[i])
  tree <- growth_climate_df_ne %>% dplyr::filter(tree == tree_ids_ne[j]) %>% select(rw_spline)
  gc.cor <- cor(clim, tree)
  row <- cbind(climvars[i], tree_ids_ne[j], gc.cor) %>% as.data.frame()
  gc_cor_df_ne <- bind_rows(gc_cor_df_ne, row)
}}

gc_cor_df_ne %>% arrange(V2)

gc_cor_df_ne %>% 
  group_by(V2) %>% 
  summarise(maxcor = max(rw_spline)) %>% 
  left_join(gc_cor_df_ne) %>% 
  group_by(V1) %>% 
  summarise(n=n())

gc_cor_df_ne %>% 
  group_by(V2) %>% 
  summarise(mincor = min(rw_spline)) %>% 
  left_join(gc_cor_df_ne) %>% 
  arrange(desc(mincor)) %>% 
  print(n=35)

fdsi_cor_ne_provs<- gc_cor_df_ne %>% 
  filter(V1 == "FDSI") %>% 
  left_join(dbh_age_good %>% select(tree, Provenance) %>% unique(), by=c("V2"="tree")) %>% 
  mutate(cor=as.numeric(rw_spline))
  
ggplot(fdsi_cor_ne_provs, aes(x=factor(Provenance, levels=prov_clim_states %>% arrange(Latitude) %>% pull(Provenance)), y=cor, fill=Provenance))+
  geom_boxplot()



raw_growth <- prov_good_nona %>%
  mutate(year=as.numeric(row.names(prov_good_nona))) %>% 
  pivot_longer(`32I2`:`47C2`)


growth_climate_df_raw <- raw_growth %>% 
  left_join(plantation_clim) %>% 
  select(c(CN:year,ppt_gs:ppt_sp, vpdmax_sm:vpdmax_sp, FDSI, aet_sum, cwd_wy, spei_sum)) %>% 
  left_join(plantation_clim_minus1, by=c("year" = "prior_year", "CN" = "prior_CN")) %>% 
  ungroup() %>% 
  filter(year>1970)

climvars_raw <- colnames(growth_climate_df_raw %>% dplyr::select(-c(CN:year)))
tree_ids <- unique(growth_climate_df_raw$name)

gc_cor_df_raw<-data.frame()
for(i in 1:length(climvars_raw)){
  for(j in 1:length(tree_ids)){
  clim <- growth_climate_df_raw %>% dplyr::filter(name == tree_ids[j]) %>% dplyr::select(climvars_raw[i])
  tree <- growth_climate_df_raw %>% dplyr::filter(name == tree_ids[j]) %>% select(value)
  gc.cor <- cor(clim, tree)
  row <- cbind(climvars_raw[i], tree_ids[j], gc.cor) %>% as.data.frame()
  gc_cor_df_raw <- bind_rows(gc_cor_df_raw, row)
}}

gc_cor_df_raw %>% arrange(desc(value))

gc_cor_df_raw %>% 
  group_by(V2) %>% 
  summarise(value = max(value)) %>% 
  left_join(gc_cor_df_raw) %>% 
  group_by(V1) %>% 
  summarise(n=n())

gc_cor_df_raw %>% 
  group_by(V2) %>% 
  summarise(value = min(value)) %>% 
  left_join(gc_cor_df_raw) %>% 
  arrange(desc(value)) %>% 
  print(n=35)

fdsi_cor_provs<- gc_cor_df_raw %>% 
  filter(V1 == "FDSI") %>% 
  mutate(tree=paste("X",V2, sep="")) %>% 
  left_join(dbh_age_good %>% select(tree, Provenance) %>% unique()) %>% 
  mutate(value=as.numeric(value))
  
ggplot(fdsi_cor_provs, aes(x=factor(Provenance, levels=prov_clim_states %>% arrange(Latitude) %>% pull(Provenance)), y=value, fill=Provenance))+
  geom_boxplot()

unique(fdsi_cor_provs$Provenance)

unique(prov_clim_states$Provenance)

##try correlating growth in year with climate in year - 1

gc_cor_lag_df_raw<-data.frame()
for(i in 1:length(climvars_raw)){
  for(j in 1:length(tree_ids)){
  clim <- growth_climate_df_raw %>% dplyr::filter(name == tree_ids[j]) %>% mutate(year = year+1) %>% filter(year<2011) %>%  dplyr::select(climvars_raw[i]) 
  tree <- growth_climate_df_raw %>% dplyr::filter(name == tree_ids[j]) %>% filter(year > 1991) %>% select(value)
  gc.cor <- cor(clim, tree)
  row <- cbind(climvars_raw[i], tree_ids[j], gc.cor) %>% as.data.frame()
  gc_cor_lag_df_raw <- bind_rows(gc_cor_lag_df_raw, row)
  }}

gc_cor_lag_df_raw

fdsi_cor_lag_provs<- gc_cor_lag_df_raw %>% 
  filter(V1 == "FDSI") %>% 
  mutate(tree=paste("X",V2, sep="")) %>% 
  left_join(dbh_age_good %>% select(tree, Provenance) %>% unique()) %>% 
  mutate(value=as.numeric(value))
  
ggplot(fdsi_cor_lag_provs, aes(x=factor(Provenance, levels=prov_clim_states %>% arrange(Latitude) %>% pull(Provenance)), y=value, fill=Provenance))+
  geom_boxplot()+
  geom_point()

ggplot(data=growth_climate_df_raw %>% mutate(tree=paste("X",tree,sep="")) %>% left_join(dbh_age_good %>% select(tree,Provenance) %>% unique(), by="tree"))+
  geom_point(aes(x=year, y=value, col=name))+
  #geom_line(data=growth_climate_df_raw, aes(x=year, y=value, col=name))+
  #geom_line(data=growth_climate_df_raw, aes(x=year, y=FDSI), col="black")+
  facet_grid(~Provenance, scales="free")
```

##linear models
```{r}
  
####try just modeling one tree's growth on last year's FDSI
testdata<- growth_climate_df_raw %>% 
  filter(name=="32I2") %>% 
  select(year, value) %>% 
  filter(year > 1991) %>% 
  left_join(growth_climate_df_raw %>% 
  select(year, FDSI) %>% unique() %>% 
  mutate(year = year+1) %>% 
  rename(FDSI_prior = FDSI) %>% 
  filter(year <2011)) %>% 
  filter(year<2003)

testmod1 <- lm(value ~ FDSI_prior, data=testdata)
summary(testmod1)


newdata <- growth_climate_df_raw %>% 
  filter(name=="32I2") %>% 
  select(year, value) %>% 
  filter(year > 1991) %>% 
  left_join(growth_climate_df_raw %>% 
  select(year, FDSI) %>% unique() %>% 
  mutate(year = year+1) %>% 
  rename(FDSI_prior = FDSI) %>% 
  filter(year <2011)) %>% 
  filter(year>2002)


testdata_predictions<- testdata %>% bind_cols(prediction= predict(testmod1)) %>% 
  bind_rows(newdata %>% left_join(data.frame(year=seq(2003,2010,1), prediction=predict(testmod1, newdata))))

ggplot(data=testdata_predictions, aes(x=year, y=value))+
  geom_point()+
  geom_line(col="black")+
  geom_line(data=testdata_predictions, aes(x=year, y=prediction), col="red")+
  geom_point(data=testdata_predictions, aes(x=year, y=prediction), col="red")+
  geom_bar(stat="identity", aes(x=year, y=FDSI_prior))

##
predrought_rawdata<- growth_climate_df_raw %>% 
  select(name, year, value) %>% 
  filter(year > 1991) %>% 
  left_join(growth_climate_df_raw %>% 
  select(year, FDSI) %>% unique() %>% 
  mutate(year = year+1) %>% 
  rename(FDSI_prior = FDSI) %>% 
  filter(year <2011)) %>% 
  filter(year<2003) %>% 
  mutate(tree=paste("X",name,sep="")) %>% 
  left_join(dbh_age_good %>% select(tree,Provenance) %>% unique(), by="tree")

postdrought_rawdata<- growth_climate_df_raw %>% 
  select(name, year, value) %>% 
  filter(year > 1991) %>% 
  left_join(growth_climate_df_raw %>% 
  select(year, FDSI) %>% unique() %>% 
  mutate(year = year+1) %>% 
  rename(FDSI_prior = FDSI) %>% 
  filter(year <2011)) %>% 
  filter(year>2002) %>% 
  mutate(tree=paste("X",name,sep="")) %>% 
  left_join(dbh_age_good %>% select(tree,Provenance) %>% unique(), by="tree")


ggplot(predrought_rawdata, aes(x=FDSI_prior, y=value, col=tree))+
  geom_point()+
  geom_smooth(method="lm")

treenames<- unique(predrought_rawdata$name)

modresultdf<- data.frame()
for(i in 1:length(treenames)){
  predata = predrought_rawdata %>% filter(name==treenames[i])
  postdata = postdrought_rawdata %>% filter(name==treenames[i])
  mod = lm(value ~ FDSI_prior, data=predata)
  adjrsquared<- summary(mod)$adj.r.squared
  newdata <-  predata %>% bind_cols(prediction= predict(mod)) %>% 
  bind_rows(postdata %>% left_join(data.frame(year=seq(2003,2010,1), prediction=predict(mod, postdata)))) %>% 
    mutate(adjrsquared = adjrsquared)
modresultdf<- bind_rows(modresultdf,newdata)
}


ggplot(data=modresultdf %>% filter(adjrsquared>0.2), aes(x=year, y=value))+
  geom_point()+
  geom_line(col="black")+
  geom_line(data=modresultdf %>% filter(adjrsquared>0.2), aes(x=year, y=prediction), col="red")+
  geom_point(data=modresultdf %>% filter(adjrsquared>0.2), aes(x=year, y=prediction), col="red")+
  geom_bar(stat="identity", aes(x=year, y=FDSI_prior, fill=Provenance))+
  geom_text(data= data.frame(name=modresultdf %>% filter(adjrsquared>0.2) %>% pull(name) %>% unique(), year=1993,value=max(modresultdf %>% filter(adjrsquared>0.2) %>% pull(value)), label=modresultdf %>% filter(adjrsquared>0.2) %>% pull(adjrsquared) %>% unique()), aes(label=paste("adj r2 =", round(label,1))))+
  geom_vline(xintercept=2003, col="darkred")+
  facet_wrap(~name)

provnames<- unique(modresultdf$Provenance)

ggplot(data=modresultdf %>% filter(Provenance==provnames[1]), aes(x=year, y=value))+
  geom_point()+
  geom_line(col="black")+
  geom_line(data=modresultdf %>% filter(Provenance==provnames[1]), aes(x=year, y=prediction), col="red")+
  geom_point(data=modresultdf %>% filter(Provenance==provnames[1]), aes(x=year, y=prediction), col="red")+
  geom_bar(stat="identity", aes(x=year, y=FDSI_prior))+
  geom_text(data= data.frame(name=modresultdf %>% filter(Provenance==provnames[1]) %>% pull(name) %>% unique(), year=1993,value=max(modresultdf %>% filter(Provenance==provnames[1]) %>% pull(value)), label=modresultdf %>% filter(Provenance==provnames[1]) %>% pull(adjrsquared) %>% unique()), aes(label=paste("adj r2 =", round(label,1))))+
  facet_wrap(~name)+
  ggtitle(provnames[1])

ggplot(data=modresultdf %>% filter(Provenance==provnames[2]), aes(x=year, y=value))+
  geom_point()+
  geom_line(col="black")+
  geom_line(data=modresultdf %>% filter(Provenance==provnames[2]), aes(x=year, y=prediction), col="red")+
  geom_point(data=modresultdf %>% filter(Provenance==provnames[2]), aes(x=year, y=prediction), col="red")+
  geom_bar(stat="identity", aes(x=year, y=FDSI_prior))+
  geom_text(data= data.frame(name=modresultdf %>% filter(Provenance==provnames[2]) %>% pull(name) %>% unique(), year=1993,value=max(modresultdf %>% filter(Provenance==provnames[2]) %>% pull(value)), label=modresultdf %>% filter(Provenance==provnames[2]) %>% pull(adjrsquared) %>% unique()), aes(label=paste("adj r2 =", round(label,2))))+
  facet_wrap(~name)+
  ggtitle(provnames[2])

ggplot(data=modresultdf %>% filter(Provenance==provnames[3]), aes(x=year, y=value))+
  geom_point()+
  geom_line(col="black")+
  geom_line(data=modresultdf %>% filter(Provenance==provnames[3]), aes(x=year, y=prediction), col="red")+
  geom_point(data=modresultdf %>% filter(Provenance==provnames[3]), aes(x=year, y=prediction), col="red")+
  geom_bar(stat="identity", aes(x=year, y=FDSI_prior))+
  geom_text(data= data.frame(name=modresultdf %>% filter(Provenance==provnames[3]) %>% pull(name) %>% unique(), year=1993,value=max(modresultdf %>% filter(Provenance==provnames[3]) %>% pull(value)), label=modresultdf %>% filter(Provenance==provnames[3]) %>% pull(adjrsquared) %>% unique()), aes(label=paste("adj r2 =", round(label,2))))+
  facet_wrap(~name)+
  ggtitle(provnames[3])




```